### DISCUSSION TITLE
CSS tweaks

### DISCUSSION THREAD

**Discussion by silverwings15** [piroor/treestyletab#2815] [General]
Figured this is as good a topic as any for the inaugural discussion thread (i wasn't sure whether to select the General or Q&A category, feel free to change as you see fit). i use the following css (as found in the wiki iirc) to remove the tab borders:

```css
/* Less visible tab dividers. A black border with a very low alpha slightly darkens any color. */
tab-item {
  border: solid 1px #00000012; 
}
```
which leads to a rather annoying gap on the very left of the tab, next to the active tab indicator. can i move the indicator into the newly vacated space? 

![image](https://user-images.githubusercontent.com/10742312/107887227-39e31580-6f37-11eb-9845-56d575baaec0.png)

also, i found out that that the active tab indicator also appears when you hover over a tab (easier to notice when you're using TST colored tabs). can i get rid of that as well?

![image](https://user-images.githubusercontent.com/10742312/107887277-84fd2880-6f37-11eb-9608-d8934c456fe6.png)

**Comment by piroor** [comment]
> which leads to a rather annoying gap on the very left of the tab, next to the active tab indicator. can i move the indicator into the newly vacated space?

Due to the CSS spec you cannot put the highlighter (active tab indicator) over the border line. You need to re-define it as a box-shadow or outline completely, otherwise you'll need to render it with a pseudo element. See also:
https://stackoverflow.com/questions/9601357/placing-border-inside-of-div-and-not-on-its-edge

> also, i found out that that the active tab indicator also appears when you hover over a tab (easier to notice when you're using TST colored tabs). can i get rid of that as well?

It is rendered with the color `--tab-highlighter-inactive`. You can unset it with a css:

```css
:root {
  --tab-highlighter-inactive: unset;
}
```
