### DISCUSSION TITLE
[css] how to change Text color of Loaded tabs

### DISCUSSION THREAD

**Discussion by KamelittaOida** [piroor/treestyletab#2872] [General]
Hi
I cannot seem to find the appropriate selector for that style.
I found the one for the not loaded tabs.
```
tab-item.discarded .label-content {
  color: #656464;
}

```

![image](https://user-images.githubusercontent.com/29007971/115991521-1b4d6a80-a5c9-11eb-9f77-f9fd7b7142d3.png)

**Comment by piroor** [comment]
Did you try the `:not()` pseudo class?

```css
tab-item:not(.discarded) .label-content {
  color: #656464;
}
```
