### DISCUSSION TITLE
option to mark tabs opened in background and not focused yet

### DISCUSSION THREAD

**Discussion by gtaltatra** [piroor/treestyletab#3060] [Q&A]
Is there an option to mark tabs opened in background and not focused yet (like in sideberry for example)?

**Comment by gtaltatra** [comment]
![kUPBE7dJHuADT1WKTg9eRkbe3SSswJIkvehognduZ9WNbSJFHM](https://user-images.githubusercontent.com/51547727/147275037-44e05f7f-1d83-452a-97e8-2c06ea55ebe1.jpg)
(Small triangle)

**Comment by irvinm** [comment]
You could try this https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#show-title-of-unread-tabs-in-italic-1363.  I believe opened tabs in the background fall into "unread" tabs.

However, I do believe this might also be triggered for sites that update\reload themselves.

**Reply by piroor** [reply]
I've tried to simulate Sideberry's appearance.

```css
tab-item.unread tab-favicon::after {
  border-style: solid;
  border-width: 5px 0 0 5px;
  border-color: transparent transparent transparent rgb(0,203,255);
  bottom:0;
  content: "";
  height: 0;
  left: 0;
  position: absolute;
  width: 0;
  z-index: 999;
}
```

Screenshot:
![image](https://user-images.githubusercontent.com/70062/147388066-083af751-2047-4067-a277-b23bf77c786c.png)
