### DISCUSSION TITLE
How can I increase tab text size without increasing tab size.

### DISCUSSION THREAD

**Discussion by mzso** [piroor/treestyletab#3101] [Q&A]
Hi!

(Sorry, but I can't find a dedicated discussion area for TST.)

I want to increase text size somewhat, with leaving the tabs the same size, but how can I do that?
I tried:
```css
tab-item {
  font-size: 10pt !important;
}
```
And variants, but not only it increases the tab size, but it also creates weird variable gaps between the tabs.
