### DISCUSSION TITLE
Displaying select tabs in Firefox tab bar

### DISCUSSION THREAD

**Discussion by TheBrambleShark** [piroor/treestyletab#3161] [Q&A] [answered]
Hi all,

This is a question for my understanding. The way I have TreeStyleTab set up currently, I have all of my tabs shown in TST's menu and I use userchrome to hide all tabs except for the currently active tab:
```css
/* Hide the native tabs */
#tabbrowser-tabs tab {
    visibility: collapse;
}
/* Show the active tab */
#tabbrowser-tabs tab[selected="true"] {
    visibility: visible;
}
```
This works great and behaves exactly as I would expect. However, when dealing with groups of tabs, it would be nice to have all of the tabs in that group show up at the top (that is, a parent and all of its children). I suspect the default sorting of this should have the group flattened, just for convenience sake.

At the moment though, I don't believe this is possible with just CSS styling. There do not appear to be any attributes I can target on the `<xul:tab/>` class. There is `linkedpanel` but that appears to be unrelated.

To prevent this from turning into an X-Y question, what I would like to do is be able to identify which tabs need to be visible so that I can unhide them. This could be done through appending a class to the tabs in the group, adding a new property, or programmatically querying the plugin for the tab ids of the active group and then either individually styling or adding a class as suggested previously.

I have two questions then:
1. Is this even possible?
2. If it is possible, what would be the best way to go about it?
