### DISCUSSION TITLE
Is it possible for Active Tab to have a different font colour?

### DISCUSSION THREAD

**Discussion by Vindickator** [piroor/treestyletab#3167] [Q&A] [answered]
Hello,

I'm trying to set the active tab's font colour to blue/white for readability..
![image](https://user-images.githubusercontent.com/87226625/183827084-cabd2562-d840-4e44-af6c-3a6c573054a6.png)

<details>
 <summary>Code snippet</summary>

```CSS


/* Highlight active tab */
tab-item.active tab-item-substance{
  /* height: 40px !important; */
  height: 40px !important;
  /* background-color: #193B99; */
  /* background-color: rgba(169,54,218,0.84); */
  background-color: rgb(177,23,23);
}



tab-item.active .label-content {
  font-size: 13px;
  /*font-color: rgb(0,255,38);*/
  font-weight: bold;
}

tab-item.active tab-twisty,
tab-item.active .label-content,
tab-item.active tab-counter {
  color: #000000;
}
```
</details>

I'm not a coder all though I have tried out font-color text-color too without successful results
Could you please help me get white font for active tabs in TST;
Thanks
