### DISCUSSION TITLE
Disable the extra space for the scrollbar (How to restore old behavior?)

### DISCUSSION THREAD

**Discussion by D3SOX** [piroor/treestyletab#3199] [Q&A] [answered]
I don't like the new behavior where it tries to make space for the scrollbar

3.8
![image](https://user-images.githubusercontent.com/24937357/190414934-b95d8aef-41cb-425c-afcf-a199f36ce925.png)

3.9

https://user-images.githubusercontent.com/24937357/190416072-3d3b3922-40fa-4309-876c-d4323bc4cb65.mp4

Is there any way to disable it?

My current extra style rules
```css
/* Custom scrollbar colors */ 
#tabbar {
  border: 0;
  scrollbar-color: auto;
}

/* Change styling of pending (unloaded) tabs */
tab-item.discarded tab-item-substance {
  opacity: 0.75;
}
/* https://github.com/serverwentdown/matched/blob/master/dark-firefox/manifest.json#L21 */
tab-item:not(.discarded) tab-item-substance > * {
  color: rgb(195, 195, 195);
}
```
