### DISCUSSION TITLE
Vertical bar on the right. What is it and how do I get rid of it?

### DISCUSSION THREAD

**Discussion by QuantumKuba** [piroor/treestyletab#3326] [Q&A] [answered]
Hi, does anyone know this annoying bar on the right hand side of TST is called. If anyone knows that this could be and how to possibly get sid of it, any hints would be appriciated.

**Not hovered**

![image](https://user-images.githubusercontent.com/47721520/234777078-b7977448-c21c-4549-ae53-b996ffcfa7b9.png)

**Gone when hovered**

![image](https://user-images.githubusercontent.com/47721520/234777203-bd9b1ee1-efe7-47c9-a278-8bba9e3ff4dc.png)

**Comment by QuantumKuba** [comment, marked as answer]
For anyone wondering. I found out the answer! 
This element is called a slitter and the author already had a solution for this in place. 

I've added the code below to my userChrome.css and the issue is solved.

```css
/* Hide splitter, when using Tree Style Tab. */
#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"] + #sidebar-splitter {
    display: none !important;
}
```
