### DISCUSSION TITLE
[Bug][Wiki Customization Snippets] v4.0.1 - Tab Numbering and Counting CSS broken.

### DISCUSSION THREAD

**Discussion by TFWol** [piroor/treestyletab#3472] [Q&A] [answered]
Since the update, CSS for [Tab Numbering and Counting](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#tab-numbering-and-counting) is janky.

The variables dealing with counting tabs is different. I think it's only counting what's seen in the view port.

**From Wiki**
```css
#tabbar {
  counter-reset: vtabs atabs tabs;
  /* vtabs tracks visible tabs, atabs tracks active tabs, tabs tracks all tabs */
}
tab-item:not(.collapsed):not(.discarded) {
  counter-increment: vtabs atabs tabs;
}
tab-item:not(.collapsed) {
  counter-increment: vtabs tabs;
}
tab-item:not(.discarded) {
  counter-increment: atabs tabs;
}
tab-item {
  counter-increment: tabs;
}
```

Are the variables the only thing that needs to change?
