### DISCUSSION TITLE
[Bug][Wiki Customization Snippets] v4.0.1 - "Put 'new tab' button at the top of the tab bar" CSS breakage

### DISCUSSION THREAD

**Discussion by TFWol** [piroor/treestyletab#3473] [Q&A] [answered]
Pinned tabs won't show properly (especially when you have more than one row) if putting 'New Tab' at the top using [Put "new tab" button at the top of the tab bar](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#put-new-tab-button-at-the-top-of-the-tab-bar-1376) from wiki.

**From Wiki**
```css
:root {
  --newtab-button-size: 20px;
}
.newtab-button-box {
  border-bottom: 1px solid var(--tab-border);
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  height: var(--newtab-button-size);
}
#tabbar {
  top: calc(var(--newtab-button-size) + 1px) !important;
  bottom: 0 !important;
}
tab-item.pinned {
  margin-top: calc(var(--newtab-button-size) + 1px) !important;
}
```
I tried messing with some of the numbers, but I'm not familiar with what needs to be tweaked. Any easy changes?
