### DISCUSSION TITLE
Autohide expands behind window content

### DISCUSSION THREAD

**Discussion by ned-martin** [piroor/treestyletab#3649] [Q&A] [answered]
## Abstract
TST is set to autohide. When mouse hover it should expand over the top of the window, but it is now expanding behind the window content.

## Steps to reproduce

 1. Upgrade Firefox to 133.0b2 when TST is set to auto-hide and expand on hover. This works on previous versions of Firefox.

## Actual result

TST auto-hidden
![image](https://github.com/user-attachments/assets/53c38f4a-a42d-4100-8d85-4cc50656702a)

TST with mouse hover - now expanded *behind* the window content
![image](https://github.com/user-attachments/assets/86f8a252-5021-40eb-9f9d-2d3fd4129393)

How it should work
 
<img width="185" alt="2024-11-01_16-44-04" src="https://github.com/user-attachments/assets/073c2db5-1c8c-41eb-bc7b-5742534e95ea">

## Environment

 * Platform (OS): Windows 11
 * Version of Firefox: 133.0b2 
 * Version (or revision) of Tree Style Tab: 4.0.23

**Comment by piroor** [comment]
Autohide is not a feature of TST, it is a userChrome.css customization topic. Thus I move this from issues to discussions.

**Comment by lediur** [comment, marked as answer]
I fixed this issue by increasing the `z-index` in `#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"]:hover` to 3 in my `userChrome.css` styles for the sidebar on hover.

```css
#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"]:hover,
#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"]
  #sidebar {
  min-width: var(--sidebar-visible-width) !important;
  max-width: var(--sidebar-visible-width) !important;
  transition-delay: 0s;
  transition-duration: 0.15s;
  z-index: 3;
}
```

### More info

I ran into this issue with 133.0b3 (Firefox Developer Edition).

I noticed that the sidebar displayed over the browser viewport when it was animating, but then was covered by the viewport when it finished animating.

After using the browser developer tools to inspect the user chrome styling, I noticed that the z-index for the browser `<tabbox>` element (`#tabbrowser-tabbox`) is now set to 2 in `var(--browser-area-z-index-tabbox)`. No idea what the value was in prior Firefox versions :shrug: 

This explained the behavior I observed, since [the example userChrome.css styles](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#auto-showhide-sidebar-by-mouseover-hover) set a higher z-index for the non-`:hover`-state sidebar than the `:hover`-state, so the z-index would remain at the higher value until the transition animation was complete.

Increasing the z-index for the hovered state above `var(--browser-area-z-index-tabbox)` fixed this issue for me.

Edit: I edited the example in the Wiki to fix this issue.

**Reply by ned-martin** [reply]
Thanks, that fixed it!

I note that in the Wiki the two examples differ - the "Full Auto-show/hide Theme" has different CSS to the "Auto-show/hide sidebar by mouseover (hover)" 

The "Full Auto-show/hide Theme" contains this, which (theoretically) protects against this problem occurring again. Perhaps both sections should be updated to be the same for simplicity?

```css
#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"] {
    ...
    z-index: calc(var(--browser-area-z-index-tabbox, 10000) + 1) !important;
}
```
