### DISCUSSION TITLE
Weird gap on side of sidebar?

### DISCUSSION THREAD

**Discussion by asyncmeow** [piroor/treestyletab#3699] [Q&A]
Hello!
I'm using Tree Style Tabs v4.1.1 on Firefox v134.0 (on MacOS, but not sure if that part is relevant). Recently, my tab sidebar got an extra gap on it, like this: 
![CleanShot 2025-01-12 at 00 17 14](https://github.com/user-attachments/assets/e449a553-ce10-4a55-ae62-eca659f95742)

Here's what my (fairly minimal) TST CSS looks like: 
```css
:root {
    --theme-colors-toolbar_bottom_separator: hsl(240, 5%, 30%); 
    overflow-y: scroll !important;
}

tab-item {
  --tab-size: 25px !important;
  height: var(--tab-size);
}
```

And my `userchrome.css`:
```css
/* Hide horizontal tabs at the top of the window */
#tabbrowser-tabs {
    visibility: collapse !important;
}

#titlebar {
    appearance: none !important;
    height: 0px;
}

#titlebar > #toolbar-menubar {
    margin-top: 0px;
}

#TabsToolbar {
    min-width: 0 !important;
    min-height: 0 !important;
}

#TabsToolbar > .titlebar-buttonbox-container {
    display: block;
    position: absolute;
    top: 12px;
    left: 0px;
}

#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"] #sidebar-header {
    display: none;
}

#nav-bar toolbarspring {
    min-width: 20px !important;
    max-width: 40px !important;
}

#main-window[privatebrowsingmode] #nav-bar { background: hsl(275, 100%, 10%) !important; }
```

What would be the best way to fix this?
