### DISCUSSION TITLE
How to match TST mute icon style with browser tab icon style?

### DISCUSSION THREAD

**Discussion by scarf005** [piroor/treestyletab#3710] [Q&A] [answered]
| browser | TST |
| - | - |
| <img width="48" alt="image" src="https://github.com/user-attachments/assets/61e43ba9-86a7-46e0-b23b-480f9bc5463d" /> | <img width="34" alt="image" src="https://github.com/user-attachments/assets/c69ade84-ff52-48bd-88d2-ae1d4da7fe1a" /> |

i searched for "icon" in TST configuration but couldn't find one.

my current config: [configs-treestyletab@piro.sakura.ne.jp.json](https://github.com/user-attachments/files/18839843/configs-treestyletab%40piro.sakura.ne.jp.json)

related: #3708

**Comment by piroor** [comment, marked as answer]
TST's mute icon refers colors of tab text. I recommend you to override definitions of those colors, like following:

```css
tab-sound-button {
    --tab-text-inverted: black; /* you can specify arbitrary CSS colors including color codes */
    --tab-text: white; /* you can specify arbitrary CSS colors including color codes */
}
```

By the way, TST imitates the icon style of Firefox 135. If you are using Firefox ESR128, you'll see matched appearance after the next ESR update.
