### DISCUSSION TITLE
fadeOutPendingTabs change title color to gray and keep icon

### DISCUSSION THREAD

**Discussion by Tragen** [piroor/treestyletab#3734] [Q&A]
The new option fadeOutPendingTabs in TST is great.
I would like to change it a bit.
I would like to keep the icons colored but have the title with gray text instead of white. How can I change this with CSS?
Thanks.

**Comment by Tragen** [comment]
I think I have it working for me.

```
tab-item.discarded tab-label
{
    color: gray;
}

tab-item.discarded .favicon-image
{
  opacity: 0.9 !important;
  filter: grayscale(10%) !important;
}
```

**Reply by milroneth** [reply]
That seems like a nice idea! I wanted the effect to be subtle (and have a purple background, not gray) so I adjusted this to the following which works great for me, but thank you for finding the classes.

```css
tab-item.discarded tab-label
{
    color: lightgray;
}

tab-item.discarded .favicon-image
{
  filter: grayscale(20%);
}
```
