### DISCUSSION TITLE
Hiding Sidebar Panel Title

### DISCUSSION THREAD

**Discussion by arpena** [piroor/treestyletab#3762] [General]
After updating to Firefox 140.0, with native vertical tabs enabled, the sidebar got its ugly title again. 
![image](https://github.com/user-attachments/assets/18fcca7b-248d-454a-9f28-cbff124d7201)

None of the [proposed customizations of userChrome.css](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#for-userchromecss) hides it. I've found that the new sidebar is called sidebar-panel, so the following snippet in userChrome.css does the trick:

`#sidebar-panel-header { display: none !important; }`

Could someone add it to the wiki?

**Comment by piroor** [comment]
~Now the header is a part of a sidebar panel, not a part of the browser window itself. How about putting the code to the `userContent.css`?~

After some trial this  works for me with the `userChrome.css` (not `userContent.css`).

```css
*|sidebar-panel-header {
  display: none !important;
}
```

**Reply by dsl101** [reply]
Not sure if this is just FF changes, but now the correct CSS for hiding the whole thing appears to be:

```css
#sidebar-header {
  display: none !important;
}
```

**Comment by PeterJCLaw** [comment]
Any ideas how to make this only hide for TST?

**Reply by tcbbd** [reply]
It's not possible to use the CSS property trick to pass info from `<sidebar-box>` to `<html:sidebar-panel-header>`, because we must pass the `<browser>` boundary, whose encapsulation is much stronger than shadow DOM.

A workaround would be like this:
```css
/* The baseline: At least you can hide extension titles alone, and keep things such as bookmarks shown */
#webextpanels-window #sidebar-panel-header {
  display: none;
}

/* The workaround: This is a hack, XYZ is a number dependent on your machine and configuration */
#webextpanels-window #sidebar-panel-header:has(+ #webext-panels-stack > #webext-panels-browser[initialBrowsingContextGroupId="XYZ"]) {
  display: none;
}
```

To get the `"XYZ"`, you need to inspect the browser itself and check the Group ID of `<browser>` element. It seems each extension has a unique ID, and it persists after browser restart.

I would say this hack is not elegant, so my choice is to add auto show/hide logic to the title:
```css
/* - Auto show/hide the header of webext sidebar panel */
#webextpanels-window #sidebar-panel-header {
  /**
   * Height = 21px + 4 * var(--space-large)
   * Reserve a small strip to show the header on hover
   */
  --sidebar-content-separator-color: color-mix(in srgb, currentColor 10%, transparent);
  --sidebar-header-hide-margin: calc((21px + 4 * var(--space-large) - var(--space-xsmall)) * -1);
  transition: all 0.3s;
  z-index: 1;

  /**
   * Avoid the initial transition caused by shadow DOM style propagation delay:
   * - The padding of #sidebar-panel-header is 0 upon sidebar panel creation.
   * - It then becomes var(--space-large) when the `:host` style from shadow DOM
   *   is applied to #sidebar-panel-header.
   * - This will be treated as a transition and be animated, which is not desired.
   */
  padding-block: var(--space-large);

  /**
   * Actually, each element has a default invisible outline. It becomes visible
   * in transition though. So it's necessary to explicitly set width to zero.
   */
  outline: 0px none;

  margin-block-start: var(--sidebar-header-hide-margin) !important;
  margin-block-end: 0;

  &:hover {
    background-color: -moz-dialog;
    outline: 0.01px solid var(--sidebar-content-separator-color);
    margin-block-start: calc(var(--space-large) * -1) !important;
    margin-block-end: calc(var(--sidebar-header-hide-margin) + var(--space-large));
  }
}
```

@piroor Should we add this to the wiki? Since the old sidebar will be removed this year.
