### ISSUE TITLE
Disable text shadow

### ISSUE THREAD

**Issue by toogy** [piroor/treestyletab#1102]
I recently switched to a light theme and the sidebar is unreadable because of the text shadow.
Is there a way to fix this?

![deepinscreenshot20160403123421](https://cloud.githubusercontent.com/assets/694873/14232001/209ae7e2-f999-11e5-922f-b632fd9ea97f.png)

**Comment by toogy** [comment]
I fixed it myself adding a `chrome/userChrome.css` to my `.mozilla/firefox/<profile>/` folder.

```css
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul"); /* set default namespace to XUL */

.treestyletab-tabbar-toolbar {
    opacity: 1.0 !important;
}
.tabbrowser-tabs[treestyletab-mode="vertical"] {
    opacity: 1.0 !important;
}
.tabbrowser-tabs[treestyletab-mode="vertical"] .tabbrowser-tab {
    opacity: 1.0 !important;
    text-shadow: 0px 0px 0px white !important;
}
```
