### ISSUE TITLE
Work in FF 53+ and improvments

### ISSUE THREAD

**Issue by vitaliylag** [piroor/treestyletab#1250]
1. In FF 53+ there's some css problems, this code can fix it:

```css
.tabbrowser-tab {
	line-height: 22px !important;;
}

.tab-label-container {
	position: relative !important;
}
```

2. I think many people would like to have an option to make pinned tabs bigger:

```css
.tabbrowser-tab[pinned] {
	width: 48px !important;
	height: 48px !important;
	max-width: 48px !important;
	max-height: 48px !important;
}

[pinned] > .tab-text.tab-label,   [pinned] > .tab-label-container {
	display: none;
}
```
