### ISSUE TITLE
Change the styling of unloaded (pending) tabs

### ISSUE THREAD

**Issue by Keith94** [piroor/treestyletab#1363]
Is it possible to change the css for unloaded tabs yet? For example change opacity, etc..

**Comment by piroor** [comment]
By recent commits, now discarded tabs have "discarded" class. So user-defined style rule like following will work as expected:

```css
.tab.discarded { opacity: 0.75; }
```

**Comment by piroor** [comment]
This is also filed at the code snippets:
https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules

**Comment by kkot** [comment]
@piroor Could you tell me how to make only icon more opaque ?

**Comment by vn971** [comment]
Great to see it working!
I think it's important enough to be built-in.

**Comment by Ainoss** [comment]
Unfortunately, it doesn't work for me after upgrading to 57.0.2 (or this is just coincidence). 
User-defined style rule as @piroor posted above does nothing.
Is it a known problem, or just for me? It will be great if anybody could give solution.

**Comment by vn971** [comment]
@Ainoss overriding font somewhy stopped working for me (I override with   `color: red;`), but opacity works. I'm on ArchLinux, FF version 57.0.2.

**Comment by encukou** [comment]
works with:
```
.tab.discarded .label {
  color: red;
}
```

**Comment by Ainoss** [comment]
@encukou Thank for your suggestion! It works fine (win10).

**Comment by alreadydone** [comment]
Unable to make this work (on Windows 10, FF60.0b12) with any of the above approaches ... any ideas? Not really familiar with CSS, but "Hide the 'Tree Style Tab' header" and "Hide horizontal tabs at the top of the window" from https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#for-userchromecss were successful.

**Comment by piroor** [comment]
@alreadydone You need to put custom CSS rules to an input field in TST's configuration page, instead of your userChrome.css file.

**Comment by alreadydone** [comment]
It works. Thanks!

**Comment by gnomesley** [comment]
This seems to be broken in the latest version (2.4.19) with FF 60.

**Comment by piroor** [comment]
@gnomesley Please add one more extra CSS rule:

```css

.tab .label-content {
  color: inherit;
}
```

I'll include this as a builtin rule at the next release of TST. Sorry.

**Comment by gnomesley** [comment]
Thanks for the response!

**Comment by bb010g** [comment]
`userChrome.css` equivalent to the wiki TST snippet:

```css
/* Change styling of pending (unloaded) tabs */
.tabbrowser-tab[pending="true"] {
  opacity: 0.75;
}
.tabbrowser-tab[pending="true"] .tab-label-container {
  color: red;
}
```

Only favicon:

```css
/* Change styling of the favicon of pending (unloaded) tabs */
.tabbrowser-tab[pending="true"] .tab-icon-image {
  opacity: 0.5;
}
```
