### ISSUE TITLE
Change position of new tab button

### ISSUE THREAD

**Issue by Keith94** [piroor/treestyletab#1376]
I was wondering if there's a CSS trick or separate option to control the position of the new tab button (i.e. top or bottom of sidebar, after last tab only, or disabled etc.)

**Comment by piroor** [comment]
I think you can do these customization via user defined CSS. For example:

> top or bottom of sidebar

```css
#all-tabs { order: 1000; }
```

or

```css
.newtab-button-box {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  height: 20px;
}
#tabbar {
  top: 20px !important;
}
.tab.pinned {
  margin-top: 20px;
}
```

> after last tab only

```css
#tabbar.overflow .after-tabs {
  display: block;
}
#tabbar.overflow ~ .after-tabs {
  display: none;
}
```
