### ISSUE TITLE
Add option to display close button at the right while scrollbar is on the right

### ISSUE THREAD

**Issue by Smile4ever** [piroor/treestyletab#1387]
## Short description
I would like to have my scrollbar on the right in the WebExtensions version.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open a lot of tabs

## Expected result
The scrollbar appears on the right side, and the close buttons too

## Actual result
The scrollbar appears on the right side, and the close buttons on the left

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 58 2017-09-27
 * Version (or revision) of Tree Style Tab: 2.0

**Comment by piroor** [comment]
How about this?:

```css
:root.right .tab .twisty {
  order: -1;
}
:root.right .tab .closebox {
  order: 10000;
}
```

**Comment by Nephyrin** [comment]
+1 for this -- I was able to get the desired behavior for left-justified-sidebar-on-the-right-of-the-screen by setting appearance to 'left-side' with custom style:

```css
* { direction: ltr !important; }
```
(No clue what actual selector I wanted to override here, but it miraculously breaks nothing)
