### ISSUE TITLE
Hide big "Tree Style Tab" title in firefox-nightly

### ISSUE THREAD

**Issue by tgy** [piroor/treestyletab#1397]
Is there a way to hide the huge "Tree Style Tab" at the top of the component?

![deepinscreenshot_select-area_20170930112654](https://user-images.githubusercontent.com/694873/31044588-723aa8f8-a5d2-11e7-9607-06c483c2729f.png)

## Environment

 * Platform (OS): `Linux stewie 4.12.13-1-ARCH #1 SMP PREEMPT Fri Sep 15 06:36:43 UTC 2017 x86_64 GNU/Linux`
 * Version of Firefox: `Mozilla Firefox 58.0a1`
 * Version (or revision) of Tree Style Tab: `Tree Style Tab 2.0.1`

**Comment by Keith94** [comment]
Add the following to [userChrome.css](http://kb.mozillazine.org/index.php?title=UserChrome.css) to hide TST's header

```css
#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"] #sidebar-header {
  display: none;
}

**Comment by tgy** [comment]
Thank you @Keith94, that worked perfectly! 👍

**Comment by oerms** [comment]
I am sorry to bring this up again. This does not seem to work for me. I have created a userchrome.css with the following:

`@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");

#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"] #sidebar-header {
    display: none;
}`

but the huge selector is still there.
I am running:
Firefox 57.0 (64-Bit)
TST 2.2.3

Thank you for supporting TST with web extensions!

**Comment by tgy** [comment]
@oerms with `Mozilla Firefox 59.0a1`, it still works on my side.

Here is the exact content of my `/home/<user>/.mozilla/firefox/<profile>/chrome/userChrome.css`:

```css
@namespace url("http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul");

.treestyletab-tabbar-toolbar {
    opacity: 1.0 !important;
}

.tabbrowser-tabs[treestyletab-mode="vertical"] {
    opacity: 1.0 !important;
}

.tabbrowser-tabs[treestyletab-mode="vertical"] .tabbrowser-tab {
    opacity: 1.0 !important;
    text-shadow: 0px 0px 0px white !important;
    margin-top:    -2px !important;
    margin-bottom: -2px !important;
}

#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"] #sidebar-header {
  display: none;
}
```
