### ISSUE TITLE
[feature request] Add customisable background color for group-tab.html

### ISSUE THREAD

**Issue by chzesa** [piroor/treestyletab#1494]
## Short description
The background color of dummy tabs (group-tab.html) cannot be easily changed from the blinding white. A color picker would be appreciated, or have group-tab.html respect --tabbar-bg css variable.

## Environment
 * Version (or revision) of Tree Style Tab: 2.0.7.5527

**Comment by piroor** [comment]
Sorry I forgot to set default BG color for the page. Now it has `ThreeDFace` system color background.

Currently I have no idea to implement color picker for dummy tabs, but you can change its background color via `userContent.css` (not `userChrome.css`) like:

```css
@-moz-document regexp("moz-extension://.+/resources/group-tab.html.*") {
  :root {
    background: red !important;
  }
}
```
