### ISSUE TITLE
Scrollbar overlapping the fold/unfold indicator/button

### ISSUE THREAD

**Issue by dikti** [piroor/treestyletab#1504]
## Short description
When scrolling the tab bar (positioned to the left), a scrollbar appears. Problem is, this scrollbar overlaps the collapse buttons, so you can't use them until the scrollbar fades again:

<img width="213" alt="bildschirmfoto 2017-11-02 um 07 51 56" src="https://user-images.githubusercontent.com/16717303/32313836-0d2721e8-bfa5-11e7-89e2-ee05b0417ed1.png">

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Scroll the tab bar
 4. Try to collapse a subtree

## Expected result
The subtree opens/collapses

## Actual result
Nothing happens, as one clicks on the scrollbar

## Environment

 * Platform (OS): macOS 10.13
 * Version of Firefox: 57.0b10
 * Version (or revision) of Tree Style Tab: 2.0.7, left side, Vertigo theme

**Comment by SXZ1** [comment]
Try latest beta:
https://piro.sakura.ne.jp/xul/xpi/nightly/treestyletab-we.xpi
It looks like this bug has already been fixed.

**Comment by piroor** [comment]
This doesn't happen on my environment. Is this a platform specific problem?

**Comment by sumyungguy** [comment]
This is not a bug. It's expected behavior in macOS. @SXZ1 , nothing has changed in the nightly.

When using "show scroll bars: when scrolling" setting in System Preferences, scroll bars appear only when scrolling. It's normal that they appear over window content. They may temporarily prevent access to window content at the edge, until they disappear again after 1/2 second or so.

Alternatives include not using auto-hiding scroll bars:
- use "show scroll bars: always" in System Preferences
- or to affect only Firefox this terminal command:
`defaults write org.mozilla.firefox AppleShowScrollBars -string Always`
- or this GUI application to adjust settings per application:
http://rants.tempura.org/2011/08/01/Per%E2%80%94App-Scrollbars-for-OS-X-Lion.html

Or make adjustments in "Extra style rules for sidebar contents" in TST preferences, for example:
- make extra space on left side:
```css
:root.left .tab .twisty { margin-left: 10px; }
```
- put scroll bar on right side, auto-hiding closebox on left, some other cosmetic changes, adjust to your liking:
```css
/* scroll bar on right */
:root.left #tabbar { 
  direction: ltr; 
}

/* adjust order and spacing */
:root.left .tab .twisty {
  order: 0;
}
:root.left .tab .closebox {
  order: 10;
  padding: 9px;
}
:root.left .tab .favicon {
  order: 20;
  padding-left: 4px;
  padding-right: 20px;
}
:root.left .tab .label {
  order: 30;
  font-size: 1.1em;
}

/* display closebox only on hover */
.tab:not(:hover) .closebox {
  display: none;
}

/* get rid of empty space for twisty on tabs that don't have children */
.tab:not([data-child-ids]) .twisty,
.tab.pinned .twisty {
  visibility:collapse !important;
  pointer-events: none !important;
}
```
- see [code snippets](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules) in the wiki for more ideas.
