### ISSUE TITLE
In Mixed skin on OSX, close tab button is tiny

### ISSUE THREAD

**Issue by gotyaoi** [piroor/treestyletab#1564]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Set skin to "Mixed"
 4. Observe tab close button size

## Expected result

larger close buttons

## Actual result

Very small, difficult to click on close buttons

Here's the tree vs the default tab bar.

![tree](https://i.imgur.com/PyT6GoT.png)
![default](https://i.imgur.com/ljqqqCD.png)

## Environment

 * Platform (OS): OSX 10.12.6
 * Version of Firefox: 57.0
 * Version (or revision) of Tree Style Tab: 2.2.9

I was able to work around this by using the custom CSS and setting font-size on .closebox. Not sure if this is something that would be best to be integrated into the base CSS for mixed. I also made the tabs thinner (my preference), and added some on-hover background color, so it behaved a bit more like the old version. My CSS is not the best, but this is what I came up with. This works acceptably on windows 10 as well.

```css
.tab {
  padding-top: 0em;
  padding-bottom: 0em;
}
.closebox {
  font-size: 1.2em;
  border-radius: 10px;
  height: 1.2em;
}
.closebox::before {
  display: block;
  margin-top: -.35em;
}
.closebox:hover {
  background: #c8c8c8;
}
.active .closebox:hover {
  background: #96afc8;
}
```
