### ISSUE TITLE
Trouble setting custom font via css

### ISSUE THREAD

**Issue by AndydeCleyre** [piroor/treestyletab#1580]
## Short description

I'm trying to specify the font used for the tabs, but it just changes from sans to serif, probably because it can't find the font, just like FF itself when similarly attempted in `userChrome.css`. But in that case I can get around it by using `@font-face`.

## Steps to reproduce

First, this works for the nav/url bar in `userChrome.css`, so here's that in its entirety:

```css
@font-face {
  font-family: 'Iosevka';
  src: url('/usr/share/fonts/TTF/iosevka-custom-regular.ttf')  format('truetype')
}
#TabsToolbar { visibility: collapse; }
#nav-bar {
  background: #262C2E !important;
  border-top: #262C2E !important;
}
* { font-family: Iosevka !important; }
```

Here's the custom css field in TST preferences:

```css
@font-face {
  font-family: 'Iosevka';
  src: url('/usr/share/fonts/TTF/iosevka-custom-regular.ttf')  format('truetype')
}

.tab.unread .label { color: darkorange !important; }
.tab.discarded { opacity: 0.93; }
:root { --tab-height: 30px !important; }  
.tab:not(.pinned) { height: var(--tab-height) !important; }
:root.left #tabbar { direction: ltr; }
.tab.private-browsing .label:before { content: "🕶"; }
.tab { font-family: Iosevka !important; }
```

## Environment

 * Platform (OS): Arch Linux
 * Version of Firefox: 57
 * Version (or revision) of Tree Style Tab: 2.2.9

**Comment by piroor** [comment]
Could you see the Debug console for Tree Style Tab from about:debugging, any security error? I think such a local file access can be blocked by Firefox.

**Comment by AndydeCleyre** [comment]
Ah, thanks, maybe I can copy or symlink the font into the extension directory. It says:

```
downloadable font: download failed (font-family: "Iosevka" style:normal weight:normal stretch:normal src index:0): status=2152857618 source: moz-extension://22ae34d3-971f-4158-bfc0-d5777a16bf63/usr/share/fonts/TTF/iosevka-custom-regular.ttf
```

OK, so I changed the `@font-face` path to `/iosevka-custom-regular.ttf` and ran:

```bash
ln -s /usr/share/fonts/TTF/iosevka-custom-regular.ttf <ff-profile>/browser-extension-data/treestyletab@piro.sakura.ne.jp/
```

But that doesn't work, same error, just shorter path. Is there a particular directory that corresponds to `moz-extension://22ae34d3-971f-4158-bfc0-d5777a16bf63/`?

**Comment by piroor** [comment]
Sadly there is no way to know actual unique URL in static CSS codes - maybe due to a security reason. We need to use JavaScript code to resolve it like:
https://github.com/piroor/treestyletab/blob/398ee71291dd7c5d385d973e1b603c6d65eb6131/webextensions/common/tree/constants.js#L223

I think I should introduce something placeholder like `font-face: url("%LOCAL_DATA%/iosevka-custom-regular.ttf")` in future versions.

**Comment by piroor** [comment]
We should do something like `.replace(/%LOCAL_DATA%/gi, actualURL)` here:
https://github.com/piroor/treestyletab/blob/81fa73e0128f4831fd1a6d453d1b5d653adabd88/webextensions/sidebar/sidebar.js#L261-L263

**Comment by AndydeCleyre** [comment]
Can `userChrome.css` be used to change that tabs' font somehow, when using TST?

**Comment by piroor** [comment]
`userChrome.css` doesn't affect to addon's sidebar. Instead you need to use `userContent.css` like:

```css
@-moz-document regexp("moz-extension://.+/sidebar/sidebar.html") {
 .tab .label {
   font-weight: bold !important;
 }
}
```
