### ISSUE TITLE
[feature request] FF57 - Custom themeing

### ISSUE THREAD

**Issue by Sioma112233** [piroor/treestyletab#1585]
## Short description
I was wondering if custom themes could be added to TST (a css file that can be imported from the addon setting's page with some template or example

**Comment by piroor** [comment]
Sorry, I have no plan to make the feature more rich...

**Comment by piroor** [comment]
Ah, but you can use `userContent.css` as a workaround. If you put codes like following, they are applied to TST's sidebar:

```css
@-moz-document regexp("moz-extension://.+/sidebar/sidebar.html") {
 .tab .label {
   font-weight: bold !important;
 }
}
```
