### ISSUE TITLE
Add ColorfulTabs feature to new Tree Style Tab WebExtension

### ISSUE THREAD

**Issue by MurzNN** [piroor/treestyletab#1645]
Firefox have very useful [ColorfulTabs](https://addons.mozilla.org/ru/firefox/addon/colorfultabs/) extension that colorize tabs per domain. It works well with XUL version of Tree Style Tab extension, but new Tree Style Tab WebExtension implement his own tab bar, that cannot be styled via other addons.

So will be good to add in new Tree Style Tab WebExtension same build-in feature for colorize tabs in per-domain basis. What do you think about this?

**Comment by piroor** [comment]
Sorry I won't implement it as a built-in feature of TST. Instead I recommend you to create new addon which can work with TST. TST now provides some APIs to register stylesheet to the sidebar from other addons, and tabs in the sidebar have an attribute `data-current-uri`. So, if you [register something generated style rules](https://github.com/piroor/treestyletab/wiki/API-for-other-addons#register-and-unregister-your-addon-to-tst) like following, it will work like the legacy ColorfulTabs:

```css
.tab[data-current-uri^="https://www.google.com/"] { background: green; }
.tab[data-current-uri^="https://www.mozilla.com/"] { background: red; }
```
