### ISSUE TITLE
Can't change color of New Tab Button

### ISSUE THREAD

**Issue by Lej77** [piroor/treestyletab#1664]
## Short description
Simulate SVG content fill doesn't work correctly for the new tab button. It always has its initial color.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Change TST Theme to "Plain Dark"

## Expected result
The new tab button should have a white '+' sign.

## Actual result
The new tab button have a black '+' sign.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 57
 * Version (or revision) of Tree Style Tab: 2.4.0

**Comment by Lej77** [comment]
The problem seems to come from the file ["webextensions/sidebar/styles/base.css" at line 466](https://github.com/piroor/treestyletab/blob/master/webextensions/sidebar/styles/base.css#L466).
It makes the '+' sign in the class `.newtab-button::after` when it probably should be `.newtab-button::before`.

It seems that the following CSS can be used as a workaround:
```CSS
/* TST 2.4.0 - HotFix for New Tab button's simulate-svg-context-fill */
:root.simulate-svg-context-fill .newtab-button::before {
  display: none;
}

:root.simulate-svg-context-fill .newtab-button::after {
  content: "";
  display: inline-block;
  height: var(--svg-small-icon-size);
  opacity: var(--button-opacity);
  width: var(--svg-small-icon-size);
}
:root.simulate-svg-context-fill .newtab-button:hover::after {
  opacity: var(--button-hover-opacity);
}
```
