### ISSUE TITLE
Sidebar loading throbber has white background when moving tab to new window

### ISSUE THREAD

**Issue by Lej77** [piroor/treestyletab#1665]
## Short description
A tab that is dropped outside of the sidebar is moved to a new window. When this happens the sidebar is grayed out and a loading throbber is shown in the middle of the sidebar. Currently there is an area around it in the shape of a square that has a white background color.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Drag a tab from the sidebar and drop it outside the window.

## Expected result
The sidebar should be grayed out and a throbber without background should be shown.

## Actual result
The sidebar is grayed out and a throbber with a white background is shown.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 57
 * Version (or revision) of Tree Style Tab: 2.4.0

**Comment by Lej77** [comment]
The following CSS code seems to make the white box transparent:
```CSS
/* HotFix for #1665 - Fix for not transparent throbber when moving Tab to New Window */
#blocking-screen .throbber::before {
  background-color: transparent !important;
}
```
