### ISSUE TITLE
userChrome.css tweaks suggestion

### ISSUE THREAD

**Issue by wheybags** [piroor/treestyletab#1672]
at https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#for-userchromecss you suggest some css to hide the normal top tab bar, but you get some messed up overlaying of the normal window management buttons on windows:

![image](https://user-images.githubusercontent.com/1093274/33861547-35e868ee-ded6-11e7-8cc7-a5d182775abd.png)

 I've been using 
```css
opacity: 0;
pointer-events: none;
```

Which works much better:
![image](https://user-images.githubusercontent.com/1093274/33861567-516dcfdc-ded6-11e7-9d22-8e0d72f8b078.png)

The topbar essentially returns to behaving like a normal windows window border.

**Comment by piroor** [comment]
Could you update the wiki by yourself? I'm not use these style rules, so I hope that the page is maintained by users.

**Comment by Lej77** [comment]
@wheybags Nice! I made the following userChrome.css file with your css code:

```CSS
#main-window[tabsintitlebar="true"]:not([extradragspace="true"]) #TabsToolbar {
  opacity: 0;
  pointer-events: none;
}
#main-window:not([tabsintitlebar="true"]) #TabsToolbar {
    visibility: collapse !important;
}
```

It uses your CSS code when title bar isn't shown and the `visibility: collapse !important;` code when the title bar is shown. Also it allows showing the tabs again by using the "extra space" option on the customization page.

**Comment by Lej77** [comment]
I improved the tab hiding when opening the window's menu alternatives with the alt key:
```CSS
@-moz-document url("chrome://browser/content/browser.xul") {
  /* Make tab area transparent when title is not shown */
  #main-window[tabsintitlebar="true"]:not([extradragspace="true"]) #TabsToolbar {
    opacity: 0;
    pointer-events: none;
  }
  
  /* Improve Alt-window-menu when title is not shown */
  #main-window[tabsintitlebar="true"]:not([extradragspace="true"]) #toolbar-menubar:not([inactive="true"]) ~ #TabsToolbar {
    visibility: collapse !important;
  }  
  #main-window[tabsintitlebar="true"]:not([extradragspace="true"]) #titlebar-buttonbox {
    height: 33px !important;
  }
  #main-window[tabsintitlebar="true"]:not([extradragspace="true"]) #toolbar-menubar {
    padding: 4px !important;
  }
  
  /* Hide tab area when title is shown */
  #main-window:not([tabsintitlebar="true"]) #TabsToolbar {
    visibility: collapse !important;
  }  
}
```

**Comment by Lej77** [comment]
I made another CSS code that shows the window title without the title bar.
```CSS
@-moz-document url("chrome://browser/content/browser.xul") {
  /* Make tab area transparent when native titlebar is not shown */
  #main-window[tabsintitlebar="true"]:not([extradragspace="true"]) #TabsToolbar {
    opacity: 0 !important;
    pointer-events: none !important;
  }
  
  /* Hide tab area when native titlebar is shown */
  #main-window:not([tabsintitlebar="true"]) #TabsToolbar {
    visibility: collapse !important;
  }
  

  /* Show title in tab area when native titlebar is not shown */
  :root {
    --customized-firefox-title-margin-top: 15px;
    --customized-firefox-title-margin-top-extra-fullscreen: 7px;
    --customized-firefox-title-margin-left: 10px;
    --customized-firefox-title-font-size: 1.1em;
    
    --customized-firefox-title-line-height: 30px;
    --customized-firefox-title-buttons-width: 150px;
  }
  
  #main-window[tabsintitlebar="true"]:not([extradragspace="true"])::before {
    display: block !important;
    pointer-events: none !important;
    max-height: 0px !important;
    
    color: var(--titlebar-text-color) !important;
    content: attr(title) !important;
    
    line-height: var(--customized-firefox-title-line-height) !important;
    --customized-firefox-title-margin-top-total: calc(-1 * (var(--customized-firefox-title-line-height) * 0.5) + var(--customized-firefox-title-margin-top));
    --customized-firefox-title-margin-bottom-total: calc(-1 * (var(--customized-firefox-title-line-height) + var(--customized-firefox-title-margin-top-total)));
    
    margin-top: var(--customized-firefox-title-margin-top-total) !important;
    margin-bottom: var(--customized-firefox-title-margin-bottom-total) !important;
    
    margin-left: var(--customized-firefox-title-margin-left) !important;
    margin-right: var(--customized-firefox-title-buttons-width) !important;
    
    font-size: var(--customized-firefox-title-font-size) !important;
  }
  #main-window[tabsintitlebar="true"]:not([extradragspace="true"]):-moz-window-inactive::before {
    opacity: 0.65 !important;
  }
  #main-window[tabsintitlebar="true"][sizemode="maximized"]:not([extradragspace="true"])::before {
    margin-top: calc(var(--customized-firefox-title-margin-top-total) + var(--customized-firefox-title-margin-top-extra-fullscreen)) !important;
    margin-bottom: calc(var(--customized-firefox-title-margin-bottom-total) - var(--customized-firefox-title-margin-top-extra-fullscreen)) !important;
  }
  #main-window[tabsintitlebar="true"]:not([extradragspace="true"]) #toolbar-menubar:-moz-any([autohide="false"] ,:not([inactive="true"])) ~ #TabsToolbar {
    visibility: collapse !important;
  }  
  #main-window[tabsintitlebar="true"]:not([extradragspace="true"]) #titlebar-buttonbox {
    height: 33px !important;
  }
  #main-window[tabsintitlebar="true"]:not([extradragspace="true"]) #toolbar-menubar:-moz-any([autohide="false"] ,:not([inactive="true"])) {
    padding-top: 30px !important;
    transition: none !important;
  }
}
```
