### ISSUE TITLE
How to get rid of X on tabs please?

### ISSUE THREAD

**Issue by ng4ever** [piroor/treestyletab#1684]
Sorry for all the questions.

**Comment by Lej77** [comment]
Add the following CSS code under the "Advanced" section in Tree Style Tab's option page in the "Extra style rules for sidebar contents" textbox.

To remove close button completely: 
```CSS
.closebox {
  display: none;
}
```

To hide close button (it still takes up space and can still be clicked on):
```CSS
.closebox {
  opacity: 0 !important;
}
```

To hide close button and allow clicks through it (it still takes up space but it can't be clicked on):
```CSS
.closebox {
  opacity: 0 !important;
  pointer-events: none;
}
```
