### ISSUE TITLE
Change the styling of pinned tabs

### ISSUE THREAD

**Issue by thomasrussellmurphy** [piroor/treestyletab#1704]
Similar to #1363, what are the CSS targets for modifying pinned tabs? In particular, height and favicon placement. This would be valuable to include in https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules, too.

I'd like to correct the styling I'm getting with inconsistent height and non-centered favicons on the pinned tabs.
![screenshot of pinned tab styling problems](https://i.imgur.com/qHugJYr.png)

## Environment

 * Platform (OS): macOS 10.12.6
 * Version of Firefox: 57.0.3
 * Version (or revision) of Tree Style Tab: 2.4.3

**Comment by Lej77** [comment]
Pinned tabs can be modified with rules for `.tab.faviconized` and their favicons with `.tab.faviconized .favicon`

However in most cases you should only need to override the following variables to change their sizes:
```CSS
:root {
  --favicon-size: 16px;
  --faviconized-tab-size: 28px;
}
```

--------------------

Helpful source files:
[treestyletab/webextensions/sidebar/sidebar.html](https://github.com/piroor/treestyletab/blob/master/webextensions/sidebar/sidebar.html)
[treestyletab/webextensions/sidebar/styles/base.css](https://github.com/piroor/treestyletab/blob/master/webextensions/sidebar/styles/base.css)
[treestyletab/webextensions/sidebar/styles/favicon.css](https://github.com/piroor/treestyletab/blob/master/webextensions/sidebar/styles/favicon.css)

**Comment by thomasrussellmurphy** [comment]
```javascript
.tab.faviconized {
  padding-left: 6px !important;
}
```

I think that the math `(var(--faviconized-tab-size) - var(--favicon-size))/2` would correctly auto-calculate the padding needed to center the favicon on the pinned tab, but using that in place of `6px` doesn't seem to work for me.

There's still some space between the pinned tabs and the other tabs, but I can live with that.

Also, it looks like the misplaced favicons were started by the older minimum-space custom style and my problems are fixed by using the current https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#leave-as-little-space-before-the-tab-name-as-possible

**Comment by Eisfunke** [comment]
I've used
```
:root {
    --faviconized-tab-size: 50px;
}

.tab.faviconized {
    --favicon-size: 30px;
}
```
to change the size of my faviconized tabs as @Lej77 suggested, but now the tabs overlap like this:

![screenshot_2018-02-01_21-38-40](https://user-images.githubusercontent.com/18213227/35702100-710ee7fa-0798-11e8-9379-428dc2bca1b9.png)

I can't figure out for the life of me how to fix it. `margin-left` e.g. only moves the whole tab block. Any tips?

**Comment by Lej77** [comment]
@Eisfunke Yes, faviconized pinned tabs position are controlled by JavaScript so its a bit harder to control their position. I commented with a workaround in [issue 1725](https://github.com/piroor/treestyletab/issues/1725#issuecomment-360499981). In short, simply add the following CSS code:
```CSS
:root {
  --faviconized-tab-size-script: calc(var(--faviconized-tab-size) / 1.75);
}
#dummy-favicon-size-box {
  min-height: var(--faviconized-tab-size-script);
  max-height: var(--faviconized-tab-size-script);
}
```
Note: any changes to the pinned tabs's size will be applied after the sidebar is closed and reopened.

**Comment by Eisfunke** [comment]
Thank you very much, @Lej77, that fixes the overlapping. Unfortunately, for some reason it also causes the normal tabs to have the same height as the faviconized tabs and the favicons to have varying sizes.
I was able to fix that by adding the following:
```css
.tab:not(.pinned) {
    max-height: 32px;
}

.tab:not(.pinned) .favicon {
    --favicon-size: 16px;
}
```

I also changed the divider to `1.74` to add a border around the tabs. (For some reason `+1` or similar things didn't work, it overlapped again)
