### ISSUE TITLE
White flash when loading sidebar

### ISSUE THREAD

**Issue by overdodactyl** [piroor/treestyletab#1714]
When the sidebar loads, the background color is a bright white (either when opening a new window, or toggling Tree Style Tabs open).

When opening the sidebar, the progression is as follows:

Complete white background --> White Background with a white "new tab button"  -->  dark background with loading dots -> custom styling + tabs

Here's a gif (sorry for the poor quality, I'm not sure why the streaking is showing up):

![white_flash](https://user-images.githubusercontent.com/33071129/34839104-6992ccb8-f6f8-11e7-94a4-25bc109b724a.gif)

Is there any way to change the background color used here?

I use 

```css
/* Remove white flash on load */
#sidebar, #sidebar-box {
    background: var(--primary-dark-color) !important;
}
```

to remove the white flash from FF's sidebar options (history, bookmarks, etc.), but couldn't figure anything out for TST.

Thanks!

## Environment

 * Platform (OS): macOS
 * Version of Firefox: 59
 * Version (or revision) of Tree Style Tab: 2.4.3

**Comment by piroor** [comment]
Because addon's sidebar panel is implemented by deeply nested inline frames, you need to apply background color for more elements:

```
<browser id="sidebar"> <= this is already applied
  #document at chrome://browser/content/webext-panels.xul?...
    <page id="webextpanels-window"> <= not applied yet
      <stack>
        <browser id="webext-panels-browser"> <= not applied yet
          #document at moz-extension://9071bd23-5e4b-4582-a58b-0ac99c1256b6/sidebar/sidebar.html?...
          ...
        </browser>
      </stack>
    </page>
</browser>
```

BTW, after recent changes now TST applies its custom background color to its sidebar panel ASAP. I think this change should reduce this flashing.

**Comment by overdodactyl** [comment]
Hi @piroor, thank you so much for the help and adjustments to TST, it's really appreciated!

I've added the additional elements from the nested inline frames and that seems to have effectively removed the initial white background seen before TST's white background + new tab button is seen.  

I think that alongside TST applying the background at an earlier stage should completely resolve the flashing.

Thanks again!

**Comment by overdodactyl** [comment]
Here are the relevant different frames from TST upon loading (the black is from the default dark theme available, then the dark grey is my custom styling):

![frames](https://user-images.githubusercontent.com/33071129/34893219-2aaa0ca0-f7d4-11e7-9895-9f070ee8482c.jpg)

Given the white is prior to *any* TST styling, I'm wondering if I have just missed another browser element and no longer anything caused by TST.


Currently using 

```css
/* Remove white flash on load */
#sidebar, 
#sidebar-box, 
#webextpanels-window, 
#webext-panels-browser {
    background: var(--primary-dark-color) !important;
} 
```
