### ISSUE TITLE
Close button instead favicon on hover

### ISSUE THREAD

**Issue by berliozz** [piroor/treestyletab#1788]
## Short description
I'm try to move close button to favicon place when mouse hover.
But when I do it, I see jumping label in tab. See GIF
![tst](https://user-images.githubusercontent.com/3850403/36151076-f68a7556-10d6-11e8-94f5-7011d3114d8c.gif)

When mouse pointer move over tab, favicon changed to close button and that fine. But label is jumping to right.

My question, how to fix it.

## My CSS:
`.tab:not(:hover) .closebox {`
` display: none;`
`}`

`.tab:hover .favicon {`
 ` display: none;`
`}`

`.tab:hover {`
`  background: #fafafa !important;`
`  opacity: 1;`
`}`

`:root.left .tab .closebox {`
`  order: -1;`
`}`

## Environment

 * macOS 10.13.3
 * Version of Firefox: 58.0.2 (64-bit) 
 * Version (or revision) of Tree Style Tab: 2.4.16

**Comment by piroor** [comment]
This works for me.

```css
.tab:not(:hover) .closebox,
.tab:hover .favicon {
  visibility: collapse;
}

:root.left .tab .closebox {
  margin-left: -3px;
  margin-right: -3px;
  order: -1;
}
```
