### ISSUE TITLE
hide tooltips in sidebar

### ISSUE THREAD

**Issue by ElhemEnohpi** [piroor/treestyletab#1806]
I've been using this, in userChrome.css, to hide tooltips for tab titles:
```css
#aHTMLTooltip {display: none !important}
```
But it's causing tooltips in other exensions not to show. How can I limit it just to the TST sidebar?
I tried:
```css
#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"] #aHTMLTooltip {
  display: none;
}
```

And I tried `.tooltip {display: none !important}` in the "extra css" box in TST prefs. Any ideas?
