### ISSUE TITLE
Feature Request: Example of removing child tab counter from tabs

### ISSUE THREAD

**Issue by derekbasch** [piroor/treestyletab#1868]
## Short description

An example of the CSS needed to remove or alter the child tab counter for parent tabs.

## Environment

 * Platform (OS): All
 * Version of Firefox: All
 * Version (or revision) of Tree Style Tab: All

**Comment by Lej77** [comment]
Here are some examples:

Hide but still take up space:
```CSS
.tab .counter {
  opacity: 0;
}
```

Hide and don't take up any space:
```CSS
.tab .counter {
  display: none;
}
```

Change color:
```CSS
.tab .counter {
  color: red;
}
```

Change prefix and suffix:
```CSS
.tab .counter::before {
  color: red;
  content: "/";
}
.tab .counter::after {
  content: unset;
}
```
