### ISSUE TITLE
Container identity indicator too small

### ISSUE THREAD

**Issue by mrwensveen** [piroor/treestyletab#1879]
The container identity indicator on the left (or right) side of the tab is hard to see (for me). I want to make this area slightly larger with extra style rules, but I can't find out how to do this properly.

I've come up with:
```
.tab *:nth-child(9) {
  width: 7px !important;
}
.tab {
  padding-right: 7px !important;
}
```
I've found nth-child(9) by experimenting, but a class name would be better. Also, it would be nice to only apply this to tabs that have a container. I've tried .tab[usercontextid] but that doesn't seem to work.

It would be even better for me to have the background-color of the whole tab set to the container's color, but that would probably require extra javascript.

**Comment by Fanolian** [comment]
The relevant codes start here:
https://github.com/piroor/treestyletab/blob/1087bd9a834ef24c6c7598da37684b25a2c469f8/webextensions/sidebar/styles/base.css#L424

I have changed it to:
````
:root.left .tab:not(.faviconized) .contextual-identity-marker { 
  width: calc(var(--favicon-size) / 2);
  left: 0;
}
````
which looks like this (the Instagram tab):
![image](https://user-images.githubusercontent.com/771216/39441498-c092f392-4ce0-11e8-9b55-5bce95e78841.png)

**Comment by Lej77** [comment]
To have the background-color of the whole tab set to the container's color you can use the following CSS code:
```CSS
.contextual-identity-marker {
  position: absolute !important;
  pointer-events: none;
  z-index: 0;
  
  bottom: 0 !important;
  left: 0 !important;
  right: 0 !important;
  top: 0 !important;
  
  width: unset !important;
  height: unset !important;  
    
  opacity: 0.5;
}
```
The opacity change is optional.
