### ISSUE TITLE
Question: how do I reduce or remove this shadow?

### ISSUE THREAD

**Issue by aesthicc** [piroor/treestyletab#1886]
![1](https://user-images.githubusercontent.com/32882701/40008401-1d0ce400-5797-11e8-9c57-2c7b3dc9ed64.png)

## Environment

 * Platform (OS): macOS
 * Version of Firefox: 60
 * Version (or revision) of Tree Style Tab: latest

Thanks.

**Comment by piroor** [comment]
You should apply CSS rules like:

```css
.tab .label.overflow {
  mask-image: linear-gradient(to left, transparent 0, black 5px);
}
:root.rtl .tab .label.overflow {
  mask-image: linear-gradient(to right, transparent 0, black 5px);
}
```

The last part `5px` is the length of the gradient. Default value is `2em`, and `0` means "no gradient".
