### ISSUE TITLE
New tab icons in the sidebar not matching the icons in Firefox's native tab bar

### ISSUE THREAD

**Issue by Lej77** [piroor/treestyletab#1893]
## Short description
The favicons for new tabs in the sidebar doesn't match the ones used by Firefox in the native tab bar. Also while the favicons used in the sidebar for new tabs is the default favicon it doesn't change color as the default favicon does. This means that if Tree Style Tab uses the `Plain Dark` Theme then the new tab icons are all black which makes them really hard to see.

The following CSS from [the wiki](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#pre-photon-no-favicon-tab-icon-1822) can be used to make the sidebar favicons match the ones in the native tab bar:
```css
/* TST 2.4.17 - Fix for #1822 - Fix for Photon themed new tab favicon */
#tabbar .tab:not(.loading) .favicon .favicon-image[src^="moz-extension://"][src$="/resources/icons/globe-16.svg"] {
  display: none;
}
#tabbar .tab:not(.loading) .favicon .favicon-image[src^="moz-extension://"][src$="/resources/icons/globe-16.svg"] ~ .favicon-default::before {
  display: inline-block !important;

  background: url("chrome://branding/content/icon32.png") no-repeat center / 100% !important;
  mask: none !important;
}
#tabbar .tab:not(.loading)[data-current-uri="about:privatebrowsing"] .favicon .favicon-image[src^="moz-extension://"][src$="/resources/icons/globe-16.svg"] ~ .favicon-default::before {
  background: url("chrome://browser/skin/privatebrowsing/favicon.svg") no-repeat center / 100% !important;
}
```

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open TST option page and change to the `Plain Dark` theme.
 4. Open a tab with the default favicon. For example by opening the `about:debugging#addons` URL.
 5. Open a new tab with the `about:newtab` or `about:home` URL.
 6. Open a new private window and a tab in it with the `about:privatebrowsing` URL.

## Expected result
The tabs in the sidebar should all have the same icons as in the native tab bar and if not then they should at least all be the same color.

## Actual result
The tab with the default favicon (URL: `about:debugging#addons`) has a white icon. The other tabs have the same icon but in black which makes them hard to see. The tabs with the black icons all have a different icon in Firefox's native tab bar.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 60.0
 * Version (or revision) of Tree Style Tab: 2.4.21
