### ISSUE TITLE
Hiding tab bar prevents me from dragging title bar on Linux

### ISSUE THREAD

**Issue by tcbbd** [piroor/treestyletab#1894]
With Client Side Decoration enabled on linux (i.e. tabs in title bar), if I use the following snippet (as suggested in wiki) to hide the tabs, I can't move the window by dragging it.
```css
#main-window[tabsintitlebar="true"]:not([extradragspace="true"]) #TabsToolbar {
  opacity: 0;
  pointer-events: none;
}
#main-window:not([tabsintitlebar="true"]) #TabsToolbar {
    visibility: collapse !important;
}
```

Maybe we should disable pointer events for the parent of #TabsToolbar instead of #TabsToolbar? After some exploration I get this working snippet
```css
#main-window[tabsintitlebar="true"]:not([extradragspace="true"]) #navigator-toolbox {
  pointer-events: none;
}
#main-window[tabsintitlebar="true"]:not([extradragspace="true"]) #navigator-toolbox > :not(#TabsToolbar) {
  pointer-events: auto;
}
#main-window[tabsintitlebar="true"]:not([extradragspace="true"]) #TabsToolbar {
  opacity: 0;
  pointer-events: none;
}
```
Not familiar with CSS tricks, any ideas on improving this or some more elegant solution?

OS: Ubuntu 16.04
DE: GNOME 3.18
Firefox version: 60.0
