### ISSUE TITLE
Option to auto-hide vertical scrollbar

### ISSUE THREAD

**Issue by hethhhhh** [piroor/treestyletab#1923]
Can you please add an option or CSS so that the vertical scrollbar auto-hides (and show it on mouse scroll for example)

Thank you.

**Comment by Keith94** [comment]
```css
#tabbar.overflow {
  margin-right: -16px;
  transition: margin-right 0s 1s;
}
#tabbar:hover {
  margin-right: 0px;
  transition: margin-right 0s 4s;
}
```

**Comment by hethhhhh** [comment]
That's great, but the transitions doesn't work :(

**Comment by piroor** [comment]
How about this?

```css
:root.left-scrollbar.narrow-scrollbar #tabbar.overflow {
  margin-left: calc(0px - var(--scrollbar-size));
  transition: margin-left ease 0.25s 0.4s;
}
:root.right-scrollbar.narrow-scrollbar #tabbar.overflow {
  margin-right: calc(0px - var(--scrollbar-size));
  transition: margin-right ease 0.25s 0.4s;
}

:root.left-scrollbar.narrow-scrollbar #tabbar.overflow:hover {
  margin-left: calc(var(--narrow-scrollbar-size) - var(--scrollbar-size));
}
:root.right-scrollbar.narrow-scrollbar #tabbar.overflow:hover {
  margin-right: calc(var(--narrow-scrollbar-size) - var(--scrollbar-size));
}
```

**Comment by hethhhhh** [comment]
this one doesn't hide it at all

**Comment by piroor** [comment]
How it broken? It works on my environment as expected so I cannot imagine how I should "fix" it. Could you attach screenshots?

**Comment by hethhhhh** [comment]
I cleaned up some code in the Extra style rules and now it works! Probably something left over like a bracket.
Thanks a lot!

**Comment by nh2** [comment]
For me `margin-` no longer works.

This works for me, replacing all `margin-` bits by nothing:

```css
:root.left-scrollbar #tabbar.overflow {
  left: calc(0px - var(--scrollbar-size));
  transition: left ease 0.25s 0.4s;
}
:root.right-scrollbar #tabbar.overflow {
  right: calc(0px - var(--scrollbar-size));
  transition: right ease 0.25s 0.4s;
}

:root.left-scrollbar #tabbar.overflow:hover {
  left: 0;
}
:root.right-scrollbar #tabbar.overflow:hover {
  right: 0;
}

:root.left-scrollbar.narrow-scrollbar #tabbar.overflow:hover {
  left: calc(var(--narrow-scrollbar-size) - var(--scrollbar-size));
}
:root.right-scrollbar.narrow-scrollbar #tabbar.overflow:hover {
  right: calc(var(--narrow-scrollbar-size) - var(--scrollbar-size));
}
```

**Comment by nh2** [comment]
My fix above now no longer works since the most recent update of TST or Firefox; it now makes tab labels invisible: https://github.com/piroor/treestyletab/issues/2200#issuecomment-479239371

**Comment by nh2** [comment]
It looks like the automatic calculation of the offset using `var(--scrollbar-size)` no longer works.

I've made it work hardcoding some pixels (including only the case where the scrollbar is on the left, as I couldn't make it work with the snippet that puts the bar on the right):

```css
/* Auto hide scrollbar */

:root.left-scrollbar #tabbar.overflow {
  left: -5px; /* calc(0px - var(--scrollbar-size)); */
  transition: left ease 0.25s 0.4s;
}

:root.left-scrollbar #tabbar.overflow:hover {
  margin-left: 0;
}

:root.left-scrollbar.narrow-scrollbar #tabbar.overflow:hover {
  left: 0px; /* calc(var(--narrow-scrollbar-size) - var(--scrollbar-size)); */
}
```
