### ISSUE TITLE
Would you like a new dark theme?

### ISSUE THREAD

**Issue by MBach** [piroor/treestyletab#1941]
## Short description

I would like to contribute with a new built-in theme.

## Expected result

A new theme can be selected in options.

## Motivation

The dark theme seems, for me, a little too dark. So I've started to design my own dark theme using the textarea in the settings.

Here's what I've done so far:

![extra_dark_theme](https://user-images.githubusercontent.com/1532657/41252411-56cafb0a-6dbd-11e8-91d6-2602782d7b2e.png)

I know, 40px height might be overkill for tab height, but it's OK on my 4k monitor :D

You can find the source below:

```css
#tabbar {
  background-color: #5E5E60;
  border-color: #5E5E60;
}
.tab {
  height: 40px;
  color: #DDDDDD;
  border-left: 3px solid #5E5E60;
  padding-right: 20px;
}
.tab.active:hover,
.tab.active {
  background-color: rgba(50,50,52,1.0);
  border-left: 3px solid #0A84FF;
}
.tab:not(.pinned) {
  padding-left: 0px !important;
}

/* HOVER */
.tab:hover {
  background: rgba(50,50,52,0.7) !important;
  border-left: 3px solid rgb(50,50,50,0.0);
}

/* NEW TAB BUTTON */
#tabbar:not(.overflow) .after-tabs {
  display: block;
  height: 40px;
}
#tabbar:not(.overflow) ~ .after-tabs {
  display: block;
}
.closebox {
  position: absolute;
  right: 4px;
  padding: 2px;
}
.closebox::after {
  content: "🞩";
  font-size: 16px;
  background: none;
  line-height: 1.25rem;
  mask: none;
  text-align: center;
}
.closebox:hover {
  background: #707070;
  border-radius: 20px;
}
.tab .favicon {
  margin-right: 10px;
}
.newtab-button-box {
  position: relative;
  top: 4px;
  bottom: 0;
  left: 0;
  right: 0;
  height: 40px;
}

.newtab-button-box * { 
  border: 0px solid transparent;
}
.newtab-button::after {
  content: '+';
  color: #bbb;
  border: 0px solid #888;
  padding-left: 6px;
  padding-right: 6px;
  padding-top: 2px;
  padding-bottom: 2px;
}
.newtab-button:hover::after {
  background-color: #666;
}
/* SOUND ICON */
.sound-button {
  margin-left: 8px;
  margin-right: 8px;
  background: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAABGdBTUEAALGPC/xhBQAAAAlwSFlzAAAOwgAADsIBFShKgAAAABl0RVh0U29mdHdhcmUAcGFpbnQubmV0IDQuMC4yMfEgaZUAAAEUSURBVDhP3dRNSsNAGMbxCBakUmwXpRTcm7P0HC48Qxduewl1Ucjk+6vBrZAbiAuvoBuhgrgp7fiMjCFNH0rSdiFd/Ek27y9DkhnDNM1tndi2fel53pWU0qgTQ4qCIBg6jvPkuu4rG2ZRSIWVdQE9AlyhTzbMolgcxz1gAtASSSHEfqDv+2NAC4WpLMuqD6Zp2gnDsK8b4ANcl7HGIAZm6Fn3gr5RgakagXg/71Wg2v8H0ZGBbwSoVh/EjrjFwL0K91NcPzSyG5jneQv79kzXjqJohFWv/diNQLb1sNIbIF8HA9VqsQUngH4PBzxgP1AF9BToA8AFrnM2zKLYX/oYu8Ppk7FhFoXKZVl2niTJBRveTBo/BynzCObUd4cAAAAASUVORK5CYII=)
  no-repeat center left;
  background-size: 16px 16px;
}
.tab.sound-playing .sound-button {

  background: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAZdEVYdFNvZnR3YXJlAHBhaW50Lm5ldCA0LjAuMjHxIGmVAAACMUlEQVQ4T6WUu0tcQRSHr7oxal4rGEIwkIhF1v/BOkWKFIKVlRhIwFSJRYgkhY1EGwstFtQisO+3d5fNIogLgmARwhaChhBSrQQi6yMqiK7fCfde5l5HyaP4mDm/c+Y3587MrhEIBC6jIRKJ3IvH4w81OS1a0SaZTN6NRqNLsVhsXZfXoRUFOvNjVMDwFHY8+YZEIvEShqVOzalFDplMph2zMEYnUA+Hwy5DTBrJT5GrgYlxt51zilQoeEPhsZgJoVDI26ERDAZbOZJ+8ttssCbHI7qRy+VupFKp2xZ3uICnqpnXkPwTtKFiseiXTtn8GfEO+nviZoNgAT5bVOAAHDNBNaSTF2i7kC2VSlcrlUoTpmPEP+TTDc5ny154EaqhdIH2Fo44x5F6vS4XdJ94iy5H/9pQsC7tE7lVmbPJTeYfYeWPDOHcpdDNJPoXuusqFAqtjBG8vv+P4TT6Bt09EEPiKF7f/smQi+lE+wrLGF6Xz5Y5x7AohlVr0WWol+Knmxm0QxgUjbiHeU1egIHrO4I5gfkHxp9woSE1E5huy1Nh9JXL5Sto8qvalM4NEUi0WLSl0+nHdO162KohRr3UPZI3yCgP+zWGv+hylNjnnIsKBc8x2dcZ2uTz+Q5MXpGr0UAGsw7RXUU2JFsoHqf4958DG7gMq9WqD30R9uQI5FLsnFPkRdrHdJ5Fx4w1b55PHUDvkyNTdVeRF+sXMctiU5fXoRVVTNO8ls1mb+ly5wkYZwlXvzaKDfSUAAAAAElFTkSuQmCC)
  no-repeat center left;
  background-size: 16px 16px;
}

```

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 62
 * Version (or revision) of Tree Style Tab: latest

## Time to vote?

If some people find this theme attractive, maybe it could be move to the source folder of this wonderful plugin, and become a built-in theme.

Thank you for reading
