### ISSUE TITLE
New tab button styling

### ISSUE THREAD

**Issue by damat** [piroor/treestyletab#2016]
## Short description
I can't figure out a way to add custom style to the New tab button without breaking it. 

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Start styling the button with custom style:

.newtab-button-box { 
 
}
 
I need to make it:
 - taller 
 - move a bit away (down) from last tab
 - add cursor:pointer on hover
  
Padding results in unclickable zone. Double clicks works though, which makes it even more frustrating: 
https://dl.dropbox.com/s/gyk1sflwj2srjfg/shot_180830_205225.png 

Height adds gap with no clicking as well. Line-height and font-size are ignored with and without !important flag.

Cursor:pointer is another mystery. Hover pseudo-class works fine for the color, but ignores cursor:
https://dl.dropbox.com/s/4hg2pxkbt7v2alp/shot_180830_205627.png

## Environment

 * Platform (OS): 
 * Version of Firefox: 
 * Version (or revision) of Tree Style Tab:

**Comment by Lej77** [comment]
I think you can use the following code to style the new tab button:

 - taller
```css
.newtab-button {
  height: 40px;
}
```

- move a bit away (down) from last tab

```css
.after-tabs {
  margin-top: 20px;
}
#tabbar {
  margin-bottom: 20px;
}
```

- add cursor:pointer on hover

```css
.newtab-button {
  cursor: pointer;
}
```
 or

```css
.newtab-button-box * {
  cursor: pointer;
}
```
