### ISSUE TITLE
"Show title of unread tabs in italic" does not work

### ISSUE THREAD

**Issue by keisuke-nakata** [piroor/treestyletab#2084]
## Short description
I wanted to format unread tabs italic (and colorizing red), but currently it does not work at my environment.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Create `chrome` folder at my default profile dir and put `userChrome.css` file according to https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#show-title-of-unread-tabs-in-italic .
My css file looks like:
```css
/* Hide horizontal tabs at the top of the window */
/* https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#hide-horizontal-tabs-at-the-top-of-the-window-1349 */
#main-window[tabsintitlebar="true"]:not([extradragspace="true"]) #TabsToolbar {
  opacity: 0;
  pointer-events: none;
}
#main-window:not([tabsintitlebar="true"]) #TabsToolbar {
    visibility: collapse !important;
}

/* Show title of unread tabs in italic */
/* https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#show-title-of-unread-tabs-in-italic */
.tab.unread .label {
  color: red !important;
  font-style: italic !important;
}

/* Only show tab close button on hover */
/* https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#only-show-tab-close-button-on-hover-1448 */
.tab:not(:hover) .closebox {
  display: none;
}

/* Hide the "Tree Style Tab" header at the top of the sidebar */
/* https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#hide-the-tree-style-tab-header-at-the-top-of-the-sidebar */
#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"] #sidebar-header {
  display: none;
}
```
 4. Save the css file and restart Firefox, but "italic unread" and "close button on hover" feature do not work.
(However "hide horizontal firefox native tabs at the top of the window" and "hide 'tree style tab' header on the sidebar" work)

## Environment

 * Platform (OS): Windows 10 home
 * Version of Firefox: 63.0.3 (64bit) 
 * Version (or revision) of Tree Style Tab: 2.6.8

**Comment by Fanolian** [comment]
``` css
.tab.unread .label-content {
  font-style: italic;
  color: red;
}
```
From https://github.com/piroor/treestyletab/blob/2225d3f8be615fd5787f9cf28c0942914558340d/webextensions/sidebar/styles/base.css#L361-L364

I have updated the wiki.

**Comment by keisuke-nakata** [comment]
Thank you for response, but it does not work yet for me. 🤔
Now my userChrome.css is:
```css
#main-window[tabsintitlebar="true"]:not([extradragspace="true"]) #TabsToolbar {
  opacity: 0;
  pointer-events: none;
}
#main-window:not([tabsintitlebar="true"]) #TabsToolbar {
    visibility: collapse !important;
}

.tab.unread .label-content {
  color: red;
}

.tab:not(:hover) .closebox {
  display: none;
}

#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"] #sidebar-header {
  display: none;
}
```

I worked for specifying the problem while, but could not find solutions.
Any idea?

**Comment by keisuke-nakata** [comment]
Ahhh I got it!
I have updated the css file at my profile folder, but it must be configured in Tree-style-tab's own configuration section!
Now it works file, my TST config is:

```css
/* Show title of unread tabs with red and italic font */
.tab.unread .label-content {
  color: red !important;
  font-style: italic !important;
}
```

Thank you so much!
