### ISSUE TITLE
[CSS] How do I center the icons for Container Tab and "Open a New Tab as" after widening the buttons?

### ISSUE THREAD

**Issue by Fanolian** [piroor/treestyletab#2089]
## Short description
Disclaimer: I don't have much CSS knowledge. I just copy and edit the codes that I can find.

I would like to widen the "open a new tabs as…" and "new container tab" sub-buttons in the new tab button. The icons for them, however, are not always centered when I change the width of TST sidebar.
How do I make them so?
Thank you.
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Append these styles to "Extra style rules" section:
```css
/* Improve new tab buttons */
.after-tabs .newtab-action-selector-anchor,
.after-tabs .contextual-identities-selector-anchor {
  opacity: 0.5;  /* Always show Container and Tab Position icons */
  padding: 0em 25%; /* Widen the buttons; the buttons are not actually 25% wide... */
}

.newtab-action-selector-anchor::before {
  content: "🗍";
  transform: scaleX(-1.25);
  font-weight: bold;
  font-size: 1em;
  margin: 0em -2.5em;  /* Hack around to center the icon for my sidebar width */

}
.contextual-identities-selector-anchor::before{
  content: "▚";
  font-size: 1em;
  margin: 0em -2.5em; /* Hack around to center the icon for my sidebar width */
}
```
 4. Change the sidebar width and observe the positions of the sub-buttons.

## Expected result
None. The styles obviously do not center the icons but I don't know how to. 

## Actual result
Screenshot when the sidebar is very wide:
![image](https://user-images.githubusercontent.com/771216/49859151-c95d7d00-fe31-11e8-95c7-fb5d0b44e4dc.png)

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox:  Nightly 2018-12-11 (20181211213305)
 * Version (or revision) of Tree Style Tab:  2.6.8

## P.S.
I found the styles from https://github.com/piroor/treestyletab/blob/d49477cc224e81450ca3f4538eba8b4f004b6bb1/webextensions/sidebar/styles/base.css#L538-L553 and below.

**Comment by Lej77** [comment]
The following css code seems to work for me:
```css

.after-tabs .newtab-action-selector-anchor,
.after-tabs .contextual-identities-selector-anchor {
  /* Always show Container and Tab Position icons (customizable): */
  opacity: 0.5;
  
  /* Widen selectors (customizable): */
  width: 25% !important;
  max-width: unset !important;
  
  /* Center icons: */
  justify-content: center;
  align-items: center;
}

.newtab-action-selector-anchor::before,
.contextual-identities-selector-anchor::before {
  /* Change selector icon size (customizable): */
  font-size: 1em;
  
  /* Center icons: */
  padding-bottom: 0.35em;
}

/* Change selector icons: */
.newtab-action-selector-anchor::before {
  content: "🗍";
  transform: scaleX(-1.25);
  font-weight: bold;
}
.contextual-identities-selector-anchor::before{
  content: "▚";
}
```

It even works if you change the height of the new tab button with something like:
```css
.after-tabs .newtab-button {
  height: 30px;
}
```
