### ISSUE TITLE
Feature request: introduce an option to disable blue dot on pinned tabs with updated title

### ISSUE THREAD

**Issue by AndreyAkinshin** [piroor/treestyletab#2110]
![image](https://user-images.githubusercontent.com/2259237/50540556-10bf6980-0ba5-11e9-89d5-e8d4a4d5393e.png)

**Comment by Lej77** [comment]
The following css seems to work for me:
```css
.tab {
  --attention-marker-gradient: none;
  --attention-marker-gradient-hover: none;
}
```
