### ISSUE TITLE
Wrong favicon when configured to bigger size

### ISSUE THREAD

**Issue by ypconstante** [piroor/treestyletab#2156]
## Short description
When the favicons are customized to be shown in a non default size, like 32x32, the favicon image shown still is the 16x16 even when the site offer bigger icon sizes.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Add the CSS to change the favicon size
```css
:root {
    --favicon-size: 32px;
}
```
 4. Open GitHub and YouTube

## Expected result
Both icons to be shown in 32x32.

## Actual result
GitHub icon is shown as expected, since the only favicon available is 32x32.
But in YouTube, the icon is shown in 16x16. In the YouTube HTML there is multiple favicons declared, the default with 16x16, one for 32x32, and some larger sizes.

![screenshot from 2019-02-18 21-04-00](https://user-images.githubusercontent.com/8113764/52981809-01f17800-33da-11e9-89df-11efe33af684.png)

## Environment
  *  Platform (OS): Linux MInt
  *  Version of Firefox: 65.0
  *  Version (or revision) of Tree Style Tab: 2.7.18

**Comment by piroor** [comment]
I couldn't reproduce the problem on my environment: Firefox 65.0.1 and Nightly 67.01a on Ubuntu 16.04. Screenshot:
![image](https://user-images.githubusercontent.com/70062/52994118-e5952000-3459-11e9-843a-eeac586f14d2.png)
I think it may be a bug of Firefox itself or a platform specific issue.

**Comment by ypconstante** [comment]
This happened to me too, usually the 16px one is used, but sometimes the right favicon is used. 

![screenshot from 2019-02-19 08-26-53](https://user-images.githubusercontent.com/8113764/53011873-5b3cc400-3439-11e9-87aa-17000bd8011f.png)

Both tabs on the print are in the same page of chess.com, and only one of then is using the 48px icon. When they were reloaded, both icons became the 16px. When the tab with the right favicon was refreshed, it displayed the right favicon really quickly, but then it changed to the small favicon.

This is the config I'm using right now, maybe it's something caused  by the icon size changed only for the pinned tabs?
```css
/* pinned sites with bigger favicon */
:root {
	--faviconized-tab-size: 59px;
	--faviconized-tab-size-script: calc(var(--faviconized-tab-size) / 1.74);
}

#dummy-favicon-size-box {
	min-height: var(--faviconized-tab-size-script);
	max-height: var(--faviconized-tab-size-script);
}

.tab.pinned {
	--favicon-size: 48px;
}

.tab:not(.pinned) {
	--favicon-size: 16px;
}

/* pinned sites favicon centered */
.tab.pinned .favicon {
	display: flex;
	justify-content: center;
	align-items: center;
}
```

**Comment by piroor** [comment]
Hmm, after retrying multiple times the problem happened on my environment. And finally I've realized that it is hard to be fixed by TST side.

Basically TST just uses the URL of the favicon given via a single string property [`tabs.Tab.favIconUrl `](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/Tab) returned from the WebExtensions API. Its value is a `data:` URI instead of raw `https://` URL due to security reasons, and it is generated from Firefox's Places database. Firefox just stores one valid favicon for a page, and it looks determined by the module [FaviconLoader.jsm](https://searchfox.org/mozilla-central/source/browser/modules/FaviconLoader.jsm). The module is designed to choose a suitable icon for Firefox's native tab, so any extra choice won't be delivered to addons via the WebExtensions API.

Then there are two different ways we can go on:

A) Propose a new feature to provide multiple favicons to WebExtensions API.
B) Add a mechanism like the FaviconLoader.jsm to TST.
C) Create a new helper addon for TST.

The plan A is hard and uncertainty. We addon author can propose any extra idea for new WebExtensions API, but such ideas must be triaged and they may be rejected when the idea is judged as less effective or too complex, even if we write patches to implement that.

The plan B is possible and controllable, but it looks not good for me with some reasons. First, it requires `<all_urls>` permission just to extract favicon information from all webpages. Second, it will increases the size of TST itself because not only the loader module but something cacher module for favicon data also are required. Currently I have less motivation to maintain such huge mechanism just for non-default size favicons I never use.

The plan C is similar to B. Instead of adding such a module to TST itself, it may be done by a [helper addon working together with TST](https://github.com/piroor/treestyletab/blob/master/README.md#addons-that-extend-tst). When you are motivated enough, I recommend you to do this, because an OSS should be developed by people who really want to use it. If something new [API](https://github.com/piroor/treestyletab/wiki/API-for-other-addons) is required to inject custom favicon to TST's sidebar, I'll add that to TST.

How about the plan C?

**Comment by ypconstante** [comment]
Well, it's a lot of effort for changing the icon size. I'll try to understand how all the parts you mentioned work and interact before I try to do an addon to solve this.
For now, I'll stick with my ugly hack of forcing the favicon for YouTube.

```css
.tab.pinned[data-current-uri^="https://www.youtube.com"] .favicon-image {
	display: none !important;
}

.tab.pinned[data-current-uri^="https://www.youtube.com"] .favicon {
	background-size: 48px 48px;
	background-image: url('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAACX
```
