### ISSUE TITLE
Tab numbers disappearing since 3.x release

### ISSUE THREAD

**Issue by Decohero** [piroor/treestyletab#2220]
Tab numbers which were added to the "Extra style rules" stopped appearing following the 3.x releases in the last week.  They appear briefly as a tab is loaded, but then disappear less than a second later.

This behavior is reproducible with a new Firefox profile using the code snippet on the TST Wiki (included below).

This behavior was observed in each of the following environments:

Mac OS 10.13.6
Firefox 66.0.2
TST 3.0 - 3.0.5

Mac OS 10.11.6
Firefox 65.0.1
TST 3.0.5

Windows 7
Firefox 66.0.2
TST 3.0.5

Tab numbering code added to style rules:

```
#tabbar {
  counter-reset: vtabs atabs tabs;
  /* vtabs tracks visible tabs, atabs tracks active tabs, tabs tracks all tabs */
}
.tab:not(.collapsed):not(.discarded) {
  counter-increment: vtabs atabs tabs;
}
.tab:not(.collapsed) {
  counter-increment: vtabs tabs;
}
.tab:not(.discarded) {
  counter-increment: atabs tabs;
}
.tab {
  counter-increment: tabs;
}

.tab .burster::after {
  background: Highlight;
  color: HighlightText;
  content: counter(vtabs);
  font-size: x-small;
  right: 0.2em;
  padding: 0.2em;
  pointer-events: none;
  position: absolute;
  bottom: 0.2em;
}
```

**Comment by stapuft** [comment]
okay so thats where they went.

**Comment by irvinm** [comment]
I use this and haven't had any problem with 3.x:

/* --------------------------------------------------------------------- */
/* Add "Active Tabs / Total Tabs" on the new tab button area ----------- */
/* --------------------------------------------------------------------- */
#tabbar {
counter-reset: vtabs atabs tabs;
/* vtabs tracks visible tabs, atabs tracks active tabs, tabs tracks all tabs */
}
.tab:not(.collapsed):not(.discarded) {
counter-increment: vtabs atabs tabs;
}
.tab:not(.collapsed) {
counter-increment: vtabs tabs;
}
.tab:not(.discarded) {
counter-increment: atabs tabs;
}
.tab {
counter-increment: tabs;
}

.newtab-button::after {
content: var(--tab-count-text);
pointer-events: none;

position: absolute;
left: 0.5em;

/* TST 2.4.0 - Fix for Issue #1664 */
background: transparent !important;
mask: none !important;
}

.newtab-button {
--tab-count-text: counter(atabs) "/" counter(tabs) " tabs";
}
/* --------------------------------------------------------------------- */

**Comment by piroor** [comment]
I've confirmed that @irvinm's version looks working as expected.

**Comment by Lej77** [comment]
`.tab .burster` has `display: none` set in latest TST so using another element will fix the problem.

I looked at the available elements and `.tab .extra-items-container` looked the most promising (it covers the whole tab so easier to position), but it has [`z-index: 10`](https://github.com/piroor/treestyletab/blob/master/webextensions/sidebar/styles/base.css#L300-L302) which will place its content under other elements. This can look weird in for example pinned tabs. So the easiest solution seems to be using the `.tab` element directly. The `::before` pseudo-element is [used by drag and drop](https://github.com/piroor/treestyletab/search?l=CSS&q=%3A%3Abefore) so we can't use that but the `::after` pseudo-element [seems to be unused](https://github.com/piroor/treestyletab/search?l=CSS&q=%3A%3Aafter).

## Using `.tab::after` pseudo-element

```css
#tabbar {
  counter-reset: vtabs atabs tabs;
  /* vtabs tracks visible tabs, atabs tracks active tabs, tabs tracks all tabs */
}
.tab:not(.collapsed):not(.discarded) {
  counter-increment: vtabs atabs tabs;
}
.tab:not(.collapsed) {
  counter-increment: vtabs tabs;
}
.tab:not(.discarded) {
  counter-increment: atabs tabs;
}
.tab {
  counter-increment: tabs;
}

.tab::after {
  background: Highlight;
  color: HighlightText;
  content: counter(vtabs);
  font-size: x-small;
  right: 0.2em;
  padding: 0.2em;
  pointer-events: none;
  position: absolute;
  bottom: 0.2em;
}
```

## Using `.tab .extra-items-container::after` pseudo-element

```css
#tabbar {
  counter-reset: vtabs atabs tabs;
  /* vtabs tracks visible tabs, atabs tracks active tabs, tabs tracks all tabs */
}
.tab:not(.collapsed):not(.discarded) {
  counter-increment: vtabs atabs tabs;
}
.tab:not(.collapsed) {
  counter-increment: vtabs tabs;
}
.tab:not(.discarded) {
  counter-increment: atabs tabs;
}
.tab {
  counter-increment: tabs;
}

.tab .extra-items-container {
  z-index: unset !important;
}
.tab .extra-items-container::after {
  background: Highlight;
  color: HighlightText;
  content: counter(vtabs);
  font-size: x-small;
  right: 0.2em;
  padding: 0.2em;
  pointer-events: none;
  position: absolute;
  bottom: 0.2em;

  z-index: 100;
}
```

**Comment by Decohero** [comment]
Excellent, @Lej77's solution(s) work for me.

Thanks, and closing issue.

**Comment by stapuft** [comment]
Ok but the code in the beginning was for tab numbers on the individual tabs (so you don't have to can't them to see what number tab you are on for debug purposes and stuff) the other codes appear to be the code that places the tab count into the new tab button? Those are completely different sets of code, and keep track of tabs completely differently

**Comment by stapuft** [comment]
@Lej77 using either one of those codes
the numbers appear in the tabs, but they do not disappear?
the numbers even are on the pinned tabs...this is a completely different code, the original code disapeered when the mouse was not hovering over the tab. that code was much better.

**Comment by stapuft** [comment]
HEY! i figured it out by accident!!!
to match the behavior of the original code this is the string you need to use
@Lej77 @irvinm 

.tab:hover::after {
  background: Highlight;
  color: HighlightText;
  content: counter(vtabs);
  font-size: x-small;
  right: 0.2em;
  padding: 0.2em;
  pointer-events: none;
  position: absolute;
  bottom: 0.2em;

  z-index: 100;
}

**Comment by irvinm** [comment]
> 
> 
> @Lej77 using either one of those codes
> the numbers appear in the tabs, but they do not disappear?
> the numbers even are on the pinned tabs...this is a completely different code, the original code disapeered when the mouse was not hovering over the tab. that code was much better.
> 
> @irvinm thats not the code we are talking about man.
> 
> is there any way to make it appear only when hovered over, like the burster.after command used to allow?

@stapuft, sorry about that.  I thought the topic was "tab counter", not "tab numbering".  Totally different, sorry.

**Comment by stapuft** [comment]
ey it happens, besides they were very close, i didn't even recognize until i read through it a second time.

**Comment by Lej77** [comment]
I remembered that [Multiple Tab Handler](https://addons.mozilla.org/firefox/addon/multiple-tab-handler/) [injects some CSS code when it registers to Tree Style Tab](https://github.com/piroor/multipletab/blob/master/webextensions/background/background.js#L323-L347). That code will conflict with the suggestion that is implemented with `.tab::after` so that the tab numbering disappears from multi-selected tabs when Multiple Tab Handler is installed. Therefore I changed the [wiki](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#numbering-of-tabs-1601-2220) to use the implementation with `.tab .extra-items-container::after`. 

@stapuft It seems like you might have been using the code from the ["Tab numbering on hovered tabs" section in the wiki](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#tab-numbering-on-hovered-tabs). I updated that code in the wiki as well so you could use something like the following:

```css
#tabbar {
  counter-reset: vtabs atabs tabs;
  /* vtabs tracks visible tabs, atabs tracks active tabs, tabs tracks all tabs */
}
.tab:not(.collapsed):not(.discarded) {
  counter-increment: vtabs atabs tabs;
}
.tab:not(.collapsed) {
  counter-increment: vtabs tabs;
}
.tab:not(.discarded) {
  counter-increment: atabs tabs;
}
.tab {
  counter-increment: tabs;
}

.tab .extra-items-container {
  z-index: unset !important;
}
.tab .extra-items-container::after {
  background: Highlight;
  color: HighlightText;
  content: counter(vtabs);
  font-size: x-small;
  right: 0.2em;
  padding: 0.2em;
  pointer-events: none;
  position: absolute;
  bottom: 0.2em;

  z-index: 100;
}

.tab .extra-items-container::after {
  opacity: 0;
  transition: 0.2s;
}
.tab:hover .extra-items-container::after {
  opacity: 1;
}
```

**Comment by stapuft** [comment]
> 
> 
> I remembered that [Multiple Tab Handler](https://addons.mozilla.org/firefox/addon/multiple-tab-handler/) [injects some CSS code when it registers to Tree Style Tab](https://github.com/piroor/multipletab/blob/master/webextensions/background/background.js#L323-L347). That code will conflict with the suggestion that is implemented with `.tab::after` so that the tab numbering disappears from multi-selected tabs when Multiple Tab Handler is installed. Therefore I changed the [wiki](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#numbering-of-tabs-1601-2220) to use the implementation with `.tab .extra-items-container::after`.
> 
> @stapuft It seems like you might have been using the code from the ["Tab numbering on hovered tabs" section in the wiki](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#tab-numbering-on-hovered-tabs). I updated that code in the wiki as well so you could use something like the following:
> 
> ```css
> #tabbar {
>   counter-reset: vtabs atabs tabs;
>   /* vtabs tracks visible tabs, atabs tracks active tabs, tabs tracks all tabs */
> }
> .tab:not(.collapsed):not(.discarded) {
>   counter-increment: vtabs atabs tabs;
> }
> .tab:not(.collapsed) {
>   counter-increment: vtabs tabs;
> }
> .tab:not(.discarded) {
>   counter-increment: atabs tabs;
> }
> .tab {
>   counter-increment: tabs;
> }
> 
> .tab .extra-items-container {
>   z-index: unset !important;
> }
> .tab .extra-items-container::after {
>   background: Highlight;
>   color: HighlightText;
>   content: counter(vtabs);
>   font-size: x-small;
>   right: 0.2em;
>   padding: 0.2em;
>   pointer-events: none;
>   position: absolute;
>   bottom: 0.2em;
> 
>   z-index: 100;
> }
> 
> .tab .extra-items-container::after {
>   opacity: 0;
>   transition: 0.2s;
> }
> .tab:hover .extra-items-container::after {
>   opacity: 1;
> }
> ```

adding :hover to the ::after code you already shared works exactly like the old code did, but thank you man, im a newbie at this but im trying to learn what is the difference between the two codes? what makes one better than the other if they both do the same thing?

**Comment by Lej77** [comment]
@stapuft My code has the `transition` property which should make the transitions (hiding or showing tab numbers) more smooth. But if you wan't the transition to be instant then your code is probably better.

**Comment by stapuft** [comment]
@Lej77 oh ok i see that now, cool thank you, could i made the padding whole pixel numbers? i am using this
 
#tabbar.overflow { margin-right: -15px; }
#tabbar.overflow { margin-left: -8px; }

to hide my scrollbars, (the theme option to hide them is broken on my end) and because of that the tab numbers are cut off partally.

**Comment by Lej77** [comment]
## Positioning tab number

```css
.tab:hover::after {
  background: Highlight;
  color: HighlightText;
  content: counter(vtabs);
  font-size: x-small;
  right: 5pxm;
  padding: 0.2em;
  pointer-events: none;
  position: absolute;
  bottom: 0.2em;

  z-index: 100;
}
```

`5pxm` is incorrect (`pxm` isn't a valid unit) which makes Firefox ignore the `right` property. This is why the tab numbering is shown on the left side of the tab. You could remove that whole line and get the same result. To get better control of the position you could use `left: 5px;` instead of `right: 5pxm;` or you can use `right: 5px;` to do what you originally intended. 

### Fixed code

```css
.tab:hover::after {
  background: Highlight;
  color: HighlightText;
  content: counter(vtabs);
  font-size: x-small;
  right: 5px;
  padding: 0.2em;
  pointer-events: none;
  position: absolute;
  bottom: 0.2em;

  z-index: 100;
}
```

## Hidden tabs

```css
.tab.hidden:not(.collapsed):not(.pinned) {
  opacity: 0.5 !important;
  visibility: visible;
  position: static;
  pointer-events: auto;
}
```

The problems with hidden tabs is probably because of how you reveal them. If you use `position: relative;` instead of `position: static;` everything seems to work fine.

### Fixed code

```css
.tab.hidden:not(.collapsed):not(.pinned) {
  opacity: 0.5 !important;
  visibility: visible;
  position: relative;
  pointer-events: auto;
}
```
