### ISSUE TITLE
How do I change tab style for a tab with a given label?

### ISSUE THREAD

**Issue by rouilj** [piroor/treestyletab#2242]
## Short description
Unable to change tab style by using css to target label contents.

I have the following CSS added to the extra style rules for tree style tab:

/* mark tabs with matching titles with a different background color for easy identification */
/* use built in style for tbt sidebar */
.tab[data-label$="- Nagios"] {background-color: rgb(255, 255, 0)}
.tab[data-label^="Facebook"] {background-color: rgb(200, 0, 200)}

These stopped working at some point in past. Today I got around to debugging the issue.
I fired up the debugger and looked at the generated HTML. It looks like the only place the label
for a tab is shown is in the contents of a span tag. There are no attributes that have a value that matches the label for the tab.

## Expected result

Css rules that allows changing the color of the tab, the font for the label, color of the label
based on a css attribute match on the text of the label for the tab.

## Actual result
The old mechanism no longer works.

## Environment

 * Platform (OS): Windows 10, Linux Mint 14
 * Version of Firefox: 66.0.3
 * Version (or revision) of Tree Style Tab: 3.0.8

**Comment by piroor** [comment]
You should use `title` instead of `data-label` on TST 3.0.8. For example:

```css
.tab[title$="- Nagios"] {background-color: rgb(255, 255, 0)}
.tab[title^="Facebook"] {background-color: rgb(200, 0, 200)}
```

**Comment by irvinm** [comment]
@rouilj can you evaluate the solution and if that works, close out this issue?  Thanks.

**Comment by rouilj** [comment]
I tried your suggestion. It seems to be working sometimes. I have had it
work, then I exit/restart the browser and it doesn't work.
Also checking/unchecking the cache seems to make it work sometimes. I
haven't tried debugging the failing cases to see what the
title attribute is set to and why the css isn't matching.

-- rouilj

**Comment by piroor** [comment]
I'm very sorry, I forgot that the "title" attribute is not available when the label of the tab is short enough. After the commit 4674432 `data-title` attribute become available like as:

```css
.tab[data-title$="- Nagios"] {background-color: rgb(255, 255, 0)}
.tab[data-title^="Facebook"] {background-color: rgb(200, 0, 200)}
```
