### ISSUE TITLE
 Numbered tabs double entry

### ISSUE THREAD

**Issue by nollinvoyd** [piroor/treestyletab#2307]
Suddenly when i open my TST menu, I get double entries for numbered tabs

![tst](https://user-images.githubusercontent.com/20844322/59153388-0daa8e00-8a0d-11e9-9734-9f166a84fe03.png)

The only explanation I can think of is that I have a numbered tabs entry in my userchrome.css and, unlike before, it's now showing up in mt TST menu as well as on my regular tabs

If I remove the TST numbered tabs css, it looks like this

![tst2](https://user-images.githubusercontent.com/20844322/59153413-a6410e00-8a0d-11e9-962d-64ecb3a5ff6e.png)

I actually much prefer this larger number tabs display.  Much better visibility.  I also have it set up to reveal the close button on mouse hover as you can see.  But as you can also see, a wide blank area has been created to the left.

How can I removed that blank area?

This is my css as it was before I removed the numbered tabs css

```css
/* Add private browsing indicator per tab */
/*
.tab.private-browsing .label:before {
  content: "??";
}
*/

/* Less visible tab dividers. 
   A black border with a very low alpha slightly darkens any color. */
.tab {
  border: solid 1.0px #000000; 
}

/* As little space before the tab name as possible.
   The fold/unfold icon is not affected. */
.tab:not(.pinned) {
  padding-left: 0px !important; /* !important is required when there are enough tabs to cause a scrollbar */
}

/* Change styling of pending (unloaded) tabs */
.tab.discarded {
  opacity: 0.75;
}

.tab.discarded .label-content {
  color: blue;
}

/* Change tab height */
.tab {
  height: 25px;
}

/* Highlight active tab */
.tab.active {
  height: 39px !important;
  background-color: #ffff80;
}
.tab.active .label {
  font-weight: bold;
  font-size: 14px;
}
.tab.active .twisty,
.tab.active .label,
.tab.active .counter {
  color: red;
}

/* Hovered tab */
.tab:hover {
  background: #EBF10B !important;
  opacity: 1;
}

/* Background color or read tabs/* 
/* To change the background color of read tabs that are unfocused the following should work: */

.tab:not(.unread):not(.active) {
  background: #FFCC99;
}

/* Tab numbering and counting */

/* All of the options in this section need the raw count of tabs available. This is done using CSS counters: */

#tabbar {
  counter-reset: vtabs atabs tabs;
  /* vtabs tracks visible tabs, atabs tracks active tabs, tabs tracks all tabs */
}
.tab:not(.collapsed):not(.discarded) {
  counter-increment: vtabs atabs tabs;
}
.tab:not(.collapsed) {
  counter-increment: vtabs tabs;
}
.tab:not(.discarded) {
  counter-increment: atabs tabs;
}
.tab {
  counter-increment: tabs;
}

/* Numbering of tabs #1601, #2220 */
/*
    Note: this requires the counting CSS block listed here.

This displays the number of each visible tab along side each tab.
*/

.tab .extra-items-container {
  z-index: unset !important;
}
.tab .extra-items-container::after {
  background: Highlight;
  color: HighlightText;
  content: counter(vtabs);
  font-size: x-small;
  right: 0.2em;
  padding: 0.2em;
  pointer-events: none;
  position: absolute;
  bottom: 0.2em;

  z-index: 1000;
}

/* Tab numbering on hovered tabs */
/*
    Note: this requires the counting CSS block listed here and the label CSS block listed here.

To show tab numbering only on hovered tabs, use this CSS:
*/

.tab .extra-items-container::after {
  opacity: 0;
  transition: 0.2s;
}
.tab:hover .extra-items-container::after {
  opacity: 1;
}
/* Put closebox left side, even if I choose "Left side" style */
:root.left .tab .twisty {
  order: 10000;
}
:root.left .tab .closebox {
  order: -1;
}

/* Change close button style */
.closebox::after { content: "U+2716";

  background: none;
  line-height: 1;
  mask: none;
  text-align: center;
  width: 1.25em;
}

.tab:not(:hover) .closebox {
  display: none;
}
```

 * Platform (OS): Windows 10 Prp
 * Version of Firefox: 68.0b8
 * Version (or revision) of Tree Style Tab: 3.0.17
