### ISSUE TITLE
Throbber animation slowing page loads by up to 50%

### ISSUE THREAD

**Issue by m-thomson** [piroor/treestyletab#2328]
## Short description

I noticed that certain pages load about ~50% faster with the TST sidebar hidden. I was able to trace it back to the page loading throbber.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Compare load time of CNN.com (or a similarly bloated site) with and without TST sidebar visible.
4.  You should notice a significant difference (for me it was roughly 50%!)
5. Hide the throbber with the CSS below and re-try the experiment.

```
.throbber { display:none!important; }
```

## Expected result

Page load time should not be affected by TST.

## Actual result

Pages loaded considerably slower

## Environment

 * Platform (OS):  MacOS 10.14.5
 * Version of Firefox: 67.0.4 (64 bit)

## Other notes

* I have a feeling that the same animation is causing the initial rendering of the TST sidebar (for example when launching FF) to be much slower than necessary.

**Comment by m-thomson** [comment]
@piroor There are other throbber-related performance issues reported in the past which I'm sure you're aware of. They mention that the throbber uses a CSS animation

**Comment by m-thomson** [comment]
Related https://github.com/piroor/treestyletab/issues/1384

**Comment by piroor** [comment]
Sadly I have no more good idea to optimize CSS animations... It is beyond my technical skill.

**Comment by Lej77** [comment]
You could try to use the animation with 30 fps instead of 60 fps by applying the following css:
```css
:root:not(.throbber-synchronizing) .tab:not(.collapsed).loading:not(.throbber-unsynchronized) .throbber::before,
:root:not(.throbber-synchronizing).have-loading-tab #master-throbber,
:root.have-loading-tab #sync-throbber,
:root.blocking-throbber #blocking-screen .throbber::before {
  animation: throbber 1.05s steps(30) infinite;
}
```
Its the css from [line 52 in `webextensions/sidebar/styles/throbber.css`](https://github.com/piroor/treestyletab/blob/master/webextensions/sidebar/styles/throbber.css#L52) and I simply changed the `steps(60)` to `steps(30)`.

From some quick testing I didn't notice any slowdown when comparing loading [CNN.com](CNN.com) with and without Tree Style Tab's sidebar being open. 

Also Firefox's tab animation seems to be defined [here](https://hg.mozilla.org/mozilla-central/file/tip/browser/themes/shared/tabs.inc.css#l198) and seems similar to Tree Style Tab's animation. 

If the performance is still bad when the animation has a really low fps (such as `1`) then the issue might be with some Tree Style Tab code that handles the animation and not with the CSS animation itself.

**Comment by m-thomson** [comment]
Oops, I didn't mean to close this. I do have saved performance profiles from the sidebar both open and closed if that helps.

After I posted this issue, I lowered the steps way down to <10 and noticed a big improvement. 

I've no idea why it would only affect my (MacOS) system. Maybe something about my setup. I'll do some more investigating.

I'm curious though, would an APNG image be better? (It's like Gif but with alpha transparency) I've never worked with with them before but like it could save some cycles.

**Comment by piroor** [comment]
> I'm curious though, would an APNG image be better?

Because SVG throbber is required to apply the theme color to the throbber itself. Firefox itself also uses this method maybe due to same reason.

Anyway, I've inspired from the idea of @Lej77's comment and I've introduced a new custom property to define the animation steps of the throbber with the commit 72db584. After that you can override the animation steps simply like following:

```css
:root {
  --throbber-animation-steps: steps(10);
}
```

**Comment by Lej77** [comment]
After some thought the performance issue might be because of tricks we do to make the loading animations synchronized. The following CSS should disable the synchronization:

```css
/* Apply animation to unsyncronized throbbers */
:root:not(.throbber-synchronizing) .tab:not(.collapsed).loading .throbber::before {
  animation: throbber 1.05s steps(60) infinite !important;
}

/* Override the rules that use -moz-element to copy the appearance of the hidden global throbber */
:root:not(.simulate-svg-context-fill) #tabbar .tab:not(.collapsed).loading .throbber::before {
  -moz-context-properties: fill;
  background: url("/sidebar/styles/throbber.svg") no-repeat !important;
}
:root.simulate-svg-context-fill #tabbar .tab:not(.collapsed).loading .throbber::before {
  mask: url("/sidebar/styles/throbber.svg") no-repeat left center / 100% !important;
}

/* Disable hidden global throbbers since they aren't used anymore */
#sync-throbber,
#master-throbber {
  animation: none !important;
}
```
