### ISSUE TITLE
Feature request: colors for containers in Firefox

### ISSUE THREAD

**Issue by ajmeese7** [piroor/treestyletab#2346]
## Short description
This is different from the previous related issues because I'm not suggesting any fancy grouping methods or anything. I just think it would be nice if there could be a similar colored underline in the side tree to the one on the top nav bar.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Open a tab in a container in Firefox.

## Expected result
Colored underline in tree tab for contained tabs

## Actual result
![image](https://user-images.githubusercontent.com/17814535/62473415-50b38400-b766-11e9-8c65-0ef0ddfbda40.png)

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 69.0b6 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.1.5

**Comment by piroor** [comment]
I think it can be done with a custom style sheet like:

```css
.contextual-identity-marker {
  top: auto !important;
  left: 0.5em !important;
  right: 0.5em !important;
  bottom: 0 !important;
  width: auto !important;
  max-width: none !important;
  height: calc(var(--favicon-size) / 10) !important;
}
```
