### ISSUE TITLE
[feature request] Setting Color of acive Tab

### ISSUE THREAD

**Issue by Murmis** [piroor/treestyletab#2477]
feature request
## Short description
I use standard dark theme on FF (rel. 71.0) with TST. (rel. 3.2.5) When big amount  tabs open - is too difficult to navigate active tab in list. They all similar dark color.
It would be nice if possible to set color of active tab. 
 * Platform (OS): w10 x64

**Comment by piroor** [comment]
Please use the custom user stylesheet option under the "Advanced" section in TST's options page. For example:

```css
tab-item.active {
  background-color: red !important;
}
```
