### ISSUE TITLE
redirection causes error on tab status

### ISSUE THREAD

**Issue by NightSharp** [piroor/treestyletab#2534]
I think maybe I've found the reason that caused what I described in #2530 
I use some addon and TamperMonkey's scripts to redirect some urls.
After I discarded a tab redirected by them, these addon and scripts will automatically change the tab's url again ( and do not activate it of course).
And so TST treat the discaded tab as loaded and unread instead of discarded--what it really is.
I guess not only the redirection tools I used will cause the incorrect display for tab status, but also many other redirection operations.
After I closed these tools, the new opened tab affected by them can be discarded normally.
I hope this is the true reason for #2530  and it can be solved quickly

**Comment by piroor** [comment]
>  I use some addon and TamperMonkey's scripts to redirect some urls.

Which script do you use? After I read you explanation, I thought that the script actually loads the redirected URL. I hope to try it on my environment and investigate what happens.

**Comment by NightSharp** [comment]
> 
> 
> > I use some addon and TamperMonkey's scripts to redirect some urls.
> 
> Which script do you use? After I read you explanation, I thought that the script actually loads the redirected URL. I hope to try it on my environment and investigate what happens.

@piroor  In my case, after the tab was discarded and showed as "loaded and unread", I click the tab to switch on it and I can promise that the tab start loading after getting the focus, which means the redirection didn't load the tab before.
But If you need, I will show these addons and TamperMonkey's scripts below(maybe in my language)
addon:
gooreplacer [https://addons.mozilla.org/zh-CN/firefox/addon/gooreplacer/](url=)
It can redirect any urls through the rules you created. You can test it with any websites you like.

scripts(used for videos in [www.bilibili.com](url)):
[https://greasyfork.org/zh-CN/scripts/373563-bilibili-evolved](url)
this is a toolbox and one feature of it is to remove url's redundant parameters

[https://greasyfork.org/zh-CN/scripts/398536-bilibili-bv自动转换av](url)
changes video's url from new encoding (for example, [https://www.bilibili.com/video/BV1ns411D7W1](url)) to old encoding (https://www.bilibili.com/video/av2231425)

[https://greasyfork.org/zh-CN/scripts/398499-bilibili-antibv](url)
the same purpose as the one before, but in different method

**Comment by piroor** [comment]
Thank you for more information. I've installed listed addons and scripts, but still I'm not familiar to them including the website. Could you describe steps to reproduce with numbered list format? For example:

1. Install TST, TamperMonkey, and all listed addons and user scripts.
2. Open the options page of the Gooreplacer.
3. Add a rule XXX.
4. Go to the page https://www.bilibili.com/video/av2231425.
5. Click the link XXX.
6. ...

**Comment by NightSharp** [comment]
@piroor Here it is.

1. Install TST, TamperMonkey, and all listed addons and user scripts.
2. Install [Dracula Dark Theme](https://addons.mozilla.org/zh-CN/firefox/addon/dracula-dark-colorscheme/)
3. Install Extra Addons for TST
[Bookmark Tree for Tree Style Tab](https://addons.mozilla.org/zh-CN/firefox/addon/bookmark-tree-for-tst/)
[Move unloaded tabs for Tree Style Tab](https://addons.mozilla.org/zh-CN/firefox/addon/move-unloaded-tabs-for-tst/)
[Tab Unloader for Tree Style Tab](https://addons.mozilla.org/zh-CN/firefox/addon/tab-unload-for-tree-style-tab/)
[Add Last Active Class To Tab](https://addons.mozilla.org/zh-CN/firefox/addon/add-last-active-class-to-tab/)
4. Set CSS Style of TST as below:
<details>
<summary>Content</summary>

```css
#tabbar tab-item:not(:hover) tab-closebox {
  display: none;
}
tab-item tab-closebox::before {
  background: #993300;
  opacity: 1;
}

tab-item {
  background-color: var(--theme-colors-toolbar);
  --tab-size: 24px !important;
  height: var(--tab-size);
}
tab-item.active {
  height: 24px !important;
  background-color: #003399;
}
tab-item.active .label-content {
  font-weight: bold;
  font-size: 13px;
}
tab-item.active tab-twisty,
tab-item.active .label-content,
tab-item.active tab-counter {
  color: #00EEEE !important;
}

.tab.last-active {
  background-color: #990066;
}

tab-item.discarded,
tab-item.discarded tab-favicon {
  opacity: 0.50 !important;
}
tab-item.discarded tab-twisty,
tab-item.discarded .label-content,
tab-item.discarded tab-counter {
  color: #99FF66 !important;
}

tab-item.unread,
tab-item.unread tab-favicon {
  opacity: 0.80 !important;
}
tab-item.unread tab-twisty,
tab-item.unread .label-content {
  font-style: italic;
}
tab-item.unread:not(.disgarded) tab-twisty,
tab-item.unread:not(.disgarded) .label-content,
tab-item.unread:not(.disgarded) tab-counter {
  color: #00EEEE;
}

tab-item:not(.unread) tab-twisty,
tab-item:not(.unread) .label-content,
tab-item:not(.unread) tab-counter {
  color: #EEEE99;
}

.contextual-identity-marker {
  top: auto !important;
  left: 1em !important;
  right: 1em !important;
  bottom: 0 !important;
  width: auto !important;
  max-width: none !important;
  height: calc(var(--favicon-size) / 6) !important;
}

tab-item:hover,
tab-item:hover tab-favicon {
  background: #CC6600 !important;
  opacity: 1 !important;
}
tab-item:hover tab-twisty,
tab-item:hover .label-content,
tab-item:hover tab-counter {
  color: #FFFFFF !important;
}


tab-item tab-twisty {
  margin-right: -1em;
  opacity: 0 !important;
  position: relative;
  z-index: 10000;
}





.newtab-button::after {
  content: var(--tab-count-text);
  pointer-events: none;
    
  position: absolute;
  right: 2em;
}
#tabbar {
  counter-reset: vtabs atabs tabs;
  /* vtabs tracks visible tabs, atabs tracks active tabs, tabs tracks all tabs */
}
tab-item:not(.collapsed):not(.discarded) {
  counter-increment: vtabs atabs tabs;
}
tab-item:not(.collapsed) {
  counter-increment: vtabs tabs;
}
tab-item:not(.discarded) {
  counter-increment: atabs tabs;
}
tab-item {
  counter-increment: tabs;
}
.newtab-button {
  --tab-count-text: counter(atabs)"/"counter(tabs)" 个标签";
}
```
</details>

5. Keep some other tab open, and open [av2231425](https://www.bilibili.com/video/av2231425) in the newtab.
6. Focus on it.
![Focused](https://raw.githubusercontent.com/NightSharp/ImageSource/master/TST%20Issue/Focused.png)
7. Discard it in TST (Issue case).
![Focused](https://raw.githubusercontent.com/NightSharp/ImageSource/master/TST%20Issue/ErrorDiscarded.png)
8. Turn off related addons and scripts.
9. Refresh the tab.
10. Discard it in TST again (Normal case).
![Focused](https://raw.githubusercontent.com/NightSharp/ImageSource/master/TST%20Issue/Expected.png)
