### ISSUE TITLE
[Question] CSS for modal window adding bookmarks

### ISSUE THREAD

**Issue by wvxwxvw** [piroor/treestyletab#2565]
How to colorize this window?
[![](https://i.imgur.com/vAWUftC.png)](https://i.imgur.com/o7VDg09.jpg)  
This is the window for adding tabs from the tree. It doesn't pick up any global styles.
Background, text, buttons, buttons text, editable field, text of the editable field. Or, at least, how and where to writing  `@-moz-document regexp("moz-extension://...??????...") { ... }` ?

**Comment by piroor** [comment]
You can do that via the `userContent.css` , like:

```css
@-moz-document regexp("moz-extension://........-....-....-....-............/resources/blank.html") {
  .rich-confirm {
    background: white !important;
  }
}
```

BTW, the popup currently doesn't respect the Dark color scheme, so I'm planning to update that.
