### ISSUE TITLE
open/collapse group with click on title?

### ISSUE THREAD

**Issue by OhSoGood** [piroor/treestyletab#2613]
Hi
I wish to also be able to open and collapse a group by clicking on its title in addition to clicking on the twisty. Is that doable with a simple CSS rule?

Thanks for any help, and thanks to the author for that nice extension!

My CSS is so that 1. I currently have the twisty on right, and 2. the close mark appears above the favicon when hoovering. Here is my CSS:
```
/* Tab height */
tab-item { --tab-size: 25px !important; height: var(--tab-size); }

/* As little space before the tab name as possible. */
/*tab-item:not(.pinned) { padding-left: 0px !important; }*/

/* Only show tab close button on hover */
#tabbar tab-item:not(:hover) tab-closebox {
  display: none;
}

/* Put closebox left side, and twisty on right */
:root.left tab-item tab-twisty { order: 10000; }
:root.left tab-item tab-closebox { order: -1;margin-right: -1.8em; position: relative; left: -3px; /* opacity: 0 !important; z-index: 10000; */ }

/* Show scrollbar in the tab bar rightside */
:root.left #tabbar {
  direction: ltr;
  overflow-x: hidden;
}

/* Put "new tab" button at the top of the tab bar */
.newtab-button-box {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  height: 20px;
}
#tabbar {
  top: 20px !important;
  bottom: 0 !important;
}
tab-item.pinned {
  margin-top: 20px;
}

```

**Comment by piroor** [comment]
How about this?

```css
tab-item.group-tab tab-twisty {
  --twisty-size: 30em;
  --twisty-margin-size: calc(var(--twisty-size) - var(--favicon-size));
}
tab-item.group-tab:not(.collapsed):not(.subtree-collapsed) tab-twisty {
  padding-right: var(--twisty-size) !important;
  margin-right: calc(0px - var(--twisty-margin-size)) !important;
}
tab-item.group-tab:not(.collapsed).subtree-collapsed tab-twisty {
  padding-bottom: var(--twisty-size)!important;
  margin-bottom: calc(0px - var(--twisty-margin-size)) !important;
  position: relative;
  top: calc(0px - (var(--twisty-margin-size) / 2));
  right: calc(0px - (var(--twisty-margin-size) / 2));
}
```
