### ISSUE TITLE
Can I Change The Apperance too Look Like Old Tree Tab?

### ISSUE THREAD

**Issue by viking2** [piroor/treestyletab#2615]
I miss the old old Tab Tree by Sergey Zelentsov (https://github.com/traxium/tabtree).
1. Can the TST appearance by modified by Custom Style Rules to look like Tab Tree:
https://i.gyazo.com/01769c5e605f9061273b6dc2617bc611.png 
(note the dotted connecting lines and absence of lines around the tabs)

2. Some other features that I am missing are: 
a. Search Tabs
b. Clicking on the current tab takes me back to the previous tab

**Comment by irvinm** [comment]
1. Yes, in general you can use CSS to make TST look like anything you want.  You can either start with a style and tweak it or disable "decorations" altogether and do it all yourself.  (The biggest challenge I would see is drawing of the lines from parent to children ... I think there are some discussions in other issues on this)
2.  TST isn't designed around search.  I think most people just use the URL bar or a separate addon for anything search related.
3.  Did you mean "closing the current tab"?  There is a whole section in the configuration on how to handle closing tabs.  (Under "Tree Behavior")

**Comment by piroor** [comment]
> Can the TST appearance by modified by Custom Style Rules to look like Tab Tree:

Currently this is quite difficult on TST. Here is a relic of my experiment:
https://github.com/piroor/treestyletab/issues/1378#issuecomment-332721026

Fundamentally we need something way to count the number of preceding visible tabs between a tab and its parent tab. I tried to stylize more better only with CSS tricks, but finally I've given up. Here is a new relic of my experiment at today:

```css
.tab {
  overflow: visible
}

.tab:not([data-level="0"]):not(.dragging)::before {
  border: solid #BBB 1px;
  border-width: 0 0 1px 1px;
  bottom: calc(var(--tab-height) / 2);
  content: " ";
  height: calc(var(--tab-height) * var(--preceding-visible-tabs-count));
  pointer-events: none;
  position: absolute;
  width: 1em;
  z-index: 0;
}

.tab.preceding-visible-tabs-count-1::before {
  --preceding-visible-tabs-count: 1;
}
.tab.preceding-visible-tabs-count-2::before {
  --preceding-visible-tabs-count: 2;
}
.tab.preceding-visible-tabs-count-3::before {
  --preceding-visible-tabs-count: 3;
}
...
.tab.preceding-visible-tabs-count-200::before {
  --preceding-visible-tabs-count: 200;
}
```

Actually each tab doesn't have any class like `preceding-visible-tabs-count-200`, so you may need to implement any script to inject such classes to TST's tabs via [TST's API](https://github.com/piroor/treestyletab/wiki/API-for-other-addons).

This restriction comes from the DOM structure of tabs in TST's sidebar. Actually they are quite flat and just indented with `margin`. Such a structure makes styling of tree lines very hard.

I'm very sorry but I won't implement any helpful features to do this type styling on TST itself, because I won't use it by myself. If you seriously need that, I recommend you to try creating a helper addon to count visible preceding tabs for each tab, otherwise I think you need to find any other tree tab addon providing such an appearance.

> Some other features that I am missing are:
> a. Search Tabs

It is out of scope of this project. I also won't implement this feature to TST.

> b. Clicking on the current tab takes me back to the previous tab

Did you mean a feature like [Tab flip for Tree Style Tab](https://addons.mozilla.org/firefox/addon/tab-flip-for-tree-style-tab/) ?
