### ISSUE TITLE
Custom Style Rules to Retitle Tabs based on URL & Container?

### ISSUE THREAD

**Issue by viking2** [piroor/treestyletab#2640]
I found an Extension, Tab ReTitle, that let me permanently change the title on the Tabs based on the URL (https://github.com/Lazyuki/ReTitle).  However, it does not let me use different titles for the same URL in different containers.

Is it possible to write custom style rules for TST that changes the Tab Title based on URL _and_ Container?
For example:
Tab for google.com in container1 would change title to Test1
Tab for google.com in container2 would change title to Test2

(I found custom style rules for TST that changes the _appearance_ of the Tab depending on the container.)

**Comment by piroor** [comment]
It looks out of purpose of this project. Container support should be done by ReTitle itself ( https://github.com/Lazyuki/ReTitle/issues/27 ) because people who don't use TST also use it.

**Comment by viking2** [comment]
I understand. However, I just wondered if it is possible to use Custom Style Rules to accomplish this?

**Comment by piroor** [comment]
You can add suffix or prefix like following:

```css
tab-item.contextual-identity-firefox-container-1 tab-label span::after {
  content: "[Personal]"
}
tab-item.contextual-identity-firefox-container-2 tab-label span::after {
  content: "[Work]"
}
tab-item.contextual-identity-firefox-container-3 tab-label span::after {
  content: "[Banking]"
}
tab-item.contextual-identity-firefox-container-4 tab-label span::after {
  content: "[Shopping]"
}
```

But complete replacement is impossible. It is a restriction of CSS spec.
