### ISSUE TITLE
Full Auto-show/hide Theme is colapsing pinned tabs

### ISSUE THREAD

**Issue by ItayHadas** [piroor/treestyletab#2657]
Hi,

## Short description
Custom style - Full Auto-show/hide snippet is collapsing and stacking the pinned tabs - is there a way to avoid this behavior?

## Steps to reproduce
Pasting the snippet into userchrome.css 
[https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#full-auto-showhide-theme](url)

The result is seen here:

<img width="250" alt="tabtree collapsed" src="https://user-images.githubusercontent.com/5610394/88466939-6baf6480-ce9f-11ea-8125-47bdb5e04cc5.jpg">       <img width="250" alt="firefox_2020-07-25_17-30-52" src="https://user-images.githubusercontent.com/5610394/88466914-30149a80-ce9f-11ea-9c3b-b12c0cfec9df.png">

## Expected result
The snippet is working great! Is there a way to **_avoid_** the collapsing and stacking of the pinned tabs???
(this is confusing when aiming for a specific tab)

**_Thanks!!_**

**Comment by piroor** [comment]
I don't use those code snippets by myself, so I hope someone maintains and updates it...

**Comment by irvinm** [comment]
@jorjio what is your desired behavior?  Are you looking to keep the pinned tabs listed horizontally at the top and the regular tabs minimized to their favico and listed vertically?  Can you describe?

**Comment by ItayHadas** [comment]
@irvinm - Exactly! When the sidebar is collapsed I'm looking to keep the pinned tabs listed horizontally at the top (only the left most pinned tab will be seen), and the regular tabs minimized to their favico and listed vertically.
Thanks!

**Comment by irvinm** [comment]
@jorjio thanks for the clarity.  However, I do not think this is going to be possible.  You have to remember that in the first screenshot, you have the pinned tabs and regular tabs all contained within the sidebar and managed by TST.  Much of the 2nd screenshot is only possible by the fact that the entire sidebar width is reduced and everything in the sidebar has to be no wider than the width of the sidebar.  If I understand everything properly ...

**Comment by ItayHadas** [comment]
@irvinm - if I use the other snippet for sidebar auto collapse it works as I requested. But then the sidebar is not floating over the site content - it 'pushes' the entire site body - so it's not really a good alternative.
https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#auto-showhide-sidebar-by-mouseover-hover

this make me think it might be possible - but I don't really know...

**Comment by irvinm** [comment]
@piroor is there a way via CSS to change the pinned tab behavior to ignore starting a new line of pinned tabs even if the width of the sidebar is too narrow to display them all?  It looks like you are calculating the max rows and max cols for pinned tabs here: https://github.com/piroor/treestyletab/blob/0aac9737d3e915430aab250a14f073927bcf98d7/webextensions/sidebar/pinned-tabs.js#L54 
I don't think any CSS would override this behavior.  I think for what @jorjio would want, simply having maxrow = 1 would keep the pinned tabs all of the same "row" even when the sidebar is small and he would not be able to see them until expanded.  (It would keep all of his other tabs at the same row whether collapsed or expanded.)

**Comment by ItayHadas** [comment]
I figured it pretty much by accident
I copied the `overflow: hidden;` variable from the other snippet and added it under `sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"]` and `#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"]:hover`

and it works!

Sorry for wasting your time guys.
Your work is amazing!

**Comment by irvinm** [comment]
Awesome!  @jorjio will you close this item?

**Comment by kocjs** [comment]
@jorjio I am trying to do the same, but no luck so far. Give me more insight and share the relevant section that works for you.

Thanks

**Comment by ItayHadas** [comment]
@kocjs yes, sorry about that. The following is working for me:

```css
/* Sidebar min and max width removal */
#sidebar {
    max-width: none !important;
    min-width: 0px !important;
}

/* Shrink sidebar until hovered */
:root {
    --thin-tab-width: 23px;
    --wide-tab-width: 207px;
}

/* fixing sidebar*/
#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"] #sidebar {
  min-width: var(--wide-tab-width) !important;
  max-width: var(--wide-tab-width) !important;
  z-index: 1;
}

#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"] {
	overflow: hidden;
    position: relative !important;
    transition: none !important;/*all 100ms*/
    min-width: var(--thin-tab-width) !important;
    max-width: var(--thin-tab-width) !important;
}
#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"]:hover {
	transition: none !important;/*all 200ms*/
    min-width: var(--wide-tab-width) !important;
    max-width: var(--wide-tab-width) !important;
    margin-right: calc((var(--wide-tab-width) - var(--thin-tab-width)) * -1) !important;
    z-index: 1;
}

/* Hide splitter, when using Tree Style Tab. */
#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"] + #sidebar-splitter {
    display: none !important;
}
/* Hide sidebar header, when using Tree Style Tab. */
#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"] #sidebar-header {
    /*visibility: collapse;*/
	display: none !important;
}
```
