### ISSUE TITLE
Firefox theme background image suddenly used for TST

### ISSUE THREAD

**Issue by sim642** [piroor/treestyletab#2662]
## Short description
I just had TST update and my Firefox theme background image now repeats in the TST sidebar background with the Mixed theme. Since Firefox theme background images were never intended for this use and to be repeated vertically, it looks completely unreadable now. It was plain gray before, as the TST theme chooser's little image also shows. How do I undo this unwanted breaking change?

Reminds me of a very similar past breaking change which only used Firefox theme colors, not the background image: https://github.com/piroor/treestyletab/issues/2197.

## Expected result
Gray background as before the update.

## Actual result
Repeating Firefox theme background image:
![Screenshot_2020-07-29_17-35-31](https://user-images.githubusercontent.com/378740/88813990-3ae26e80-d1c2-11ea-9d24-f32f3f071312.png)

## Environment

 * Platform (OS): Xubuntu 18.04
 * Version of Firefox: 78.0.2
 * Version (or revision) of Tree Style Tab: 3.5.14

**Comment by sim642** [comment]
I noticed now that while switching TST theme, the Mixed theme initially loads with the previous and expected gray background. After 0.5s it loads the Firefox theme background image instead. So clearly the solid gray is still part of TST but gets dynamically overridden by the Firefox theme image.

**Comment by piroor** [comment]
As a workaround, you can expand the background image to cover the sidebar area with this styles declaration:

```css
#background {
  background-position: left;
  background-size: cover;
}
```

Screenshot:
![image](https://user-images.githubusercontent.com/70062/88818393-9ed45980-d1f9-11ea-994f-60458aa36a19.png)

I've introduced this as a part of the builtin style with the commit e4b6f7b.

And, if you don't like to apply background images to the sidebar, this will help you:

```css
#background {
  background-image: none !important;
  /* and you can override the background color also.
  background-color: darkgray !important;
  */
}
```

**Comment by sim642** [comment]
Thanks for the quick reply! The CSS workarounds improve the situation but even with an overridden gray background color it doesn't look exactly as it did before (and it doesn't look like what the TST theme icon shows). The background (image or color) shows through the tab rows themselves as opposed to them being lighter gray and the active one being light blue.

When switching between TST themes, it momentarily loads without any Firefox theming applied with the previous and expected colors. I just want to still have that. When the Firefox theming is applied, the tab rows' backgrounds become transparent etc, which is nothing like what the Mixed theme icon shows.

**Comment by piroor** [comment]
OK, here is an example to unset all colors and images cited from the browser theme:

```css
:root {
  --browser-background: unset;
  --browser-bg-base: unset;
  --browser-bg-less-lighter: unset;
  --browser-bg-lighter: unset;
  --browser-bg-more-lighter: unset;
  --browser-bg-lightest: unset;
  --browser-bg-less-darker: unset;
  --browser-bg-darker: unset;
  --browser-bg-more-darker: unset;
  --browser-fg: unset;
  --browser-fg-active: unset;
  --browser-border: unset;
  --browser-header-url: unset;
  --browser-bg-url: unset;
  --browser-bg-for-header-image: unset;
  --browser-bg-hover-for-header-image: unset;
  --browser-bg-active-for-header-image: unset;
  --browser-textshadow-for-header-image: unset;
  --browser-tab-highlighter: unset;
  --browser-loading-indicator: unset;
  --theme-colors-frame: unset;
  --theme-colors-tab_background_text: unset;
  --theme-images-theme_frame: unset;
}
```
