### ISSUE TITLE
[question]Changing closebox with png image

### ISSUE THREAD

**Issue by Altsinn** [piroor/treestyletab#2675]
## Short description
Hi @piroor, to modify Firefox appearance I use this project: 

https://github.com/Aris-t2/CustomCSSforFx

It has several options to change closebox style. I use ./css/generalui/close_icon_windows7v2.css

Inactive:
![obraz](https://user-images.githubusercontent.com/50676021/89219826-cf890a00-d5d0-11ea-8f9f-1b4361d38091.png)

Active:
![obraz](https://user-images.githubusercontent.com/50676021/89219900-edef0580-d5d0-11ea-8982-a021d0c47d6b.png)

CSS

[close_icon_windows7v2.zip](https://github.com/piroor/treestyletab/files/5018110/close_icon_windows7v2.zip)

PNG

![close_w7v2](https://user-images.githubusercontent.com/50676021/89220920-aff2e100-d5d2-11ea-9a39-a2319c758e2e.png)

I spent hours trying to replace the default TST closebox with above and I failed. I tried to modify Aris code, incorporate it to your code snippets, convert png image to svg ect. 

It's important to me to have an unified look and the default TST closebox style, even modified, looks out-of-place with the rest. Leaving the the default Firefox metro/material style is no option to me. 

Is it possible to achieve above style in TST? I will greatly appreciated any guidance.

**Comment by piroor** [comment]
I successfully done it with following style declarations:

```css
tab-closebox::before {
  content: none !important;
}
tab-closebox::after {
  mask: none !important;
  background: transparent url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAQCAYAAABQrvyxAAAByklEQVRIie2WsYrCQBCGr7LxCdJYHCoplhCOFLJpAh6CFpapEt8kXBqf4Cq7NDaCjU1SWIR9AcuzjYUPYGNzyVw1y7om2cXjmsOBv5lk4PtgZ9mXl2f9k2Kuu9xRCjphrruU51fD4fJzMKh0shoO7+Z/XQfPg6/pVCsHzwN5PjHNaus4oJPENKtGkPF8YfVHs9iahF3sWZOw2x/N4vF8YTXNIVwRRQBlCUff58BH3wcoSyiiiPfk+TUhsHUc2AcBnPMcdpRy4B2lcM5z2AcBbB0H1oTczfPqj2YxxpqEXYTHqASgLHmOvs/hMSqBc57z4JETe0qBjDHj9e39oy4ZY4ZKQAaWhVQCMrAspBRokmiDFwVQorxebyLCNwlsbBs2tl0rsaOUf1cKWJOw2yM0RvgeoTc7UVcHzwNMk4D4j0rglKY30RZA+Lq0SYjw35dLbUQJeT4xzaoJXpZovYVE4IwxI2PMEHsqAREYj4vYUwnIwLKQUmA8X1gIjz2UaLtGEayIIg6PPZQooqhVYE0I7IMATmnKlxWX+5SmsA8CWBPSLgAAnbqFzRgzAKCjEtBNk4BOWgUeLea6S134pqdEYpqVTv7kKfGsB+sHvEgqflZeWqcAAAAASUVORK5CYII=") no-repeat left !important;
}
tab-closebox:hover::after {
  background-position: center !important;
}
tab-closebox:active::after {
  background-position: right !important;
}
```

Please note that you need to put it to TST's options page instead of userChrome.css.
