### ISSUE TITLE
Featue Request: Display Hidden Tabs - see the "Simpl Tab Groups" Add on.

### ISSUE THREAD

**Issue by Mcmeman** [piroor/treestyletab#2697]
A feature Request, I use Tree Style Tab in conjunction with Simple Tab Groups. This add on hides tabs in groups you set and dictate date. However it would be super helpful if the Tree Style tab Sidebar could still show hidden tabs. This would make hoping between groups and accessing tabs on another group seamless.

This would be somewhat similar to the interface you see in in Vivaldi's sidebar.

Please let me know what additional details, logs, screenshots I can provide.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. 
 4. 

## Environment

 * Platform (OS): 
 * Version of Firefox: 
 * Version (or revision) of Tree Style Tab:

**Comment by piroor** [comment]
It can be done with a user style:

```css
tab-item.hidden {
    opacity: 0.5; /* show hidden tabs as half-transparent for convenience */
    pointer-events: initial;
    position: relative;
    visibility: visible;
}
```
