### ISSUE TITLE
How do I set transparent colors to the whole sidebar like I did for history/bookmarks so that it would blend in with the theme? 

### ISSUE THREAD

**Issue by mzso** [piroor/treestyletab#2759]
Hi!

I've been tinkering with pasting stuff from the snippets page, but virtuall nothing has any visual effect. (Only the "Disable browser theme colors and images" section does)

Particularly I had this CSS for ages, and it still works:
```css
#bookmarksPanel, #history-panel, #sidebar, #sidebar-header, #sidebar-box
{
  /*background-color: transparent !important;*/
  background-color:  rgba(255,255,255,0.2) !important;
}

.sidebar-placesTreechildren::-moz-tree-row(hover) {
   background-color: rgb(205,243,159) !important;
}

.sidebar-placesTreechildren::-moz-tree-row(selected) {
   background-color: rgb(255,235,134) !important;
}
.sidebar-placesTreechildren::-moz-tree-row(selected, focus) {
background-color: rgb(255,100,50) !important;
}
```

But since these are tabs, I also want unloaded tabs to have transparent text/icons to show this. For the normal tab-bar I also used to distinguish loaded, but unviewed tabs by changing the text color and the background color. (via Classic Theme Restorer)
