### ISSUE TITLE
Grouping tabs without indentation, but separating groups by white space

### ISSUE THREAD

**Issue by icher** [piroor/treestyletab#2777]
Hi. 

Old TST (pre-webextensions) allowed grouping tabs without indentation, but separated by white space. May be it was undocumented function or even a bug, only worked by editing about:config variable, some kind of "indent_tabs_until=-1" or like that. It was VERY useful. But new TST can't do that. Is it possible to implement that behavior by webextension-api?

Bookmarks sidebar can use separators ("Add separator" horizontal straight line) -- may be it's the way to go.

![old_tst](https://user-images.githubusercontent.com/8604717/101274976-7aeadb00-37cc-11eb-85f4-d1efc98a15a7.png)

**Comment by piroor** [comment]
Spacings between root level tabs can be emulated with a custom style rules like:

```css
/* show separator space between root level tabs */
tab-item[data-level="0"] {
  margin-top: var(--tab-size);
}
/* cancel needless separators on exceptions */
tab-item[data-level="0"].pinned,
tab-item[data-level="0"].pinned + tab-item[data-level="0"],
tab-item[data-level="0"] + tab-item[data-level="0"]:not([data-child-ids]) {
  margin-top: 0;
}

/* make collapsed tabs visible */
tab-item:not(.pinned).collapsed,
tab-item:not(.pinned).collapsed.collapsed-completely {
  margin-top: 0;
  opacity: 1;
  visibility: visible;
}
```

Setting the max indent level to zero with this style rules will work like the old one.

**Comment by piroor** [comment]
Sorry but it won't be a built-in option of TST itself, because:

* The style (appearance and behavior) is quite different from my usecase and codes for the mode never be used on my environment.
* For better maintainability I hope to keep TST clean from such dead codes.

**Comment by icher** [comment]
Jesus Christ, man, since webextensions I suffering from lack of this feature! It works like a charm. Thanks. I modified it a little bit for my taste:
```css
/* show separator space between root level tabs */
tab-item[data-level="0"] {
  margin-top: 8px;
}

/* cancel needless separators on exceptions */
tab-item[data-level="0"].pinned,
tab-item[data-level="0"].pinned + tab-item[data-level="0"],
tab-item[data-level="0"] + tab-item[data-level="0"]:not([data-child-ids]) {
  margin-top: 0;
}

/* sidebar background */
:root.sidebar #background {
  background: #6c6c6c;
}
```


Maybe you should add it to the "Code Snippets" documentation.

**Comment by irvinm** [comment]
@icher, can you close this item?  Thanks.

**Comment by silverwings15** [comment]
interestingly, i get a 'ghost' tab in the background of my side bar if i use @icher 's sidebar background color CSS, but only if i replace it with a gradient, such as

```css

/* sidebar background */
:root.sidebar #background {
  background: rgb(238,156,167) linear-gradient(90deg, rgba(238,156,167,1) 0%, rgba(251,193,200,1) 100%);
   opacity: .25 !important;
}
```

![image](https://user-images.githubusercontent.com/10742312/101530065-011d4200-39c4-11eb-886c-1b653e35beda.png)

**Comment by piroor** [comment]
I've added a new section to the code snippets:
https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#grouping-tabs-with-spaces-instead-of-indented-tree-2777
But I won't maintain it aggressively so it need to be maintained by people who actually use.

**Comment by icher** [comment]
> I've added a new section to the code snippets:
> https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#grouping-tabs-with-spaces-instead-of-indented-tree-2777

Actually, last section "make collapsed tabs visible" do not need, collapse group is useful feature. Without this section all works great. The idea is just economy of space, no change the behaviour.

![Screenshot from 2020-12-09 12-07-12](https://user-images.githubusercontent.com/8604717/101591631-28512f00-3a17-11eb-9a28-a8485c9ea681.png)

**Comment by piroor** [comment]
> Actually, last section "make collapsed tabs visible" do not need, collapse group is useful feature.

OK, I've removed the last section.

**Comment by silverwings15** [comment]
@piroor do you have any idea what the 'thing' in my screenshot could be?

**Comment by silverwings15** [comment]
i tried setting `tab-item.active` to `opacity: 0` and this is what i see 

![image](https://user-images.githubusercontent.com/10742312/101635569-b7cd0100-3a5c-11eb-9947-582c975308ba.png)


edit: managed to capture the entire bar

![image](https://user-images.githubusercontent.com/10742312/101645102-8fe39a80-3a68-11eb-85f4-68a0237d0bde.png)

**Comment by piroor** [comment]
Ah, it is by design. TST has a "fake" tab behind the background screen element to calculate size of tabs, favicons, and others. It will be revealed unexpectedly for now, if you use transparent color for the `#background` element. Until I find ouf some better solutions, you shouldn't use transparent color for the background.

**Comment by silverwings15** [comment]
seems like i peeked behind the wizard's curtain by accident :D appreciate the explanation

**Comment by piroor** [comment]
The commit 9411efb should hide the dummy elements completely.

**Comment by silverwings15** [comment]
amazing work you're doing here, thank you once again!!

**Comment by silverwings15** [comment]
@piroor hmm seems like you managed to get rid of the dummy tab, but these 'open new tab as' (?) options still linger

![image](https://user-images.githubusercontent.com/10742312/102780071-e5ed0200-43c7-11eb-879f-da0cd45b4799.png)

**Comment by silverwings15** [comment]
well they're only present briefly when you activate the sidebar, so i guess they're not a big deal

**Comment by piroor** [comment]
@mimecry Sorry I missed that. Here is a workaround:

```css
body > ul[id$="selector"] {
  opacity: 0;
}
```

Now it is included by default with the commit 61a6fbb6e.
