### ISSUE TITLE
TST uses a different colour scheme then Firefox

### ISSUE THREAD

**Issue by Peilonrayz** [piroor/treestyletab#2780]
## Description

TST's plain style doesn't use the same colours as Firefox's tabs for regular surface, regular active and border. This made TST have white borders and blue surfaces when Firefox's UI is my selection of greys.

## Fix

I have fixed these with the following CSS change:

```css
:root {
  --tab-surface-regular: var(--theme-colors-tab);
  --tab-surface-active: var(--theme-colors-tab_selected);
  /* Firefox doesn't seem to have a active hover colour */
  /* --tab-surface-active-hover: var(--theme-colors-tab_selected); */
  --tab-border: var(--theme-colors-tab_background_separator);
}
```

You can test these are updated with the theme by using [Firefox Color](https://color.firefox.com/).

-   `--tab-surface-regular`: Custom Colors > Background Color
-   `--tab-surface-active`: Advanced Colors > Tab Selected
-   `--tab-surface-border`: Advanced Colors > Tab Background Separator

## Environment

 * Platform (OS): Linux-5.9.11-arch2-1-x86_64-with-glibc2.32
 * Widget Toolkit: GTK3 1:3.24.24-1
 * Window Manager: Awesome 4.3-2
 * Version of Firefox: 83.0
 * Version of Tree Style Tab: 3.6.3
