### ISSUE TITLE
Error with viewing text in option settings

### ISSUE THREAD

**Issue by medievalberries** [piroor/treestyletab#2842]
## Short description

An error with viewing text in option settings

## Steps to reproduce

I do not know how to reproduce this issue. Sorry. I am on a clean install of Firefox and the problem persists.

## Expected result

As perviously, I had expected text and buttons when viewing the options in the addons permissions sections. This would allow me to tweak the extension.

## Actual result

![image](https://user-images.githubusercontent.com/75999097/112590683-257a1e80-8dfb-11eb-9e68-9f6347b38785.png)

I cannot see any of the text which would allow me to tweak TST. I have disabled my userChrome.css, dark reader and switched back to light theme. None of which worked.

## Environment

 * Operating System: Windows 10 (20H2)
 * Version of Firefox: 87.0 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.7.3

**Comment by piroor** [comment]
Sadly I couldn't reproduce the problem on my environment: Firefox 87.0 (64bit) + Windows 10 Pro 20H2 + TST 3.7.3
Screenshot with the dark mode (configured via the options of Windows itself):
![image](https://user-images.githubusercontent.com/70062/112780044-f4ac1a80-9082-11eb-8095-1287ced2f86c.png)
Any other possible trigger?

**Comment by Sei-lus** [comment]
Had the same problem. In my case it is related to userContent.css:
https://cdn.discordapp.com/attachments/763858377121857568/831543170268397638/unknown.png

```css
@-moz-document url-prefix(moz-extension://), url-prefix(about:addons) {
.inline-options-stack {background-color: #000 !important;}
label {color: #fff;}
p {color: #fff;}
h1 {color: #fff;}
legend {color: #fff;}
th {color: #fff;}
pre {color: #fff;}
h2 {color: #fff;}
span input, button {color: #fff;}
label input {color: #fff;}
}
```
I guess it could be shortened to:
```css
@-moz-document url-prefix(moz-extension://), url-prefix(about:addons) {
.inline-options-stack {background-color: #000 !important;}
label,p,h1,h2,legend,th,pre,span input,span button,label input {color: #fff;}
}
```


I had to use the page source to work around it and my fix is the code above.
https://cdn.discordapp.com/attachments/763858377121857568/831582726943015012/unknown.png

By the way, Piroor... can you link me to somewhere where I can get info about how to modify ColoredTabs to color only borders?

Having trouble finding that info.
