### ISSUE TITLE
Can't use "margin-right" in "tab-item" in version 3.7.4

### ISSUE THREAD

**Issue by pnthach95** [piroor/treestyletab#2848]
## Short description

After updated to version 3.7.4, `margin-right` in `tab-item` is not working

## Steps to reproduce

 1. Import my settings: [tst-margin-right-bug-v3.7.4.txt](https://github.com/piroor/treestyletab/files/6238196/tst-margin-right-bug-v3.7.4.txt)
 2. Load my theme

```css
:root{
  --active-tab-color-a     : #0c549c;
  --active-tab-color-b     : #0c9c65;
  --active-tab-color-shadow: rgba(12, 156, 101, 0.7);
  --active-tab-text-color  : white;
  --tab-hover-color        : darkslategray;
  --tab-text-color         : white;
  --close-box-background   : #dc143c;
}

tab-item {
  margin       : 15px 10px;
  margin-right : 30px;
  border-radius: 5px;
  padding-top  : 5px;
  padding-right: 10px;
  transition   : all 0.3s ease-i-out !important;
}

tab-item .label{   
  color: var(--active-tab-text-color ) !important;
}

tab-item.active {
  background  : linear-gradient(to right, var(--active-tab-color-a), var(--active-tab-color-b)) !important;
  box-shadow  : 5px 0 15px -1px var(--active-tab-color-shadow);
  margin-right: 18px;
  font-weight : bolder;
  transition  : scale 0.3s ease-i-out !important;
  color       : var(--tab-text-color ) !important;
}
tab-item:hover {
  background: var(--tab-hover-color ) !important;
  box-shadow: 0 5px 20px -5px var(--tab-hover-color ) !important;
}

tab-item:not(:hover) tab-closebox {
  right    : -30px;
  transform: scale(110%);
}

tab-item tab-closebox{
  position     : absolute;
  right        : 10px;
  height       : 25px;
  width        : 25px;
  padding-top  : 5px;
  background   : var(--close-box-background);
  opacity      : 1;
  border-radius: 50%;
  transition   : all 0.1s ease-in-out;
}

:root.right tab-item tab-twisty {
  display: none;
}

:root.right tab-item tab-favicon {
  transform: scale(120%);
  margin-left: 20px;
  margin-bottom: 8px;
  order: 1000;
  filter: drop-shadow(0px 4px 6px rgba(0,0,0,0.2)) grayscale(80%) opacity(80%);
  transition: all 0.2s ease-in-out;
}

:root.right tab-item.active:not(:hover) tab-favicon {
  filter: drop-shadow(0px 4px 6px rgba(0,0,0,0.2)) grayscale(10%) opacity(80%);
  transform: scale(150%);
  margin-right: 5px;
}

:root.right tab-item:hover tab-favicon, :root.right tab-favicon {
  transform: scale(50%);
}

:root.right tab-item:hover tab-favicon 
{
//  margin-left: -15px;
}

.tab:not(.group-tab):not([data-current-uri^="chrome:"]):not([data-current-uri^="about:addons"]):not([data-current-uri^="about:preferences"]) 
.favicon .favicon-default::before {
  background: url("chrome://branding/content/identity-icons-brand.svg") no-repeat center / 100% !important;
  mask: none !important;
}
```

 3. Change `margin-right` to any value in `tab-item` and `tab-item.active`

## Expected result

Version 3.7.3 screenshot

![image](https://user-images.githubusercontent.com/31266357/113180805-5f27ab00-927b-11eb-824d-96fec5100aa3.png)

## Actual result

Version 3.7.4 screenshot

![Screenshot 2021-03-31 233808](https://user-images.githubusercontent.com/31266357/113180743-4ae3ae00-927b-11eb-9daf-9c03ae518894.png)

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 87.0
 * Version (or revision) of Tree Style Tab: 3.7.4

**Comment by irvinm** [comment]
This worked for me to get indenting to match up:
```
:root.right tab-item {
  margin       : 15px 10px;
  margin-right : 30px !important;
  border-radius: 5px;
  padding-top  : 5px;
  padding-right: 10px;
  transition   : all 0.3s ease-i-out !important;
}

:root.right tab-item.active {
  background  : linear-gradient(to right, var(--active-tab-color-a), var(--active-tab-color-b)) !important;
  box-shadow  : 5px 0 15px -1px var(--active-tab-color-shadow);
  margin-right: 18px !important;
  font-weight : bolder;
  transition  : scale 0.3s ease-i-out !important;
  color       : var(--tab-text-color ) !important;
}
```

**Comment by piroor** [comment]
There looks to be a missing step to reproduce: setting TST's appearance to "right side" style.

On TST 3.7.4 I've introduced new custom properties `--tab-margin-left/right/top/bottom` to define visual margins (it is defined to the `:root` by default). Sorry I forgot to document it to the change log.

TST uses `margin-left` or `margin-right` to apply indentation, so customizing of side margins of tabs was hard. Now you can use those custom properties to apply any extra margin with TST's indentation, like as:

```css
tab-item {
  --tab-margin-right: 30px;
}

tab-item.active {
  --tab-margin-right: 50px;
}
```
