### ISSUE TITLE
Is it possible to remove the "New Tab" option in the right-click menu?

### ISSUE THREAD

**Issue by chunderbolt** [piroor/treestyletab#2887]
When you right click a tab, a "New Tab" option is at the top of the context menu as of 3.8.0.

Generally, if I were opening a blank tab I would use a keyboard shortcut or the + button at the bottom of the tab list. When right-clicking a tab, I am normally attempting to refresh the tab. Would it be possible to get an option to toggle it off?

If not, is it otherwise removable via userscripts? I'm happy enough to do that.

**Comment by irvinm** [comment]
https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#hide-context-menu-items-in-the-sidebar-2116

**Comment by chunderbolt** [comment]
Nice, solved.

The newTab stuff isn't mentioned in the file that the above link says contains the context entries, so for anyone else looking to remove the new tab item:

```css
*[id^="treestyletab_piro_sakura_ne_jp-menuitem-_context_newTab"],
*[id^="treestyletab_piro_sakura_ne_jp-menuitem-_context_separator:afterNew"] {
  display: none;
}
```
