### ISSUE TITLE
Scroll Bar

### ISSUE THREAD

**Issue by JeffGart** [piroor/treestyletab#2911]
I used to get a scroll bar that allowed be to easily jump around in tabs and subtabs. For the past few months I have been unable to get them to display.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. 
 4. 

## Environment

 * Platform (OS): 
 * Version of Firefox: 
 * Version (or revision) of Tree Style Tab:

**Comment by piroor** [comment]
Do you mean "the scroll bar in the TST sidebar is suddenly hidden"? Then, please try them:

* If you use user style rules, clear it at first.
* Try exporting existing options and reset all in TST's options page. You can see "export" and "reset" buttons under TST's options => Development => All Configs.
* If you use some other addons together, please try bisection to find out the trigger addon. https://github.com/piroor/treestyletab/wiki/How-to-minimize-conditions-to-reproduce-a-problem

**Comment by irvinm** [comment]
@JeffGart any updates on this one?

**Comment by JeffGart** [comment]
Apparently the scroll bar is really narrow and on the left. It used to be on the right. But it is there so I’m all good. Thanks for checking!
    	
    	
    
  
 From: irvinm ***@***.***>Sent: Saturday, June 12, 2021 3:07 PMTo: piroor/treestyletabCc: JeffGart; MentionSubject: Re: [piroor/treestyletab] Scroll Bar (#2911) 
@JeffGart any updates on this one?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/piroor/treestyletab/issues/2911#issuecomment-860095889",
"url": "https://github.com/piroor/treestyletab/issues/2911#issuecomment-860095889",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by irvinm** [comment]
That is good to hear @JeffGart ... will you close this item then?  Thanks.

**Comment by irvinm** [comment]
@piroor I think it is ok to close this one.

**Comment by h4-n1** [comment]
I think I'm having the same issue on Manjaro / Firefox 89.0.2. The scrollbar that would show up on the right moved to the left, and then it disappeared. Yesterday I could get it to show up by opening a lot of empty tabs, but now nothing will trigger it. Resetting configs didn't help.

**Comment by JeffGart** [comment]
I found that the bar is now VERY narrow and hard to notice but it is there. See if it is actually there on the left side but barely noticeable.
 
 
-----Original Message-----

**Comment by piroor** [comment]
@JeffGart Does this snippet "Show scrollbar with regular width" help you?
https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#show-scrollbar-with-regular-width
And a screenshot may help me to understand what happens on your environment.

**Comment by JeffGart** [comment]
The attached shows the narrow scroll bar. It is very light color as well so between the 2, it is hard to even notice. I don't know how to change the setting to make it wider. Normally the scroll bar in most apps is on the right side anyway.
 
 
-----Original Message-----

**Comment by piroor** [comment]
@JeffGart Did you respond to messages via emails and attached images? Sadly they look to be removed by the mail server or GitHub and they are not visible on the Web UI https://github.com/piroor/treestyletab/issues/2911 . Could you upload them via the comment form again?

**Comment by JeffGart** [comment]
![scroll](https://user-images.githubusercontent.com/85031072/125790864-d0aaede1-5c8a-4016-bac6-6a7d003ec955.png)

**Comment by JeffGart** [comment]
As I said, I used to have a wide one on the right side of the tabs. Then it disappeared and somehow I was able to get it back. But it showed up on the left of the tabs and is very narrow.

**Comment by JeffGart** [comment]
I only responded because someone else was having similar issues. I am dealing with the narrow bar.

**Comment by piroor** [comment]
Thanks. Here is an example to customize the scrollbar (you need to set it to TST options => Advanced => Extra style rules for contents provided by Tree Style Tab).

```css
:root.left #tabbar {
  /* show scrollbar rightside https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#show-scrollbar-in-the-tab-bar-rightside-1362 */
  direction: ltr;
  overflow-x: hidden;

  /* regular width scrollbar https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#show-scrollbar-with-regular-width */
  scrollbar-width: auto;

  /* custom scrollbar colors https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#custom-scrollbar-colors-2911 */
  scrollbar-color: red blue;
}
```

![screenshot](https://user-images.githubusercontent.com/70062/125884938-6e9ad760-1d6f-4abb-b255-4ce69eee0061.png)
