### ISSUE TITLE
Wiki suggestion

### ISSUE THREAD

**Issue by altano** [piroor/treestyletab#2924]
At [Apply tab colors exactly same to Firefox's native #2780](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#apply-tab-colors-exactly-same-to-firefoxs-native-2780) you say how to use native Firefox colors. I think this needs some tweaking.

1. `tab_background_separator` has been deprecated in FF89. It looks like `tab_line` is the only way to customize the native border in FF89. Since that is the main border customization it probably makes sense to use that as a fallback like so: `--tab-border: var(--theme-colors-tab_background_separator, var(--theme-colors-tab_line, var(--theme-colors-tab_background_text-30, hsl(240,9%,32%) /* from https://searchfox.org/mozilla-central/rev/8d722de75886d6bffc116772a1db8854e34ee6a7/browser/themes/shared/tabs.inc.css#684 : --tab-text-regular * 0.3 opacity */)));`
2. `--tab-surface-regular: var(--theme-colors-tab);` is the first line but I don't see `tab` in [the official theme documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/theme#colors). This should probably reference `frame_inactive` according to the docs: `--tab-surface-regular: var(--theme-colors-tab, var(--theme-colors-frame_inactive));`
3. The active tab's text color is set to `--tab-text-active: var(--theme-colors-toolbar_text, ...);`. `toolbar_text` is the active tab's color only if `tab_text` is not set. We should use `tab_text` (to better match native functionality AND to allow customization of the active tab's text color to be something different than the toolbar text color like so: `--tab-text-active: var(--theme-colors-tab_text, var(--theme-colors-toolbar_text, -moz-DialogText /* from https://searchfox.org/mozilla-central/rev/8d722de75886d6bffc116772a1db8854e34ee6a7/toolkit/themes/windows/global/tabbox.css#27 */));`

All these proposed changes together:

```css
:root {
  --tab-surface-regular: var(--theme-colors-tab, var(--theme-colors-frame_inactive));
  --tab-surface-active: var(--theme-colors-tab_selected, var(--theme-colors-toolbar, var(--browser-bg-for-header-image, var(--tab-like-surface))));
  --tab-surface-active-hover: var(--theme-colors-tab_selected, var(--theme-colors-toolbar, var(--browser-bg-for-header-image, var(--tab-like-surface))));
  --tab-surface-hover: rgba(255,255,255,.1) /* from https://searchfox.org/mozilla-central/rev/8d722de75886d6bffc116772a1db8854e34ee6a7/browser/themes/shared/tabs.inc.css#590 */;
  --tab-border: var(--theme-colors-tab_background_separator, var(--theme-colors-tab_line, var(--theme-colors-tab_background_text-30, hsl(240,9%,32%) /* from https://searchfox.org/mozilla-central/rev/8d722de75886d6bffc116772a1db8854e34ee6a7/browser/themes/shared/tabs.inc.css#684 : --tab-text-regular * 0.3 opacity */)));
  --tab-text-regular: var(--theme-colors-tab_background_text, hsl(240,9%,98%) /* from https://searchfox.org/mozilla-central/rev/8d722de75886d6bffc116772a1db8854e34ee6a7/toolkit/themes/windows/global/tabbox.css#27 */);
  --tab-text-active: var(--theme-colors-tab_text, var(--theme-colors-toolbar_text, -moz-DialogText /* from https://searchfox.org/mozilla-central/rev/8d722de75886d6bffc116772a1db8854e34ee6a7/toolkit/themes/windows/global/tabbox.css#27 */));
  --tabbar-bg: var(--theme-colors-frame, hsl(235,33%,19%) /* from https://searchfox.org/mozilla-central/rev/8d722de75886d6bffc116772a1db8854e34ee6a7/browser/themes/windows/browser-aero.css#59 */);
}
```
