### ISSUE TITLE
TST is unexpectedly using darker background color on Firefox v89.0 and default theme

### ISSUE THREAD

**Issue by cosmo0920** [piroor/treestyletab#2942]
## Short description

After I upgrade Firefox to v89.0, TST starts to use "darker" background color with default theme.
But, tab bar still use gray color that I expected to be used in TST.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST 3.8.2.
 3. Use TST with Firefox v89.0 and use default theme.
 4. Background color glitch is occurred.

## Expected result

When with default theme and not to be enabled night mode, the following appearance I'd expected. 

![Screenshot from 2021-06-14 18-24-41](https://user-images.githubusercontent.com/700876/121870236-cd89ee80-cd3d-11eb-9670-1ce7c1df02c2.png)

## Actual result

When with default theme and not to be enabled night mode, I got the following appearance. (TST uses darker background)

![Screenshot from 2021-06-14 18-20-19](https://user-images.githubusercontent.com/700876/121869892-7421bf80-cd3d-11eb-8f8b-19180cc933d6.png)
![Screenshot from 2021-06-14 18-21-28](https://user-images.githubusercontent.com/700876/121869910-784ddd00-cd3d-11eb-9aaa-598cd9ec5366.png)

## Environment

 * Platform (OS): Ubuntu 18.04 Bionic
 * Version of Firefox:  89.0
 * Version (or revision) of Tree Style Tab:  3.8.2

![Screenshot from 2021-06-14 18-14-07](https://user-images.githubusercontent.com/700876/121869998-91568e00-cd3d-11eb-8bce-444984f8bb15.png)

**Comment by piroor** [comment]
This is intentional. Currently TST's theme color for Linux is made for the default theme of Ubuntu. Here  is a screenshot on Ubuntu 20.04LTS:
![image](https://user-images.githubusercontent.com/70062/121871482-1f7f4400-cd3f-11eb-91b5-7b618ecc95eb.png)
Sadly Firefox doesn't provide ability to know the exact background color of the native tab bar on GNOME3 to extensions. So I had to decide just one from possible colors. I thought that [inverted menu color (system colors `Menu` and `MenuText`: I use `Menu` as the text color, `MenuText` as the background color)](https://github.com/piroor/treestyletab/blob/9d202c3337fd7baa0c1cb3f4f9b1ab18c4622d62/webextensions/sidebar/styles/proton/proton.css#L79-L97) looks natural on this environment.

Here is a workaround user styles to override those colors:

```css
:root[color-scheme="system-color"][data-user-agent*="Linux"]
  tab-item:not(.active):not(.bundled-active):not(.highlighted),
:root[color-scheme="system-color"][data-user-agent*="Linux"]
  .after-tabs button,
:root[color-scheme="system-color"][data-user-agent*="Linux"]
  .after-tabs [role="button"],
:root[color-scheme="system-color"][data-user-agent*="Linux"]
  #subpanel-selector-anchor,
:root[color-scheme="system-color"][data-user-agent*="Linux"]
  #background {
  --toolbar-non-lwt-bgcolor: (something background color);
  --toolbar-non-lwt-textcolor:(something foreground color);
}
```
