### ISSUE TITLE
New code snippet to remove vertical space between tab borders and tab active areas

### ISSUE THREAD

**Issue by mintern** [piroor/treestyletab#2946]
**Before my tweak:**

![Screenshot from 2021-06-16 10-49-40](https://user-images.githubusercontent.com/3847612/122268237-af80d300-ce90-11eb-879f-c03c00324ed4.png)

**After:**

![Screenshot from 2021-06-16 11-10-36](https://user-images.githubusercontent.com/3847612/122270823-92013880-ce93-11eb-8967-6d5ca3563e23.png)

On Firefox 89.0, the tabs are now much more spaced out. The primary issue seems to be that there is space between the tab borders (using the [tab border snippet](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#change-tab-border)) and the rounded active/hover area of the tab. I didn't find anything in the code snippets to remove this space.

I have Firefox's density set to compact, and I also tried their recommendations for [Reducing vertical spacing in menus](https://www.userchrome.org/firefox-89-styling-proton-ui.html#menuspacing). I tried multiple different theme combinations, 

I was able to fix this by adding the following extra style rules:

```css
/** Compact tabs without vertical negative space **/
tab-item {
  padding-top: 3px;
  padding-bottom: 3px;
}
tab-item .background {
  top: 0;
  bottom: 0;
}
```

That snippet also includes `padding` tweaks to decrease the height back to approximately a pre-Proton appearance.

I didn't see anything like this in the code snippets. Would it be worth adding?
