### ISSUE TITLE
[UX Discussion/Help] Tree indentation with code editor tree line style

### ISSUE THREAD

**Issue by haoadoreorange** [piroor/treestyletab#2948]
## Short description
Hello, I recently made a few modification to the TST indentation, and since it makes more sense this way I thought it might be nice to have it as default.

Here's the current default:
![image](https://user-images.githubusercontent.com/22086462/122604807-12779300-d066-11eb-8546-c788f420f13a.png)
And here's mine:
![image](https://user-images.githubusercontent.com/22086462/122604849-23c09f80-d066-11eb-9dbf-ac179d88b6eb.png)

Notice how the arrow of the tab level 1 used to be on the same indentation of the tab level 0 ?
For a long time I often feel confusing whether the below tab belongs to the subtree but didn't really know what is the problem. Here's the little snippet:
```
/* Tree line */
tab-item[data-parent-id] {
    border-left: 0.0007em dashed grey;
    margin-left: calc(var(--tab-margin-left) + var(--tab-indent)*2.2) !important;
}
```

[Help]: Now after having the proper indentation. I'm trying to get vscode-like line level indicator.
![image](https://user-images.githubusercontent.com/22086462/122605299-c8db7800-d066-11eb-8ec6-b7fddd6e35fc.png)
with one long line for the whole level. I'm trying to use border for that but having difficulty on nested levels since the number of possible borders (workaround) are limited. Does someone have a solution/done this before ?

**Comment by irvinm** [comment]
@piroor maybe move this to the discussions section?

**Comment by irvinm** [comment]
@haoadoresorange I spent a little time looking at this today and thought I would share my thoughts.  (Please keep in mind I am not a CSS expert)

The reason your CSS works is that you are changing how the far left border is both displayed (dashed grey) and where is is located (changing the indentation).  What you are trying to do is to continue other dashed lines down along side of them.  The challenge I see is that basically for each tab that has the dashed line is that there is nothing to the left of that border.  The only thing out there is the background.

![image](https://user-images.githubusercontent.com/979729/122646041-4d6fda00-d0eb-11eb-97f2-86faeddf431b.png)

I think the only real way to do what you want to do is to leave all the tabs at the root level (far left) and then basically indent the content of the tab when the tab should be indented.  There would still have to be some number of "lines" that you would either hide or show and re-space for each level down.  All of this I think would be pretty challenging and unless there were lines for you to manipulate, I am not even sure you could do anything via CSS.

Maybe @piroor or someone else might have a better idea.

**Comment by irvinm** [comment]
One new idea, but maybe you could add a "box" for each level of indentation in an addon via the "Extra Tab Contents API" right before the favico.  For each box, the left border could be formatted with the dashed line and when you aligned everything up, it should look like multiple lines as necessary.

Obviously this is more work than just CSS and the tabs would have to be monitored for changes in indentation and boxes added\removed as necessary.

**Comment by haoadoreorange** [comment]
Hi,
Thanks a lot for the comment. Actually for the problem you mentionned I found a workaround which will de-indent according to a variable set from root.
The real challenge is, for each nested level, I need another line that is indented, that means for level 2 there should be 2 lines, level 3 3 lines and so on, dynamically. I don't see how to make that happens in css, regarding 2 following problems.
1. It seems not possible to do it dynamically, so the only way is to hard code it up to for example 10 levels.
2. Assuming I would hard code it, I don't see how I can make 10 borders, providing limited workarounds with `:before` and `:after`

**Comment by irvinm** [comment]
@haoadoresorange you definitely have a handle of the problem.  I forgot to include a link to the API:  https://github.com/piroor/treestyletab/wiki/Extra-Tab-Contents-API

Also, if you look at the example addon using this API, I could see a situation where you could do what you want via a helper addon but obviously it is a lot more involved.  https://addons.mozilla.org/en-US/firefox/addon/tst-tab-drag-handle/  (Basically, thinking about adding a box before the favico for each level of indentation and format appropriately.

I don't think you can do it via CSS alone.  You can't (I believe) create any new content via CSS, but only modify existing content.

**Comment by haoadoreorange** [comment]
> 
> 
> @haoadoresorange you definitely have a handle of the problem. I forgot to include a link to the API: https://github.com/piroor/treestyletab/wiki/Extra-Tab-Contents-API
> 
> Also, if you look at the example addon using this API, I could see a situation where you could do what you want via a helper addon but obviously it is a lot more involved. https://addons.mozilla.org/en-US/firefox/addon/tst-tab-drag-handle/ (Basically, thinking about adding a box before the favico for each level of indentation and format appropriately.
> 
> I don't think you can do it via CSS alone. You can't (I believe) create any new content via CSS, but only modify existing content.

Yeah after looking around I come to the conclusion that an addon helper shall be the less hacky way to do it. Are you interested ?

**Comment by irvinm** [comment]
Interested?  Kind of.  Capable?  Not really.  I only know enough to be dangerous and maybe be able to modify working code.  Sorry.

**Comment by piroor** [comment]
How about this?:

```css
/* Demonstration of indent line for Proton, left side style */
:root.left tab-item:not(.pinned)::before {
  background: repeating-linear-gradient(
                to right,
                rgba(0, 0, 0, 0) 0px,
                currentcolor 0px,
                currentcolor 1px,
                rgba(0, 0, 0, 0) 1px,
                rgba(0, 0, 0, 0) var(--indent-size)
              );
  bottom: 0;
  content: "";
  left: calc(var(--indent-size) - 1px);
  opacity: 0.45; /* make border color thinner */
  pointer-events: none;
  position: absolute;
  top: 0;
  width: var(--tab-indent);
  z-index: 999999;
}

/* indent via padding instead of margin */
:root.left tab-item:not([data-level="0"]):not(.pinned) {
  margin-left: 0 !important;
  padding-left: var(--tab-indent);
}
:root.left tab-item:not([data-level="0"]):not(.pinned) .background {
  left: var(--tab-indent);
}
```

screenshot:
![image](https://user-images.githubusercontent.com/70062/122668066-5d71e180-d1f1-11eb-9d5f-5beb27bf510b.png)

**Comment by piroor** [comment]
I've added a new snippet: https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#indent-border-like-visual-studio-code-2948

**Comment by irvinm** [comment]
... and if you remove the 1px border from the tab, the lines look continuous.

```
tab-item {
	border: unset;
}
```

![image](https://user-images.githubusercontent.com/979729/122672962-47860180-d19c-11eb-8eb3-a622f64bee28.png)

**Comment by irvinm** [comment]
One last possible change:

Shifting the padding-left offset a little aligns the lines more consistently from the first to the last.

`  padding-left: calc(var(--tab-indent) + 3px); `

![image](https://user-images.githubusercontent.com/979729/122675622-4064f080-d1a8-11eb-8899-6b6d40dd2042.png)

**Comment by haoadoreorange** [comment]
Thanks for the snippet ! Brilliant workaround with the `repeating-linear-gradient`, I didn't even not it exists. 
I notice however that there is a small padding by default on `tab-item`, so maybe to indent via padding, we should use the selector without `:not([data-level="0"])` so that all indentation is uniform.

**Comment by haoadoreorange** [comment]
I also notice that this method makes the underline when drag-to-move one tab to under the target tab disappeared (probably because of `:before` element ?).
Trying to fix it but no success so far, I can't find what the element responsible for that underline.
Any idea ? @piroor @irvinm 
**EDIT**: a simple fix would be to use ::after in the snippet above to avoid clashing with the drop-marker ::before

**Comment by irvinm** [comment]
@piroor I think this can be closed.  We can discuss anything else as needed when it is closed, but doesn't seem to require any TST changes.

**Comment by piroor** [comment]
Currently I still don't use this style, but I agree that sometimes I'm suffered from less detectivity of deeply nested tab level with Proton theme. The mentioned problem around drop position marker is hard to be fixed with current DOM structure, and I need to introduced a new container element inside tab-item.

**Comment by piroor** [comment]
I've introduced a new mid-level element `tab-item-substance` between `tab-item` and in-tab elements, with the commit b8e919b. After the commit you can show the border more safely with following user style:

```css
/* Demonstration of indent line for Proton, left side style */
:root tab-item:not(.pinned):not(.collapsed)::before {
  bottom: 0;
  content: "";
  opacity: 0.25; /* make border color thinner */
  pointer-events: none;
  position: absolute;
  top: 0;
  width: var(--tab-indent);
  z-index: 999999;
}
:root.left tab-item:not(.pinned)::before {
  background: repeating-linear-gradient(
                to right,
                rgba(0, 0, 0, 0) 0px,
                currentcolor 0px,
                currentcolor 1px,
                rgba(0, 0, 0, 0) 1px,
                rgba(0, 0, 0, 0) var(--indent-size)
              );
  left: calc(var(--indent-size) - 1px);
}
:root.right tab-item:not(.pinned)::before {
  background: repeating-linear-gradient(
                to left,
                rgba(0, 0, 0, 0) 0px,
                currentcolor 0px,
                currentcolor 1px,
                rgba(0, 0, 0, 0) 1px,
                rgba(0, 0, 0, 0) var(--indent-size)
              );
  right: calc(var(--indent-size) - 1px);
}
```
