### ISSUE TITLE
The last update skewed the custom styles

### ISSUE THREAD

**Issue by wvxwxvw** [piroor/treestyletab#2958]
The last update skewed the custom styles, the examples in the "Code snippets for custom style rules" do not work correctly. Specifically, the border of the tabs, the indentation of icons and text on the left, the indicator of the active tab, and so on. Photon theme, but largely self-customized.

**Comment by wvxwxvw** [comment]
I couldn't set it up quickly, I rolled back to the previous version. There is no time to spend half a day on configuration through debugging.

**Comment by afgks** [comment]
I'd also like to know how to remove the new grey border and the 2px gaps between tabs. They are very distracting.

Screenshots for comparison:
https://i.imgur.com/BHPaeJx.png
https://i.imgur.com/xWieBIs.png

**Comment by vitidev** [comment]
>I'd also like to know how to remove the new grey border and the 2px gaps between tabs. They are very distracting.

I agree. I also want to remove them 

**upd:** I'm not a css expert, but very distracting - so temp solution until a normal solution appears 

```
tab-item-substance,
.after-tabs button,
.after-tabs [role="button"] {
  border: 0px solid var(--tab-border) !important;
}
```

**Comment by piroor** [comment]
If you paste your user CSS here, someone (include me) may advice where should be updated.

**Comment by DimitryAndric** [comment]
For me the appearance of the tabs changed greatly due to this update, even though I don't have any user styles, except for hiding the top bar:

```
#TabsToolbar, #sidebar-header {
	visibility: collapse !important;
}
```

Before (3.8.4):
![Screenshot 2021-07-06 at 19 44 02](https://user-images.githubusercontent.com/9060368/124644403-86050700-de92-11eb-9082-d5d323cc2f9d.png)

After (3.8.5 or 3.8.6, didn't see any difference between them):
![Screenshot 2021-07-06 at 19 45 59](https://user-images.githubusercontent.com/9060368/124644649-cd8b9300-de92-11eb-8703-38290a25a5c9.png)

E.g. the virtual spacing is *much* wider now.

**Comment by afgks** [comment]
I think it is this that caused the problem:

```
/* Less visible tab dividers. 
   A black border with a very low alpha slightly darkens any color. */
tab-item {
  border: solid 1px #11111150;
}

```

After removing this part of the code, the gaps disappeared, but the tab dividers are still grey. How to change them to black?

**Comment by DimitryAndric** [comment]
> E.g. the virtual spacing is _much_ wider now.

Oops, apologies for that, I *did* have user styles but totally forgot about them (as they're quite deep in the TST settings). These were copied from TST snippets a very long time ago, and seem to have always kept working:

```
/* Show title of unread tabs with italic font */
.tab.unread .label {
  font-style: italic;
}

/* Add private browsing indicator per tab */
.tab.private-browsing .label:before {
  content: "🕶";
}

/* Make tabs smaller */
.tab {
  padding-top: 0px;
  padding-bottom: 0px;
}


/* regular width scrollbar */
#tabbar { scrollbar-width: auto; }

/* put scrollbar rightside */
:root.left #tabbar { direction: ltr; }
```

Are you now supposed to change `.tab` to something like `tab-item.tab-item-substance` ?

**Comment by DimitryAndric** [comment]
Okay, for me the following worked to get the narrower tab spacing:

```
/* Make tabs smaller */
tab-item-substance {
  padding-top: 0px;
  padding-bottom: 0px;
}
```

This made the end result look identical to my 3.8.4 screenshot. It seems the "Show title of unread tabs with italic font" item still works as-is.

**Comment by dotmacro** [comment]
Seemed like the "less visible tab dividers" code snippet was seemingly the main cause of the issue for me too. I fixed it by removing `solid 1px` from that snippet and adding a new snippet to specify tab height. 

```
/* Less visible tab dividers. 
   A black border with a very low alpha slightly darkens any color. */
/* removed `solid 1px` 
	because it made the boarders too thick at 3.8.6 update */
.tab {
  border: #00000012; 
} 

/* tab height */
tab-item {
 --tab-size: 25px !important;
 height: var(--tab-size);
}
```

**Comment by piroor** [comment]
@DimitryAndric Yes it is the answer!

DOM structure on TST 3.8.4 and olders is:

```html
<tab-item id="tab-17"
          data-level="0"
          class="tab discarded private-browsing unread"
          ...>
  <span class="background"></span>
  <tab-twisty class="twisty" role="button"></tab-twisty>
  <tab-favicon class="favicon" src="...">...</tab-favicon>
  <tab-label role="button" class="label" value="New Tab">...</tab-label>
  <tab-counter class="counter">0</tab-counter>
  <tab-sound-button class="sound-button" role="button"></tab-sound-button>
  <tab-closebox class="closebox" role="button" draggable="true"></tab-closebox>
  ...
</tab-item>
```

* Properties `border`, `padding`, and other basic appearances are applied to the `tab-item`.
* Tab states are stored as classes of `tab-item`, so you need to use `tab-item.class1.class2.class3` (equivalent to `.tab.class1.class2.class3`) to specity tabs with states.
* `tab-item > (element type)`` is effective for `tab-twisty`, `tab-label`, and others.

On the other hand, DOM structure on TST 3.8.5 and later is:

```html
<tab-item id="tab-17"
          data-level="0"
          class="tab discarded private-browsing unread"
          ...>
  <span class="extra-items-container indent"></span>
  <tab-item-substance draggable="true">
    <span class="background"></span>
    <tab-twisty class="twisty" role="button"></tab-twisty>
    <tab-favicon class="favicon" src="...">...</tab-favicon>
    <tab-label role="button" class="label" value="New Tab">...</tab-label>
    <tab-counter class="counter">0</tab-counter>
    <tab-sound-button class="sound-button" role="button"></tab-sound-button>
    <tab-closebox class="closebox" role="button" draggable="true"></tab-closebox>
    ...
  </tab-item-substance>
</tab-item>
```

* Properties `border`, `padding`, and other basic appearances are now applied to the `tab-item-substance` instead of `tab-item`.
* But `tab-item-substance` does not inherit classes of `tab-item`, so you still need to use `tab-item.class1.class2.class3` (equivalent to `.tab.class1.class2.class3`) to specify tabs with states.
  * For example: `tab-item.class1.class2.class3 tab-item-substance { (border, background, etc.) }`
* `tab-item > (element type)` is now un-effective for `tab-twisty`, `tab-label`, and others.
  * Instead `tab-item (element type)` or `tab-item > * > (element type)` are effective.

**Comment by afgks** [comment]
> 
> 
> Seemed like the "less visible tab dividers" code snippet was seemingly the main cause of the issue for me too. I fixed it by removing `solid 1px` from that snippet and adding a new snippet to specify tab height.
> 
> ```
> /* Less visible tab dividers. 
>    A black border with a very low alpha slightly darkens any color. */
> /* removed `solid 1px` 
> 	because it made the boarders too thick at 3.8.6 update */
> .tab {
>   border: #00000012; 
> } 
> ```

I can't change the border colour for some reason.

**Comment by piroor** [comment]
For example, `tab-item.unread { (border, color, etc.) }` (equivalent to `.tab.unread { (border, color, etc.) }`) should be updated like `tab-item.unread tab-item-substance { (border, color, etc.) }` (equivalent to `.tab.unread tab-item-substance { (border, color, etc.) }`).

**Comment by piroor** [comment]
@afgks `tab-item-substance { border: #00000012; } ` should work for you.

Edit: I missed the validity of the `border` property. Border-style and border-width are required like:

```css
tab-item-substance {
  border: solid 1px #00000012;
}
```

**Comment by piroor** [comment]
I've updated code snippets for TST 3.8.5 and later.
https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules

**Comment by afgks** [comment]
> 
> 
> @afgks `tab-item-substance { border: #00000012; } ` should work for you.

Hmm, it didn't work. All it did was remove the borders.
![sshot-2021-07-06- 20-16-07](https://user-images.githubusercontent.com/11691936/124654914-12192d80-de97-11eb-8d57-6a41dcece3ba.png)

**Comment by Veyka** [comment]
I've been fiddling with my cobbled together CSS and have hit a wall, some guidence would be appreciated!
The background colour doesnt seem to be working as expected, and there are odd black borders between tabs.

```
:root {
  --colorA: #ecff6b;
  --colorB: #6affda;
  --colorC: #b4b4b4;
  --colorD: #5ceaff;
  --colorE: #514350;
  --colorF: #281f1a;
  --colorG: green;
  --tab-height: 30px;
  --font-size: 12px;
  background-color: var(--colorF);
}

:root.simulate-svg-context-fill .closebox::after {
  background: white;
}

:root.simulate-svg-context-fill .tab.active .closebox::after {
  background: black;
}

:root.simulate-svg-context-fill .tab:hover .closebox::after {
  background: black;
}

:root.simulate-svg-context-fill .tab.active .sound-button::after {
  background: black;
}

:root.simulate-svg-context-fill .tab:hover .sound-button::after {
  background: black;
}

.tab {
  background-color: var(--colorE);
  height: var(--tab-height);
  border-top: none;
  border-right: none;
  border-left: none;
  border-bottom: 2px solid var(--colorF);
}

.label {
  font-size: var(--font-size);
}

.tab .label {
  color: white;
}

.tab.active .label {
  color: black;
}

.tab .counter {
  color: var(--colorD);
}

.tab.active .twisty
{
  color: var(--colorG);
}

.tab.active {
  color: black;
  background-color: var(--colorA);
}

.tab.active:hover {
  background-color: var(--colorA);
}

.tab:hover .label {
  color: black;
}

.tab:hover, .tab:not(.active):hover {
  color: black;
  background-color: var(--colorB);
}

.tab.unread .label {
  font-style: italic;
}

.tab.discarded {
  color: var(--colorC);
  background-color: black;
  border-top: none;
  border-bottom: 1px solid black;
}

/* Change styling of the favicon of pending (unloaded) tabs */
.tab.discarded .favicon {
  opacity: 0.5 !important;
}

.tab.private-browsing .label:before {
  content: "🕶";
}
/*colour scrollbar */
:root.left #tabbar { scrollbar-color: dimgrey black; }

/* Tab Counter on New Tab button */
/* https://github.com/piroor/treestyletab/issues/1661 */

#tabbar {
  counter-reset: tabs;
}
.tab {
  counter-increment: tabs;
}

.newtab-button::before {
  content: counter(tabs) " tabs";
  pointer-events: none;
    
  position: absolute;
  left: 0.2em;

  /* TST 2.4.0 - Fix for Issue #1664 */
  background: transparent !important;
  mask: none !important;
}
/* Slide tab count away from selector */
:root.newtab-action-selectable.contextual-identity-selectable .newtab-button::after {
  transition: margin-left 0.1s;
}
:root.newtab-action-selectable.contextual-identity-selectable .newtab-action-selector-anchor.open ~ .newtab-button::after,
:root.newtab-action-selectable.contextual-identity-selectable .newtab-button-box:hover .newtab-button::after {
  margin-left: 20px;
}
.newtab-button::after {
  opacity: var(--button-opacity);
}
.newtab-button-box:hover .newtab-button::after {
  opacity: .989;
}
```

**Comment by snw-0** [comment]
I use the "Full Auto-show/hide Theme" from the code snippets, with `--thin-tab-width: 2px;` and the following:
`tab-highlighter {
  width: 4px;
}
tab-item.active {
  height: 52px !important;
}`

However, a couple of problems have cropped up since the update:

- My tabs used to be a solid color, but now there's this grey bar on active/hovered tabs, and it does not respect the `height: 52px !important;` on the active tab.
- The `tab-highlighter` does not appear at all.
- There's a weird delay on the animations, where the sidebar slides out and then the labels on indented tabs slide further out (this may have been the case before the update and I just didn't notice, but the other two are new)

Here is a gif showing these problems:
![tab_problem](https://user-images.githubusercontent.com/2808851/124684083-04ae7400-de94-11eb-8569-efad4389153b.gif)

Thanks for any help you can offer!

**Comment by piroor** [comment]
@ontoclasm The highlighter is no longer visible with the "Proton" theme. I think you should use the "Photon" theme. And here is the updated version of your user styles:

```css
.highlighter {
  --tab-highlighter-size: 4px;
}
tab-item.active tab-item-substance {
  height: 52px;
}
```

> There's a weird delay on the animations, where the sidebar slides out and then the labels on indented tabs slide further out (this may have been the case before the update and I just didn't notice, but the other two are new)

Sorry it is uncontrollable via user styles. [The delay depends on a hidden option `collapseDuration` (150 msec by default)](https://github.com/piroor/treestyletab/blob/1957f0bc1795c3e8148eef8b56d7d611a76abbbb/webextensions/sidebar/indent.js#L157), it is changed via TST options => Development => All Configs => collapseDuration.

**Comment by zekeblue** [comment]
I have managed to restore all of the appearance settings except for the sidebar background color.  I had it gray and it is now white.  I would also appreciate the code snippet for this if it is possible to restore.   Thanks.

**Comment by piroor** [comment]
@Veyka I've tried to update your user styles. Please look at updated selectors around `tab-item` and `tab-item-substance` for the [DOM structure on TST 3.8.5 and later](https://github.com/piroor/treestyletab/issues/2958#issuecomment-874987381).

```css
:root {
  --colorA: #ecff6b;
  --colorB: #6affda;
  --colorC: #b4b4b4;
  --colorD: #5ceaff;
  --colorE: #514350;
  --colorF: #281f1a;
  --colorG: green;
  --tab-height: 30px;
  --font-size: 12px;
  background-color: var(--colorF);
}

:root.simulate-svg-context-fill tab-closebox::after {
  background: white;
}

:root.simulate-svg-context-fill tab-item.active tab-closebox::after {
  background: black;
}

:root.simulate-svg-context-fill tab-item tab-item-substance:hover tab-closebox::after {
  background: black;
}

:root.simulate-svg-context-fill tab-item.active tab-sound-button::after {
  background: black;
}

:root.simulate-svg-context-fill tab-item tab-item-substance:hover tab-sound-button::after {
  background: black;
}

tab-item {
  height: var(--tab-height);
}

tab-item-substance {
  background-color: var(--colorE);
  height: var(--tab-height);
  border-top: none;
  border-right: none;
  border-left: none;
  border-bottom: 2px solid var(--colorF);
}

tab-label {
  font-size: var(--font-size);
}

tab-item tab-label {
  color: white;
}

tab-item.active tab-label {
  color: black;
}

tab-item tab-counter {
  color: var(--colorD);
}

tab-item.active tab-twisty
{
  color: var(--colorG);
}

tab-item.active tab-item-substance {
  color: black;
  background-color: var(--colorA);
}

tab-item.active tab-item-substance:hover {
  background-color: var(--colorA);
}

tab-item tab-item-substance:hover tab-label {
  color: black;
}

tab-item tab-item-substance:hover,
tab-item:not(.active) tab-item-substance:hover {
  color: black;
  background-color: var(--colorB);
}

tab-item.unread tab-label {
  font-style: italic;
}

tab-item.discarded tab-item-substance {
  color: var(--colorC);
  background-color: black;
  border-top: none;
  border-bottom: 1px solid black;
}

/* Change styling of the favicon of pending (unloaded) tabs */
tab-item.discarded tab-favicon {
  opacity: 0.5 !important;
}

tab-item.private-browsing tab-label:before {
  content: "🕶";
}
/*colour scrollbar */
:root.left #tabbar { scrollbar-color: dimgrey black; }

/* Tab Counter on New Tab button */
/* https://github.com/piroor/treestyletab/issues/1661 */

#tabbar {
  counter-reset: tabs;
}
tab-item {
  counter-increment: tabs;
}

.newtab-button::before {
  content: counter(tabs) " tabs";
  pointer-events: none;
    
  position: absolute;
  left: 0.2em;

  /* TST 2.4.0 - Fix for Issue #1664 */
  background: transparent !important;
  mask: none !important;
}
/* Slide tab count away from selector */
:root.newtab-action-selectable.contextual-identity-selectable .newtab-button::after {
  transition: margin-left 0.1s;
}
:root.newtab-action-selectable.contextual-identity-selectable .newtab-action-selector-anchor.open ~ .newtab-button::after,
:root.newtab-action-selectable.contextual-identity-selectable .newtab-button-box:hover .newtab-button::after {
  margin-left: 20px;
}
.newtab-button::after {
  opacity: var(--button-opacity);
}
.newtab-button-box:hover .newtab-button::after {
  opacity: .989;
}
```
