### ISSUE TITLE
Why is my styling messed up.

### ISSUE THREAD

**Issue by mzso** [piroor/treestyletab#2967]
I pretty much overrode all colors, but for some reason the changes in 3.8.7 ruins them:

![kép](https://user-images.githubusercontent.com/4479090/125740030-4c4e6be8-5155-4445-89d8-3a45602fe75e.png)
Solid blues and greys coming in instead of what I set in the config. Even the items that retain transparency change (but more subtly).

```css
:root {
  --browser-bg-base: unset;
  --browser-bg-less-lighter: unset;
  --browser-bg-lighter: unset;
  --browser-bg-more-lighter: unset;
  --browser-bg-lightest: unset;
  --browser-bg-less-darker: unset;
  --browser-bg-darker: unset;
  --browser-bg-more-darker: unset;
  --browser-fg: white;
  --browser-fg-active: unset;
  --browser-border: rgb(83, 83, 87);
  --browser-header-url: unset;
  --browser-bg-url: unset;
  --browser-bg-for-header-image: unset;
  --browser-bg-hover-for-header-image: unset;
  --browser-bg-active-for-header-image: unset;
  --browser-textshadow-for-header-image: unset;
  --browser-tab-highlighter: unset;
  --browser-loading-indicator: unset;
  --theme-colors-frame: unset;
  --theme-colors-tab_background_text: unset;
  --theme-images-theme_frame: unset;
}




tab-item {
  background-color: rgba(0,0,0,0.6)
}


tab-item.discarded {
  
  background-color: rgba(0,0,0,0.6);
  opacity: 0.55;
}

tab-item.unread {
  font-style: italic;
  color: rgb(255,0,0);
  
}
tab-item.unread .label-content {
    color: rgb(255,0,0);
  }

tab-item.active {
  /*font-weight: bold;*/
  background-color: rgba(255,255,255,0.5);
  color:black !important;
  
}

 tab-item.active .label-content {
    color: black;
  }

.newtab-button {
  display:none;
}
```

**Comment by piroor** [comment]
How about this?:

```css
:root {
  --browser-bg-base: unset;
  --browser-bg-less-lighter: unset;
  --browser-bg-lighter: unset;
  --browser-bg-more-lighter: unset;
  --browser-bg-lightest: unset;
  --browser-bg-less-darker: unset;
  --browser-bg-darker: unset;
  --browser-bg-more-darker: unset;
  --browser-fg: white;
  --browser-fg-active: unset;
  --browser-border: rgb(83, 83, 87);
  --browser-header-url: unset;
  --browser-bg-url: unset;
  --browser-bg-for-header-image: unset;
  --browser-bg-hover-for-header-image: unset;
  --browser-bg-active-for-header-image: unset;
  --browser-textshadow-for-header-image: unset;
  --browser-tab-highlighter: unset;
  --browser-loading-indicator: unset;
  --theme-colors-frame: unset;
  --theme-colors-tab_background_text: unset;
  --theme-images-theme_frame: unset;
}




tab-item-substance {
  background-color: rgba(0,0,0,0.6)
}


tab-item.discarded tab-item-substance {
  
  background-color: rgba(0,0,0,0.6);
  opacity: 0.55;
}

tab-item.unread {
  font-style: italic;
  color: rgb(255,0,0);
  
}
tab-item.unread .label-content {
    color: rgb(255,0,0);
  }

tab-item.active tab-item-substance {
  /*font-weight: bold;*/
  background-color: rgba(255,255,255,0.5);
  color:black !important;
  
}

 tab-item.active .label-content {
    color: black;
  }

.newtab-button {
  display:none;
}
```

The discussion about user styles for TST 3.8.5 and later may help you, so I recommend you to see that also:
https://github.com/piroor/treestyletab/discussions/2960

**Comment by mzso** [comment]
@piroor 
Thanks. I'll try.

**Comment by mzso** [comment]
@piroor 
So it seems to work fine. What does this new tab item "tab-item-substance" means. I notice that you added it besides "tab-item.active " (without a comma, which is also new to me) instead of changing to something like "tab-item-substance.active ". So I guess the logic behind its usage is a fair bit different.

If I may ask: How do I change (thickness, color) the indicator bar (I don't know the proper name) for hovered tabs? Not really noticeable right now.

**Comment by piroor** [comment]
`tab-item-substance` was introduced to add a new container to put custom elements for the "indent" space. It means a box of visible tab, and now `tab-item` means "a row for a tab". More details: https://github.com/piroor/treestyletab/discussions/2960#discussioncomment-972745 It is required to implement helper extensions like [TST Indent Line](https://addons.mozilla.org/firefox/addon/tst-indent-line/). `tab-item-substance` doesn't inherit classes of `tab-item`, so `tab-item-substance.active` won't affect as you expected. Instead you still need to use `tab-item.active tab-item-substance` (it means "tab-item-substance under a tab-item with active class).

> If I may ask: How do I change (thickness, color) the indicator bar (I don't know the proper name) for hovered tabs? Not really noticeable right now.

Do you mean the blue line? It is internally identified as "highlighter". You can change its size like as:

```css
:root {
  --tab-highlighter-size: 10px;
}
```

I recommend you to inspect the DOM tree of TST's sidebar.
https://github.com/piroor/treestyletab/wiki/How-to-inspect-tree-of-tabs#how-to-inspect-the-sidebar
You'll customize it more and more as you like if you have CSS knowledges.
