### ISSUE TITLE
Dark theme not working on firefox 90

### ISSUE THREAD

**Issue by jayywolff** [piroor/treestyletab#2969]
Here we go again.

Firefox 90.0.1
Arch Linux 5.12.15
TST 3.8.7

Just updated firefox and my side tabs are now burning my eyes with the light theme. Still not sure what changed, digging around to see what happened.

**Comment by jayywolff** [comment]
This snippet to enable a dark gtk theme no longer works. When I remove it from my config, im able to use the stock photon theme in dark. I guess i may have to hardcode the colors as a workaround for now

https://github.com/piroor/treestyletab/blob/5a8569c22feeaedeecde623a86832db7bc0419a2/webextensions/sidebar/styles/photon/photon.css#L49-L76

**Comment by szc126** [comment]
Also Arch + Firefox. I suspect that something has broken in Firefox itself. My custom CSS used system colors, which have apparently become light. I use `widget.non-native-theme.enabled=false` for native GTK widgets, and they have also become light. Strangely, the "System colors" FF theme is still dark.

**Comment by piroor** [comment]
@jayywolff @szc126 Could you attach screenshots describing what is expected and what is actual? I'm not well about Arch Linux environment. I've just setup an Arch Linux environment with XFCE4 but I'm afraid that everything is different from your environment including color scheme.

What I got (and expected) is:
![image](https://user-images.githubusercontent.com/70062/126095840-835c12a8-7e8f-4a2f-9662-dc62e94b1865.png)

**Comment by jayywolff** [comment]
@piroor You should use a dark gtk theme to test this. 
I use [arc-dark gtk theme](https://github.com/horst3180/arc-theme#arc-dark)
It's in the arch repo, so it's easy to install [arc-gtk-theme](https://archlinux.org/packages/community/any/arc-gtk-theme/)

Here's an example of how it looked before Firefox 90. This was a screenshot i saved a few days ago, had to randomize the tabs since I had many open.
![image](https://user-images.githubusercontent.com/16052485/126168422-903cecdd-a9a1-456a-b65c-c784a3602731.png)

Here's how it looks now
![image](https://user-images.githubusercontent.com/16052485/126169674-3d65c9d6-aa1d-40e0-a5eb-113e8fa5c1c9.png)


My styling that's pasted into the extra styles textarea under Addon Manager -> treestyletab -> Preferences ->  Advanced
```css
:root {
  --tab-size: 36px;
}
.tab:not(.pinned) { 
  height: var(--tab-height) !important;
}
.tab:not(:hover) .closebox {
  display:none;
}

/*** 
 * Apply Dark GTK theme in Linux
 * https://github.com/piroor/treestyletab#appearance
 * https://github.com/piroor/treestyletab/blob/5a8569c22feeaedeecde623a86832db7bc0419a2/webextensions/sidebar/styles/photon/photon.css#L49-L76
 * 
 */
:root[color-scheme="system-color"] {
  --tab-surface-regular: var(--browser-bg-for-header-image, var(--browser-bg-base, -moz-dialog));
  --tab-text-regular: var(--browser-fg, -moz-dialogtext);
  --tab-text-inverted: var(--browser-bg-more-lighter, -moz-dialog);
  --tab-text-active: var(--tab-text-regular);
  --tab-text-active-inverted: Highlight;
  --tab-border: var(--browser-border, var(--browser-bg-more-darker, ThreeDShadow));
  --tab-surface-hover: var(--browser-bg-hover-for-header-image, var(--browser-bg-more-lighter, ThreeDHighlight));
  --tab-surface-active: var(--browser-bg-active-for-header-image, var(--face-highlight-more-lighter, Highlight));
  --tab-surface-active-hover: var(--browser-bg-active-for-header-image, var(--face-highlight-more-more-lighter, Highlight));
  --tab-dropmarker: var(--browser-fg, -moz-dialogtext);
  --tabbar-bg: var(--browser-bg-darker, ThreeDShadow);
}
:root[color-scheme="system-color"] #background::after {
  background: var(--browser-bg-darker, AppWorkspace);
  opacity: 0.15;

  bottom: 0;
  content: "";
  left: 0;
  margin: 0;
  overflow: hidden;
  padding: 0;
  position: fixed;
  right: 0;
  top: 0;
  z-index: 20;
}

```

**Comment by happy-dude** [comment]
@jayywolff do you happen to have high contrast turned on in accessibility/display options through system settings?

If this is the case, it's a known/reported bug searchable on bugzilla.

**Comment by jayywolff** [comment]
@Happy-Dude I don't use high contrast

my gtk3 config looks like
```ini
[Settings]
gtk-theme-name=Arc-Dark
gtk-icon-theme-name=Papirus-Dark
gtk-font-name=Hack Nerd Font 13
gtk-cursor-theme-name=capitaine-cursors-light
gtk-cursor-theme-size=0
gtk-toolbar-style=GTK_TOOLBAR_BOTH
gtk-toolbar-icon-size=GTK_ICON_SIZE_SMALL_TOOLBAR
gtk-button-images=1
gtk-menu-images=1
gtk-enable-event-sounds=0
gtk-enable-input-feedback-sounds=0
gtk-xft-antialias=1
gtk-xft-hinting=1
gtk-xft-hintstyle=hintfull
gtk-xft-rgba=rgb
```

**Comment by happy-dude** [comment]
To further narrow it down if it's a Firefox issue or TST issue, does your Addons page also show up as all-white or does it retain the dark styling you expect?

**Comment by jayywolff** [comment]
@Happy-Dude its dark


Also this is how the treestyletab Photon theme looks when I remove that system color snippet from my treestyletab css config 
![image](https://user-images.githubusercontent.com/16052485/126177989-ec01105e-7282-4561-b8d0-2f387b9fffaf.png)

**Comment by wsmwk** [comment]
I'm seeing something similar, but didn't happen to me until I updated (I think) to 91.0b4

>  I suspect that something has broken in Firefox itself.

That's my thought as well. I'm using TST normal sidebar theme, with Mac "**light**" theme.  It's affected more than sidebar - Firefox is seriously messed up. 

<img width="1081" alt="Screen Shot 2021-07-22 at 11 27 20 AM" src="https://user-images.githubusercontent.com/216903/126666366-76f0e842-23c2-4f54-bb12-468de2753b2b.png">

**Comment by wsmwk** [comment]
I haven't figured out which FF bug it might be. I'm not even sure my bug query is good https://mzl.la/3eJZK5v

**Comment by wsmwk** [comment]
Found my issue -[ Bug 1721312 - When using High-Contrast Theme (Mac display > increase contrast), Firefox doesn't show if checkboxes are checked or unchecked.](https://bugzilla.mozilla.org/show_bug.cgi?id=1721312)

**Comment by szc126** [comment]
Firefox "System theme" + TST "no decoration" and no custom CSS.
![a](https://user-images.githubusercontent.com/29127915/127712183-6ca029c0-7fe9-429c-90b8-bc5e3f60ac5d.png)
![b](https://user-images.githubusercontent.com/29127915/127712188-85f6baf5-24c2-4f94-b931-f67b79378cf0.png)

**Comment by piroor** [comment]
https://askubuntu.com/questions/1210859/how-to-make-firefox-look-more-like-the-current-gtk-theme
You looks need to specify the environment variable `GTK_THEME` to apply GTK+ theme to CSS system color. I've tried it on an Arch Linux environment and here are screenshots:

Firefox started via `firefox`:
![image](https://user-images.githubusercontent.com/70062/128148790-eea107e8-ebca-4688-85b8-5d2614825629.png)

Firefox started via `GTK_THEME=Arc-Dark firefox`:
![image](https://user-images.githubusercontent.com/70062/128148840-3e868036-2fd1-4977-9cde-688dc2c29c31.png)

**Comment by piroor** [comment]
Hmm... it is very odd. Firefox looks to respect GTK+ theme color on its chrome (UI of Firefox itself) but does not apply for CSS system colors in content processes including for extensions...

**Comment by jayywolff** [comment]
Yippy, adding `export GTK_THEME="Arc-Dark"` to `~/.profile` and restarting resolves this issue completely. Thank you @piroor 

might be helpful for others to mention this in the faq "How to apply GTK+ theme color on Linux?"

**Comment by piroor** [comment]
@jayywolff Thanks, I added the description to the FAQ topic.

**Comment by lapo-luchini** [comment]
This is on Windows: half the default themes respect dark, half don't:
![image](https://user-images.githubusercontent.com/420454/138827892-34258816-7020-4ce9-be55-b7a9caa8db0e.png)
PS: I'd love the "×" to be activated on hover also in themes other than "Sidecar", would it be possible to control it from a separated option?

**Comment by irvinm** [comment]
@lapo-luchini check the wiki ... there is CSS to hide the "x" unless on hover.

**Comment by lapo-luchini** [comment]
> @lapo-luchini check the wiki ... there is CSS to hide the "x" unless on hover.

[Here](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#only-show-tab-close-button-on-hover-1448), nice, thanks!

**Comment by irvinm** [comment]
@piroor can this be closed?

**Comment by piroor** [comment]
@jayywolff Could you try Firefox 96.0 + TST 3.8.19 without workarounds on Arch? If they work as expected with no workaround, I think this issue can be closed.

**Comment by jayywolff** [comment]
@piroor 

![image](https://user-images.githubusercontent.com/16052485/149552356-9b317e7f-12e0-4777-8eee-3cf3be5d6626.png)

My current setup:
Firefox 96.0
TST 3.8.19 with Photon theme
Arch Linux (running i3wm)
Arc-Dark GTK theme

Still works well with the css workaround suggested a while ago.

In order to get my system dark theme working properly with TST I currently need to:

- add `export GTK_THEME="Arc-Dark"`  in  ~/.profile 
- enable `widget.content.allow-gtk-dark-theme` in firefox about:config
- I run fairly minimal custom css, and the patch in the extra styles section of the TST perferences

```css
:root {
  --tab-size: 36px;
}
.tab:not(.pinned) { 
  height: var(--tab-height) !important;
}
.tab:not(:hover) .closebox {
  display: none;
}

/*** 
 * Apply Dark GTK theme in Linux
 * https://github.com/piroor/treestyletab#appearance
 * https://github.com/piroor/treestyletab/blob/5a8569c22feeaedeecde623a86832db7bc0419a2/webextensions/sidebar/styles/photon/photon.css#L49-L76
 * 
 */
:root[color-scheme="system-color"] {
  --tab-surface-regular: var(--browser-bg-for-header-image, var(--browser-bg-base, -moz-dialog));
  --tab-text-regular: var(--browser-fg, -moz-dialogtext);
  --tab-text-inverted: var(--browser-bg-more-lighter, -moz-dialog);
  --tab-text-active: var(--tab-text-regular);
  --tab-text-active-inverted: Highlight;
  --tab-border: var(--browser-border, var(--browser-bg-more-darker, ThreeDShadow));
  --tab-surface-hover: var(--browser-bg-hover-for-header-image, var(--browser-bg-more-lighter, ThreeDHighlight));
  --tab-surface-active: var(--browser-bg-active-for-header-image, var(--face-highlight-more-lighter, Highlight));
  --tab-surface-active-hover: var(--browser-bg-active-for-header-image, var(--face-highlight-more-more-lighter, Highlight));
  --tab-dropmarker: var(--browser-fg, -moz-dialogtext);
  --tabbar-bg: var(--browser-bg-darker, ThreeDShadow);
}
:root[color-scheme="system-color"] #background::after {
  background: var(--browser-bg-darker, AppWorkspace);
  opacity: 0.15;

  bottom: 0;
  content: "";
  left: 0;
  margin: 0;
  overflow: hidden;
  padding: 0;
  position: fixed;
  right: 0;
  top: 0;
  z-index: 20;
}
```

Haven't had any issues with this setup for several firefox releases.

If I remove the css patch above, it'll use the default Photon theme. If that's set as dark, it'll be dark, but the only way I can use my system gtk dark theme is with that css workaround.
