### ISSUE TITLE
Background of theme "sidebar" does not match FF14b toolbar colours

### ISSUE THREAD

**Issue by FichteFoll** [piroor/treestyletab#307]
Yeah, I updated my FireFox today and it seems that the background color of toolbars has changed. At least of the bookmarks'.

A small

``` css
.treestyletab-tabbar-toolbar[treestyletab-style="sidebar"] .tabbrowser-tabs {
    background-color: #DBEAF9 !important;
}
```

in Stylish fixed it for me. And fortunately this also removed the annoying grayed-out background when the window is not active. You should think about an option to disable that because it really does not match with any other colour in the UI.
