### ISSUE TITLE
How to enable color transition

### ISSUE THREAD

**Issue by FichteFoll** [piroor/treestyletab#310]
I've been experimenting with the sidebar and Stylish lately, but I've come upon a limit, I guess.

I added a background-color for hovered tabs, but I can't manage to apply transition to them. Here is what I have:

``` css
/* Hover colors on tabs */
.treestyletab-tabbar-toolbar[treestyletab-style="sidebar"]
.tabbrowser-tabs[treestyletab-mode="vertical"]
.tabbrowser-tab:not([selected="true"]):hover {
    background: -moz-linear-gradient(center top, hsla(0, 0%, 90%, 1), hsla(0, 0%, 80%, 1)) repeat-x scroll 0 0 transparent !important;
    border-top: 1px solid hsla(0, 0%, 80%, 1) !important;
}

/* TODO: Attempt to animate color changes */
.treestyletab-tabbar-toolbar[treestyletab-style="sidebar"]
.tabbrowser-tabs[treestyletab-animation-enabled="true"][treestyletab-mode="vertical"]
.tabbrowser-tab:not([treestyletab-collapsed-done="true"]) {
    -moz-transition: background-color 0.2s linear !important;
}
```

I know that this is not really an issue with TreeStyleTab but it revolves around it. Maybe someone knows how to solve this.
 [Here](https://gist.github.com/2931591) is the full .css if you are curious; some parts are pretty hacky though.
