### ISSUE TITLE
Tab bar height aren't updated sometimes

### ISSUE THREAD

**Issue by Infocatcher** [piroor/treestyletab#312]
I'm use following userChrome.css style

``` css
.tabs-newtab-button {
    display: none !important;
}
#new-tab-button {
    visibility: visible !important;
}
```

So I have new tab button at bottom of tab bar.
But the same things happens without it (but it less visible).

<ol><li>Open Tools - Web Developer - Inspector:
<br/>
<img src="http://img21.imageshack.us/img21/7488/fxtsttabbarheightbug0.png" alt="Inspector" /></li>
<li>Open new tab:
<br/>
<img src="http://img854.imageshack.us/img854/9291/fxtsttabbarheightbug1.png" alt="New tab" /></li></ol>

Height of internal tab bar part aren't updated.

I think, you can always check height after each TabSelect event.
