### ISSUE TITLE
Default tab color flashes when switching tabs

### ISSUE THREAD

**Issue by myzeiri** [piroor/treestyletab#3120]
## Short description

An odd behavior started when I updated to Firefox v100.0. I override the current tab color to be white. When I switch tabs, the default blue color flashes briefly. See the gif below:

![kAohfiObAf](https://user-images.githubusercontent.com/7775058/167489436-c270bbd9-6872-4ea3-9131-ff7e9bc2e1f5.gif)

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Select the Photon theme.
 4. Add the following CSS to override the selected tab color:

```css
tab-item.active .background {
  background: white !important;
  opacity: 1;
}
```
 5. Click between tabs; note the flashes of the default color.

## Expected result
Default color should not appear at all.

## Actual result
Default color shows briefly on every tab selection.

## Environment

 * Platform (OS): Windows 10
 * Version of Firefox: 100.0
 * Version (or revision) of Tree Style Tab: 3.8.23

**Comment by irvinm** [comment]
Can you try again with JUST your CSS inside of TST?  I tried your sequence with just your CSS and didn't see any problems.  (I'm wondering if there is some other CSS interfering)

**Comment by myzeiri** [comment]
> Can you try again with JUST your CSS inside of TST? I tried your sequence with just your CSS and didn't see any problems. (I'm wondering if there is some other CSS interfering)

Sorry, I should have posted my full CSS. Unfortunately the issue persists with just the original snippet, even after I reset all the configs and and reinstalled the extension.

This is my normal CSS config:
```css
tab-item tab-item-substance:hover {
  background: #ebebeb !important;
  opacity: .9;
}

tab-item.active .background {
  background: white !important;
  opacity: 1;
}

#tabbar tab-item:not(:hover) tab-closebox {
  display: none;
}

:root[data-label-overflow="fade"] tab-item tab-label.overflow {
  mask-image: linear-gradient(to left, transparent 0, rgb(241,1,1) 0.5em);
}
```
These are my exported settings after resetting all configs and adding just the `tab-item.active` snippet:

```json
{
  "chunkedUserStyleRules0": "dGFiLWl0ZW0uYWN0aXZlIC5iYWNrZ3JvdW5kIHsKICBiYWNrZ3JvdW5kOiB3aGl0ZSAhaW1wb3J0YW50OwogIG9wYWNpdHk6IDE7Cn0K",
  "configsVersion": 25,
  "optionsExpandedSections": [
    "section-appearance",
    "section-advanced"
  ],
  "style": "photon",
  "syncDevices": {
    "device-1652143850813-3141": {
      "id": "device-1652143850813-3141",
      "name": "Firefox on Windows",
      "icon": "device-desktop",
      "timestamp": 1652144633268
    },
    "device-1652144830492-46720": {
      "id": "device-1652144830492-46720",
      "name": "Firefox on Windows",
      "icon": "device-desktop",
      "timestamp": 1652144830493
    }
  },
  "userStyleRules": "",
  "userStyleRulesFieldHeight": "120px"
}
```
