### ISSUE TITLE
How to see page url too, besides page title

### ISSUE THREAD

**Issue by ravirathore** [piroor/treestyletab#3246]
Hi,

Is it possible to see the page url too, besides page title? (Not sure, if such option is available now)

## Expected result
Show page url besides or below the title of the page.

## Actual (present) result
Only shows the title of the page.

Thanks for building this extension.

thanks and regards,

**Comment by piroor** [comment]
I've tried it with custom CSS (TST options => Advanced => Extra style rules for contents provided by Tree Style Tab):

```css
tab-item:not(.faviconized)::after {
  bottom: 0;
  content: attr(data-current-uri);
  font-size: 90%;
  left: calc(var(--tab-margin-left) + var(--tab-indent) + (var(--favicon-size) * 2)); /* margin + indent + twisty + favicon */
  opacity: 0.75;
  overflow: hidden;
  pointer-events: none;
  position: absolute;
  right: 0;
  text-align: left;
  text-overflow: "..";
  white-space: pre;
}
```

![image](https://user-images.githubusercontent.com/70062/199784320-7772770f-f18d-4300-a499-def17f0b02f0.png)
