### ISSUE TITLE
[Enhancement] Close tab button in group tab

### ISSUE THREAD

**Issue by Kenqr** [piroor/treestyletab#3267]
If you want to close tabs in a collapsed tree, you need to expand the tree and subtrees first, and then collapse them after, and may accidentally activate unloaded tabs in the process.
Group tabs shows child tab structures and allows users to switch to child tabs with clicking.
It would be helpful if there is also a close tab button for each tab, so you can close tabs in the group without expanding trees.

**Comment by irvinm** [comment]
I like this idea.  Hopefully it could support CSS to only show the "X" on hover as not to clutter the display too much.

**Comment by piroor** [comment]
As the first step: now you can close tabs with middle-click or accel-click on items in group tabs.

**Comment by piroor** [comment]
Closebox is now available for each tree item.

**Comment by piroor** [comment]
Currently closeboxes are shown only when an item is hovered. If you need to see closeboxes always, please set a custom user style:

```css
:root.group-tab .closebox {
  opacity: 1;
}
```

**Comment by Kenqr** [comment]
Thank you.

I noticed that there is no underline on tab names when hover over close button, so I added it with the following style:
``` CSS
:root.group-tab li[id|=tab-item]:hover {
    text-decoration: underline;
}
```
