### ISSUE TITLE
[Enhancement] Customize Group Tab Icon

### ISSUE THREAD

**Issue by zeroarst** [piroor/treestyletab#3280]
## Steps to see the situation

 1. Create a group from bookmarks or TST More Tree Commands extension
 2. Click the created group tab.

## Expected result
Be able to change the group with other icons emoji like 🛒, 🥔..etc, or favicons
Not sure the best to do it. Maybe:
Click folder icon can select to enter a emoji, or select a favicon (favicon.ico).
![image](https://user-images.githubusercontent.com/1834837/211800134-6017e747-95aa-40df-be2f-a805a16117c3.png)

## Actual (present) result
Cannot change the group tab icon.

## Environment

 * Platform (OS): Windows 10.
 * Version of Firefox: 108.0.2 (64-bit) 
 * Version (or revision) of Tree Style Tab: 3.9.12 (2023.1.7):

**Comment by irvinm** [comment]
Just for fun, you could probably do this already via CSS.  Just making a few changes "in-line" I was able to do this.  (Not a great solution, but a workaround)  I think there is a way to differentiate group tabs as well ... maybe based on the "title".  (Ex:  Title = "Shopping" gets the "cart" icon, etc.)

![image](https://user-images.githubusercontent.com/979729/211824199-61f5c3f4-e0f6-4dd3-93a3-560c71135fe4.png)

![image](https://user-images.githubusercontent.com/979729/211824232-57062174-8c9d-4aa6-96fe-4b1928bc5cf0.png)

**Comment by piroor** [comment]
@zeroarst If favicons in the sidebar need to be changed to emoji, you can do that like:

```css
tab-item.group-tab[data-current-uri*="/resources/group-tab.html?title=Shopping"] tab-favicon .favicon-builtin {
  display: none;
}

tab-item.group-tab[data-current-uri*="/resources/group-tab.html?title=Shopping"] tab-favicon::before {
  content: "🛒";
  font-size: 16px;
}
```

I've updated the snippet: https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#change-favicon-for-group-tabs-folder-icon

**Comment by irvinm** [comment]
@piroor from the snippet you added for emojis, can you think of a way to customize the header icon based on the title via CSS? [Using the data-current-uri for the tabs make a lot of sense]  I see on the examples you did for that element that all of them are change "all of them the same" basically just make the changes for all h1:before items on the group-tab pages.

I guess something like:  "For :root.group-tab where "span id title == Shopping" change h1::before ... changes.

![image](https://user-images.githubusercontent.com/979729/211954319-1c2c6871-9ba1-4f23-96f7-94acf5fa9a89.png)

![image](https://user-images.githubusercontent.com/979729/211954335-edb10a31-cb86-45fd-9043-976887665326.png)

**Comment by zeroarst** [comment]
> @zeroarst If favicons in the sidebar need to be changed to emoji, you can do that like:
> 
> ```css
> tab-item.group-tab[data-current-uri*="/resources/group-tab.html?title=Shopping"] tab-favicon .favicon-builtin {
>   display: none;
> }
> 
> tab-item.group-tab[data-current-uri*="/resources/group-tab.html?title=Shopping"] tab-favicon::before {
>   content: "🛒";
>   font-size: 16px;
> }
> ```
> 
> I've updated the snippet: https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#change-favicon-for-group-tabs-folder-icon

Somehow it does not align to center...I tried some css but still could not make it centralized..
![image](https://user-images.githubusercontent.com/1834837/212045670-9e54e361-d6e3-4965-a42a-6a565e3cddb5.png)

**Comment by zeroarst** [comment]
Actually fixed it by 
```css
tab-item.group-tab[data-current-uri*="/resources/group-tab.html?title=Shopping"] tab-favicon::before {
  content: "😀";
  font-size: 15.5px;
  display: flex;
  justify-content: center;
}
```
