### ISSUE TITLE
[Bug] tab widths stuck at specific width

### ISSUE THREAD

**Issue by BorisTheBrave** [piroor/treestyletab#3283]
## Abstract

Visual glitch causes tabs to display incorrectly. See expected vs actual results.

## Steps to reproduce

Unfortunately, I cannot reproduce. A fresh profile works fine.

## Expected result

Tabs stretch entire width of side bar.
![image](https://user-images.githubusercontent.com/183773/212468471-3d716a8a-1d8b-4f2c-8ca8-b71c23faecf7.png)

## Actual result

Tabs are a fixed with, leaving either a gap or truncating depending on width of sidebar.

![image](https://user-images.githubusercontent.com/183773/212468500-c870dfda-55e7-4aee-8f0a-6097dfa75072.png)

![image](https://user-images.githubusercontent.com/183773/212468621-59bb3817-10af-43e9-ab03-1c4a9c436ba3.png)

## Environment

 * Platform (OS): Windows 10 Home 19045.2486
 * Version of Firefox: 108.0.2 (64-bit)
 * Version (or revision) of Tree Style Tab: 3.9.12 (2023.1.7):

## Additional notes

The problem only started a few weeks ago.

I disabled all other extensions in my profile. My userchrome.css is the following:

```css
#TabsToolbar {
    visibility: collapse !important;
}
/*
#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"] #sidebar-header {
  display: none;
}
*/
.bookmark-item[label=""] * {
  font-size: 0 !important
} 
.bookmark-item * {
  padding:0 !important; 
  margin:0 !important;
}
```
