### ISSUE TITLE
[Bug kinda] When making indent line bold it does not work 

### ISSUE THREAD

**Issue by haShinui** [piroor/treestyletab#3343]
## Abstract
Hello I am trying to customize to customize TST. 
So what I want I want is a line in a color that I can decide per level (example, level 1:green, level 2:red, .... ) and I also want it bold. Thats produces 2 problems, when you the `bold 3px` the indent just crashes or doesnt show up. And I cant set a color per leveI, I can set in t general but not level specific. I use this code from your documentation a bit modified.
```:root {

  --custom-indent: 8px;
  --max-visual-indent: 15
}
tab-item {
    --indent-line-color-active: bold 3px blue;
}
tab-item tab-item-substance {
  margin-left: calc(var(--custom-indent) * var(--max-visual-indent)) !important;
}
tab-item[data-level][data-level="0"] tab-item-substance {
  margin-left: 0px !important;
}
tab-item[data-level][data-level="1"] tab-item-substance {
  margin-left: var(--custom-indent) !important;
  --indent-line-color: bold 3px red;
}
tab-item[data-level][data-level="2"] tab-item-substance {
  margin-left: calc(var(--custom-indent) * 2) !important;
  --indent-line-color: bold 3px green;
}```
Also the indent lines placement is a bit random, because I want it all directly under the arrow, but sometimes its on the left or right or directly under it, see video. 
I also show my other design, where I user the border of the tabs, the outer one and the inner highlighted one, the only problem I have is that I cant go deeper then 2 level.
So if I have a level 3 there the outer border is for level 1, that makes a straight line and one for  level 3, but nothing for 2 and that cause the gapes in between which dont look good.
I also tried looking into the indent extension source code but couldn't really.
If you have any idea how to fix one of the issue let me know. I was working on it for hours and will continue

To reproduce just copy the code, I also have a theme on top but I that has not influx at all, tested it thoroughly.

https://github.com/piroor/treestyletab/assets/67230963/0f67f825-0a52-4c45-a7ef-fe3099685e6c



<!--
Please describe how to reproduce your problem on my (developer/author/other peoples') environment.
If your issue is related to tree structure, figures or screenshots will help me a lot, like:


## Expected result
So I expect that I have lines on different level that I can each assign different color and that I can mace the lines thicker and that the line can be position under the arrow.

## Actual result
As show in the window

## Environment

 * Platform (OS): Hyprland, arch
 * Version of Firefox: 113
 * Version (or revision) of Tree Style Tab: 3.9.15, newest just update 21, Mai

**Comment by haShinui** [comment]
I dont know why you cant see more of my post, I just have plain text but here:

Also the indent lines placement is a bit random, because I want it all directly under the arrow, but sometimes its on the left or right or directly under it, see video. 
I also show my other design, where I user the border of the tabs, the outer one and the inner highlighted one, the only problem I have is that I cant go deeper then 2 level.
So if I have a level 3 there the outer border is for level 1, that makes a straight line and one for  level 3, but nothing for 2 and that cause the gapes in between which dont look good.
I also tried looking into the indent extension source code but couldn't really.
If you have any idea how to fix one of the issue let me know. I was working on it for hours and will continue

To reproduce just copy the code, I also have a theme on top but I that has not influx at all, tested it thoroughly.

https://github.com/piroor/treestyletab/assets/67230963/0f67f825-0a52-4c45-a7ef-fe3099685e6c


## Expected result
So I expect that I have lines on different level that I can each assign different color and that I can mace the lines thicker and that the line can be position under the arrow.

## Actual result
As show in the window

## Environment

 * Platform (OS): Hyprland, arch
 * Version of Firefox: 113
 * Version (or revision) of Tree Style Tab: 3.9.15, newest just update 21, Mai

**Comment by haShinui** [comment]
Also the collapsing of tree that are not focused just works **after** you open a new tree (doesnt work when realoading tree parent or child), is it possible that it is activated when you open the browser.
Tested with default theme and settings, expert mode disabeld

**Comment by haShinui** [comment]
So I still could get thickness working.
My question is the ` ::part(%EXTRA_CONTENTS_PART% indent-line)`, I dont under that, I did find the [defenition](https://developer.mozilla.org/en-US/docs/Web/CSS/::part) of `::part` but I still dont understand what it does exactly.
So as far I understand everything in the backgorund.js [file](https://github.com/piroor/tst-indent-line/blob/main/background/background.js). I tried to reassing the values but till now did not work, gonna keep trying.

**Comment by irvinm** [comment]
> EXTRA_CONTENTS_PART

Not a direct answer, but here is some additional information that might help:  https://github.com/piroor/treestyletab/wiki/Extra-Tab-Contents-API#styling-extra-contents

**Comment by piroor** [comment]
I've introduced changes to tst-indent-line to make line width easily customizable, like as:

```css
:root {
  --indent-line-width: 2px;
  --indent-line-width-active: 3px;
}
```

On the other hand, applying different color for each level is hard to do due to the implementation.
Lines are rendered as horizontally repeated gradient, so line color will be applied horizontally instead vertically.
![image](https://github.com/piroor/treestyletab/assets/70062/79a2272a-0e64-4796-bf06-600e949249bb)
To apply colors for each level, you need to define gradient with details like as:

```css

:root {
  --indent-line-width: 1px;
  --indent-line-width-active: 3px;
}

tab-item:not(.pinned):not(.collapsed)
  ::part(extra-contents-by-tst-indent-line_piro_sakura_ne_jp indent-line) {
  --indent-line-left: repeating-linear-gradient(
    to right,

    transparent calc(var(--indent-size) * 0),
    red calc(var(--indent-size) * 0),
    red calc(var(--indent-size) * 0 + var(--indent-line-width)),
    transparent calc(var(--indent-size) * 0 + var(--indent-line-width)),
    transparent calc(var(--indent-size) * 0 + var(--indent-size)),

    transparent calc(var(--indent-size) * 1),
    blue calc(var(--indent-size) * 1),
    blue calc(var(--indent-size) * 1 + var(--indent-line-width)),
    transparent calc(var(--indent-size) * 1 + var(--indent-line-width)),
    transparent calc(var(--indent-size) * 1 + var(--indent-size)),

    transparent calc(var(--indent-size) * 2),
    aqua calc(var(--indent-size) * 2),
    aqua calc(var(--indent-size) * 2 + var(--indent-line-width)),
    transparent calc(var(--indent-size) * 2 + var(--indent-line-width)),
    transparent calc(var(--indent-size) * 2 + var(--indent-size)),

    transparent calc(var(--indent-size) * 3),
    orange calc(var(--indent-size) * 3),
    orange calc(var(--indent-size) * 3 + var(--indent-line-width)),
    transparent calc(var(--indent-size) * 3 + var(--indent-line-width)),
    transparent calc(var(--indent-size) * 3 + var(--indent-size)),

    transparent calc(var(--indent-size) * 4),
    lime calc(var(--indent-size) * 4),
    lime calc(var(--indent-size) * 4 + var(--indent-line-width)),
    transparent calc(var(--indent-size) * 4 + var(--indent-line-width)),
    transparent calc(var(--indent-size) * 4 + var(--indent-size))
  );
}

tab-item:not(.active) {
  --indent-line-color-active: transparent;
}
tab-item[data-level="0"].active ~ tab-item {
  --indent-line-color-active: red;
}
tab-item[data-level="1"].active ~ tab-item {
  --indent-line-color-active: blue;
}
tab-item[data-level="2"].active ~ tab-item {
  --indent-line-color-active: aqua;
}
tab-item[data-level="3"].active ~ tab-item {
  --indent-line-color-active: orange;
}
tab-item[data-level="4"].active ~ tab-item {
  --indent-line-color-active: lime;
}
```
![image](https://github.com/piroor/treestyletab/assets/70062/c8c18d8f-7644-4eac-9256-82ba5ba6e30f)
