### ISSUE TITLE
[Bug] Proton style tab borders lack contrast

### ISSUE THREAD

**Issue by heftig** [piroor/treestyletab#3360]
## Abstract

The borders of Proton style TST tabs look different from the border of tab bar tabs. Notably, they lack contrast.

## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Install https://addons.mozilla.org/en-US/firefox/addon/matte-black-sky-blue/

## Expected result

Style of TST tabs matches style of tab bar tabs.

## Actual result

Borders lack contrast. Upon closer inspection, it seems they use box shadows instead of proper borders or outlines.

![image](https://github.com/piroor/treestyletab/assets/204006/370235cc-9c9e-442d-98a5-707fca60ac01)

## Environment

 * Platform (OS): Arch Linux
 * Version of Firefox: Nightly 117.0a1 (2023-07-10)
 * Version (or revision) of Tree Style Tab: 3.9.15

**Comment by irvinm** [comment]
It is using box shadows.  I did see a way around it by using the following TST CSS until @piroor evaluates it.

```
tab-item.active .background,
tab-item.active tab-item-substance:hover .background,
tab-item.bundled-active .background,
tab-item.bundled-active tab-item-substance:hover .background,
.mutiple-highlighted > tab-item.highlighted .background,
.mutiple-highlighted > tab-item.highlighted tab-item-substance:hover .background {
  border: 1px solid var(--browser-tab-highlighter);
  box-shadow: 0 2px 4px #0000;
}
```

![image](https://github.com/piroor/treestyletab/assets/979729/8a4fee9e-0a5a-4d7c-a41d-2fbb1c4add55)

The original CSS is below and is probably more robust than my solution.

```
tab-item.active .background,
tab-item.active tab-item-substance:hover .background,
tab-item.bundled-active .background,
tab-item.bundled-active tab-item-substance:hover .background,
.mutiple-highlighted > tab-item.highlighted .background,
.mutiple-highlighted > tab-item.highlighted tab-item-substance:hover .background {
  box-shadow: 0 0 0.15em var(--browser-tab-highlighter, var(--tab-active-border-near)),
              0 0 var(--tab-dropshadow-size) var(--browser-tab-highlighter, var(--tab-active-border-far));
}
```

**Comment by heftig** [comment]
Thanks. I inspected the styles of the tab bar and this seems to work well:

```css
tab-item.active .background,
tab-item.active tab-item-substance:hover .background,
tab-item.bundled-active .background,
tab-item.bundled-active tab-item-substance:hover .background,
.mutiple-highlighted > tab-item.highlighted .background,
.mutiple-highlighted > tab-item.highlighted tab-item-substance:hover .background {
  box-shadow: 0 0 4px #0006;
  outline: 1px solid var(--browser-tab-highlighter);
  outline-offset: -1px;
}
```

As far as I can tell the drop shadow is always black.

The only theme that still doesn't look right is the dark variant of Alpenglow, where TST looks like the light variant.
