### ISSUE TITLE
Minor option tweak/addition: Under `Too long label of tabs:`, allow to configure the option `Crop with ".." (better performance)` to `Crop with "[user-chosen string, including empty string]`?

### ISSUE THREAD

**Issue by dwawlyn** [piroor/treestyletab#3370]
Hi, I'm just looking at this option:

```
 Too long label of tabs:
  (RB) Fade out (better visibility)
  (RB) Crop with ".." (better performance)
```

[`(RB)` meaning "Radio Button"]

And for me personally, I want the better performance,
but I find that *most* page titles are too long to fit completely within the tab.

If I could select the string to crop with myself,
for instance changing it from `".."` to just `"|"` or even just the empty string `""`...?

I would find this helpful,
because I think I would already *know* from context when the title is cropped,
without needing any additional visual indication of that,
and it would allow me to read one or two additional characters of the title.

Thank you!

**Comment by irvinm** [comment]
You can remove the ".." if you want by leaving the option set to "crop" and using this CSS:

```
:root:not([data-label-overflow="fade"]) tab-item tab-label {
	text-overflow: unset;
}
```

Or if you want a different delimiter:

```
:root:not([data-label-overflow="fade"]) tab-item tab-label {
	text-overflow: " |";
}
```

![image](https://github.com/piroor/treestyletab/assets/979729/c66ed7e7-bb36-48b9-98a6-459787ca2b75)

**Comment by dwawlyn** [comment]
Thank you!
(
I used:
```css
	:root:not([data-label-overflow="fade"]) tab-item tab-label {
		text-overflow: unset;
	}
```
and it seems to work great.
)


---
btw, is there any practical difference between:
```css
	:root:not([data-label-overflow="fade"]) tab-item tab-label {
		text-overflow: unset;
	}
```
and:
```css
	:root:not([data-label-overflow="fade"]) tab-item tab-label {
		text-overflow: "";
	}
```
?

(
I'm on a rather slow old computer, so performance can be an issue for me.
But if something causes *non-obvious* performance problems (like only under certain conditions),
I might not notice...
)


---
I think I'll leave this "issue" open for now though,
because I still think it *might* make sense to tweak the option itself to include a text-input field for the user to input a short chosen string?
(
ie,
a text-input field replacing the current plain text `".."` in the option `Crop with ".." (Better Performance)`,
with that text-input field simply coming auto-filled with "`..`" by default
)

(That *seems* to me like something that would be probably relatively trivial to implement, but I don't actually know.)
