### ISSUE TITLE
[Enhancement] Allow to tweak layout of the "Expand tree" unfold-button (`>`) and the number of folded children (eg `(3)`) from eg: `> [favicon] Title here..(3)` to eg: `>(3) [favicon] Title here..`

### ISSUE THREAD

**Issue by dwawlyn** [piroor/treestyletab#3371]
When a tab has its children folded,
it looks like, for example with 3 children:
`> [favicon image] Title, cropped or faded if too long..(3)`

Would it be possible to allow the option to re-configure that to something more like:
`>(3) [favicon image] Title, cropped or faded if too long..`
?

Personally, I would find this more visible and easier to read.

---
Additionally, could the entire `>(3)` part at the beginning serve as the clickable area to un-fold the children?
(ie rather than just the `>` being clickable.)
[edit: I note this is actually called the "Expand tree" button in the on-hover tooltip.]

This would be a larger, easier target to click on,
and it would also mean the user would automatically be aware how many tabs would be unfolded whenever they looked at the button to unfold them.

---
(
Personally, I think such a tweak might even be a better default,
but of course one should err on the side of not disturbing existing users with sudden changes to the default,
so I'm only suggesting this tweak as a new, additional option that the user could choose.
)

Thank you!

**Comment by irvinm** [comment]
It is easy enough to move the counter over by the twisty with:

```
:root.left tab-item tab-counter {
  order: -1;
}
```
![image](https://github.com/piroor/treestyletab/assets/979729/e1e9136d-f181-450a-af60-6ee33d695679)

I probably have some other padding\margin CSS causing the alignment issues above.

However, I am not sure via CSS if it is possible to do what you want for the "> (3)" to all be clickable.  @piroor will need to chime in on that.

**Comment by dwawlyn** [comment]
Cool, thank you!

btw, where/what/how should I have looked to find the documentation for this sort of thing?
(
I'm wondering if there's a simple way to tweak the spacing with just CSS too...

ie,
not this:
`> (3)[favicon] foo`
but this:
`>(3) [favicon] foo`
)

**Comment by piroor** [comment]
For example:

```css
:root.left tab-item tab-counter {
  order: -1;
  margin-left: -5px;
  margin-right: 5px;
}
```

**Comment by piroor** [comment]
Anyway this can be done with user stylesheet so I won't add any specific option for it.
Please see the FAQ topic: https://github.com/piroor/treestyletab#user-content-feature-requests-add-more-minor-trivial-options

**Comment by dwawlyn** [comment]
@piroor Thank you!

But about the other part,
*is* it possible using CSS to make the "(3)" part be included as part of the clickable-area to do the unfold?

Or like, to use CSS to customize the appearance/positioning of the fold/unfold clickable-area/button ("twisty" apparently is the term?) in general?

Could you maybe point me to the place/terms in the documentation I should be looking at to learn about that kind of thing?

**Comment by piroor** [comment]
>  is it possible using CSS to make the "(3)" part be included as part of the clickable-area to do the unfold?

For example:

```css
:root.left tab-item tab-counter {
  order: -1;
  margin-left: -5px;
  margin-right: 5px;
}

:root.left tab-item tab-twisty,
:root.left tab-item.subtree-collapsed tab-twisty {
  transform: none;
  margin-right: -10px;
  min-width: calc(var(--favicon-size) + 10px);
}

:root.left tab-item tab-twisty::before {
  transform: rotatez(0deg);
}
:root.left tab-item.subtree-collapsed tab-twisty::before {
  transition: transform 0.2s ease-out, opacity 0.15s ease-out;
  transform: rotatez(-90deg);
}
```

> Could you maybe point me to the place/terms in the documentation I should be looking at to learn about that kind of thing?

Sorry there is no concrete document about that. You need to study CSS and inspect the live DOM tree of TST's sidebar. There are some hints:
https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#for-version-20-and-later
https://github.com/piroor/treestyletab/wiki/How-to-inspect-tree-of-tabs#how-to-inspect-the-sidebar
