### ISSUE TITLE
[Bug] Sidebar menupopup lose background-color in FF version 119

### ISSUE THREAD

**Issue by rainbowflesh** [piroor/treestyletab#3392]
## Steps to reproduce

 1. Start Firefox with clean profile.
 2. Install TST.
 3. Enable `toolkit.legacyUserProfileCustomizations.stylesheets` in `about:config`
 4. add to Profile Root Directory/chrome/userChrome.css
    ```css
    .menupopup-arrowscrollbox {
        background: var(--arrowpanel-background) !important;
      }
    ```
 5. right click on sidebar, done.

## Expected result
menupopup show with background color.

## Actual result
background color gone, only transparency.

## Environment

 * Platform (OS): Linux GTK, QT; Windows NT 10
 * Version of Firefox: 119.0b3 (64-bit)
 * Version (or revision) of Tree Style Tab: Version 3.9.17
