### ISSUE TITLE
[Bug] Tab overlaps each other at reduced heights

### ISSUE THREAD

**Issue by azhongzl** [piroor/treestyletab#3480]
## Abstract
When using the Photon profile at small tab heights, one tab overlaps on each other.
<img width="194" alt="SCR-20240312-jvre-2" src="https://github.com/piroor/treestyletab/assets/22796369/df3da47b-7cb8-4385-9bdb-ab396d73cf73">

## Steps to reproduce
 1. Start Firefox with clean profile.
 2. Install TST.
 3. Reduce tab height and enable hovered tab in user styles
```
/* Change tab height */
tab-item {
  --tab-size: 18px !important;
}
tab-item  tab-item-substance {
  height: var(--tab-size);
}

/* This makes the hovered tab noticeable by modifying the color and font */
tab-item tab-item-substance:hover {
  background: #aaaaaa !important;
  opacity: 1;
}
```
 4. Open 3 tabs, and click the 2nd one
 5. We can see the active tab overlaps the previous and next tab
 6. Hover on the 3rd tab, we can see it overlaps the 2nd tab

## Expected result
1. Active tab should not overlap other tabs
2. Hovered tab should not overlap other tabs

## Actual result
1. Active tab overlaps other tabs
2. Hovered tab overlaps other tabs

## Environment

 * Platform (OS): MacOS
 * Version of Firefox: 123.0.1 (64-bit)
 * Version (or revision) of Tree Style Tab: 4.0.1

**Comment by piroor** [comment]
You need to do more:

```css
/* Change tab height */
tab-item {
  --tab-size: 18px !important;
}
tab-item  tab-item-substance {
  max-height: var(--tab-size) !important;
  min-height: var(--tab-size) !important; /* added */
  padding-top: 0 !important; /* added */
  padding-bottom: 0 !important; /* added */
}

/* This makes the hovered tab noticeable by modifying the color and font */
tab-item tab-item-substance:hover {
  background: #aaaaaa !important;
  opacity: 1;
}
```
