### ISSUE TITLE
[Bug] Custom style for scrollbar now not completely working

### ISSUE THREAD

**Issue by dsl101** [piroor/treestyletab#3500]
## Abstract
Customising the scrollbar color in v4 not working / not documented

## Steps to reproduce

I've had this snippet in Custom Styles since v4, to fix the slightly borked scrollbar, and it's been working well:
```css
#normal-tabs-container {
  direction: ltr; /* Right side */
  scrollbar-width: thin; /* Style */
  scrollbar-color: #ccc #eee; /* Colour */
}
```
I see there have been some recent changes to make the width setting irrelevant now, so I've removed that, but the colour setting in my custom style snippet is ignored. Looking at [this commit](https://github.com/piroor/treestyletab/commit/82359fb83c5f1017f565f9822d4383ba59207772), it seems a more specific CSS selector is required now:
```css
#tabbar:not(.scrollbar-autohide) #normal-tabs-container {
  direction: ltr; /* Right side */
  scrollbar-color: #ccc #eee; /* Colour */
}
```

Is that just the way things are supposed to work now? Or should the basic `#normal-tabs-container` be enough, since it does fix direction and width?

Related, and always a bane of any fast-changing software, [this page](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#scrollbar) is outdated and confusing, and once v4 settles likely needs an overhaul. If keeping info for v3 is required, it probably needs 2 separate sections. Or removing the v3 stuff and just aligning around the new v4 settings. I'd be happy to have a go, but not sure I really understand enough about how it's supposed to work just yet...
