### ISSUE TITLE
Tab counter is broken in latest update

### ISSUE THREAD

**Issue by HighCommander4** [piroor/treestyletab#3540]
## Steps to reproduce

 1. Update to today's TST version (4.0.14)
 2. Use the steps at https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#tab-numbering-and-counting to show a tab count, for example:

```css
#tabbar {
  counter-reset: vtabs atabs tabs;
  /* vtabs tracks visible tabs, atabs tracks active tabs, tabs tracks all tabs */
}
tab-item:not(.collapsed):not(.discarded) {
  counter-increment: vtabs atabs tabs;
}
tab-item:not(.collapsed) {
  counter-increment: vtabs tabs;
}
tab-item:not(.discarded) {
  counter-increment: atabs tabs;
}
tab-item {
  counter-increment: tabs;
}

:root.simulate-svg-context-fill .newtab-button::after {
  content: var(--tab-count-text);
  pointer-events: none;
    
  width: 100%;
  /* TST 2.4.0 - Fix for Issue #1664 */
  background: transparent !important;
  mask: none !important;
}

.newtab-button {
  --tab-count-text: counter(tabs) " tabs";
}
```

## Expected result

Total tab count is shown in the new tab button.

## Actual result

A smaller number is shown, and it changes as you scroll.

## Environment

 * Platform (OS): Linux
 * Version of Firefox: 115.10.0esr
 * Version (or revision) of Tree Style Tab: 4.0.14

---

I assume the CSS needs to be updated to reflect a change in the add-on, but I'm not sure what the update should be.
