### ISSUE TITLE
[Bug] "Grouping tabs with spaces" snippet crops tab list

### ISSUE THREAD

**Issue by TheFou** [piroor/treestyletab#3592]
I was trying some CSS to customize appearance.
However, [this code snippet](https://github.com/piroor/treestyletab/wiki/Code-snippets-for-custom-style-rules#grouping-tabs-with-spaces-instead-of-indented-tree-2777) induces a bug where the tabs list in TST is cropped at the end.
The more space I use, the more tabs are cropped in TST.
I tried messing with other parameters, and even removing everything in the CSS except from this snippet, and I got the same issue as soon as I enable this snippet.
I tried closing / re-opening the sidebar, and even quitting / relaunching Firefox after applying, still the same.
I have around 2000 tabs, in many groups via "Simple Groups" extension.
The group I was testing on has ~270 opened tabs.
I should mention, all tabs appear correctly in the real tab bar at the top.

Here are some screenshots, with exactly the same tabs opened.
The second one with spaces uses `margin-top: calc(var(--tab-size) / 5);` so that you can see what's missing relative to the "normal" one.

![image](https://github.com/user-attachments/assets/dfc24644-9416-4fe0-9b6e-7b8fc39ac4ff)

![image](https://github.com/user-attachments/assets/3b83d91f-9c98-41c6-9fe6-dfe8c7f415f9)

 * Platform (OS): macOS Ventura 13.6.7 (22G720)
 * Version of Firefox: 128.0
 * Version (or revision) of Tree Style Tab: 4.0.20

Thanks for your help.
Regards.

**Comment by piroor** [comment]
Hmm... sadly the CSS hack is unfriendly to the virtual scrolling architecture of TST 4.0 and later. TST 4.0's virtual scrolling assumes that all tabs have same height and zero vertical margins (except negative margin for collapsed tabs), so virtually scrolled tabs are cut off for margins added by your user stylesheets - it is unavoidable. We may need to implement something new API to register extra margins for tabs and implement a new helper addon which uses the API, instead of the CSS hack.

**Comment by piroor** [comment]
I'm afraid that such a new API may make virtual scrolling calculations more slow. Does anyone have something solution idea?

**Comment by TheFou** [comment]
Thanks for considering the issue.
I can't help unfortunately, I'm a simple user... Hope you'll figure something out.
Regards.

**Comment by irvinm** [comment]
@piroor want to move this over to the discussions as this is CSS related?  (I did try playing around and thinking about how to solve this and couldn't come up with anything ... I use spacing between my tabs too, but uniformly across all tabs, not just at the root level)

**Comment by piroor** [comment]
I have an idea based on blank tabs just for separators, like following:

* Tab A
  * Tab A-1
  * Tab A-2
* Blank tab for the separator
* Tab B
  * Tab B-1
  * Tab B-2
* Blank tab for the separator
* Tab C

Something helper addon maintaining such blank tabs for separators between (before) top level tabs and hiding them by CSS may provide the "grouping tabs with spaces" feature virtually. There are some restrictions: the size of spaces for grouping will be same to the height of a tab always, and the space between groups will be clickable unexpectedly so we need to do something for such click events.

**Comment by irvinm** [comment]
A helper addon I think could certainly facilitate all of this ... within the limitations you mentioned.
- I would guess the "spacing being the same size as a tab" might be a deal breaker for some ... big gap. :)

The addon could:

- Monitor/evaluate each "root" tab and insert/ensure a spacer tab above it
- It could add a "state" to those spacer tabs via TST that could be acted upon by CSS
- CSS could then style all the elements to match the background of the sidebar
- CSS could disable "pointer events" for all of the elements as well (this is the one I am least confident it for all elements)

Additionally, couldn't you really do this manually with some CSS?

- Create a tab to be used as a spacer (Just need something unique about this tab for CSS)
- CSS could then style all the elements to match the background of the sidebar
- CSS could disable "pointer events" for all of the elements as well (this is the one I am least confident in)
- Would need to enable pointer events if need to duplicate the tab and move to another location
- Maybe too much work for the return for the manual process?

Either way, not sure there is anything more to do on the TST side. :)

**Comment by seaflown** [comment]
(You can skip the next, quoted part)

> I read @piroor's comment that the virtual scroller:
> 1. Assumes tabs have the same height, and
> 2. Disregards margins.
> 
> After some messing around, I saw that padding decreases tab height to create extra space.
> 
> So, my initial plan was:
>  - add to the tab height
>  - add padding, that removes the extra tab height and which creates space
>  - use negative margins to remove the space from padding, except in the desired regions
> 
> (Which should result in:
>  - the virtual scroller expecting every tab to be bigger than it is, and giving extra scroll space
>  - while in the meanwhile, the padding has reduced the tabs back to normal size and created space,
>  - and the margins have gotten rid of the padding space where it's not desired
> 
> But...

When I was typing the CSS, I didn't actually increase tab size, and it seems to work fine. (with the extra scroll space at the end, as expected...) Maybe the virtual scrolling architecture is accounting for the padding, actually?

```CSS
/* remove padding between top-level tabs, and remove an extra 1px to overlap the repeated borders between them */
tab-item[data-level="0"] + tab-item[data-level="0"] {
  margin-top: -12.33px;
}

/* remove padding between tabs that that aren't top-level, and an extra 1px... */
tab-item:not([data-level="0"]) + tab-item:not([data-level="0"]) {
  margin-top: -12.33px;
}

/* remove padding between parent (top-level) tabs and their first child (not top-level) tab, and an extra 1px... */
tab-item[data-level="0"] + tab-item:not([data-level="0"]) {
  margin-top: -12.33px;
}

/* add padding everywhere else (so there's space between the last child of a tree and the parent of the next) */
tab-item {
  padding-top: 11.33px;
}
```
11.33 px (adjust as necessary) represents what I think is `calc(var(--tab-size / 3)`, but when I tried using it verbatim, my solution fell apart. This creates some extra scroll space / blank space at the end of the tab list, but that's okay with me. 

This also causes drag and drop to no longer work to indent tabs, which is due to not using `--tab-margin-top,` I suspect. However, I'm not sure how `--tab-margin-top` behaves, and there's no equivalent `--tab-padding-top` as far as I am aware.
