### ISSUE TITLE
[Bug] (On Firefox Restore Trees are flattened)

### ISSUE THREAD

**Issue by SilentGlasses** [piroor/treestyletab#3693]
## Abstract
I had to reboot my Macbook after an update recently and upon re-launching Firefox with TST and all my tabs trees were flattened out. It did restore all my tabs just not in trees like I had them.
## Steps to reproduce

 1. I don't know how to reproduce this issue as it's the first time it's happened to me and I have many bookmarks that I was researching with for work that were set under trees for organization by topics/subtopics.

As noted above, not sure how to reproduce but, my tabs should have been restored as:
```
A
\- 1 (collapsed)
\- 2 (collapsed)
\- 3 (collapsed)
\- 4 (collapsed)
B
\- 1 (collapsed)
\- 2 (collapsed)
\- 3 (collapsed)
\- 4 (collapsed)
```

But they were restored as:
```
A
1
2
3
4
B
1
2
3
4
```

## Expected result

Trees should remain indented on restore.

I did pull up the `/background/background.html` info in the `about:debugging` window from where I ran this code provided in GH-3276

```
browser.tabs.query({}).then(async tabs => {
  return await Promise.all(tabs.map(async tab => { return `---${tab.windowId}-${tab.id}---
id: ${(await browser.sessions.getTabValue(tab.id, 'data-persistent-id')).id}
  ancestors: ${await browser.sessions.getTabValue(tab.id, 'ancestors') || ''}
  children:  ${await browser.sessions.getTabValue(tab.id, 'children') || ''}` }…
Promise { <state>: "pending" }
```

I'll post the output as a comment to avoid making the post itself super long. When grabbing this portion of the info, do you need me to expand all the child blocks or just copy the actual output in collapsed mode?

The initial output is:

```
Promise { <state>: "pending" }

---3-5---
id: tab-hoary-salamander-1722546969859-566
  ancestors: 
  children:  tab-warty-lynx-1707942167031-351,tab-oneiric-vervet-1707942600292-50,tab-xenial-meerkat-1707941999972-737,tab-edgy-vervet-1707944444367-867,tab-agile-meerkat-1707941883504-231,tab-yakkety-ocelot-1707941879901-839,tab-karmic-pangolin-1707941742262-589,tab-jaunty-werwolf-1707941344573-22,tab-vivid-zapus-1718984137479-113,tab-zesty-alpaca-1707941862804-727,tab-jaunty-narwhal-1707944039246-747,tab-agile-unicorn-1707941887520-917,tab-warty-xerus-1707941906077-402,tab-hoary-ocelot-1712589049569-116,tab-breezy-meerkat-1718983955737-537,tab-raring-jackalope-1708445294884-613,tab-marveric-meerkat-1707941893478-150,tab-agile-pangolin-1707941922959-356,tab-zesty-narwhal-1707941655084-500,tab-oneiric-tahr-1707941870786-242,tab-marveric-lynx-1707941867187-97,tab-cheerful-ringtail-1713546809410-706,tab-marveric-lynx-1709565906869-1,tab-jaunty-pangolin-1710961117486-861,tab-feisty-ibis-1731519677441-622
---3-6---
id: tab-…
```

## Actual result

Not sure how a screenshot would help here because the trees are just flattened.

## Environment

 * Platform (OS): macOS Sequoia 15.2 arm64
 * Version of Firefox: 133.0.3
 * Version (or revision) of Tree Style Tab: 4.0.25

Please let me know if you need more info and I'll be happy to provide more as I can.

**Comment by SilentGlasses** [comment]
If I expand the bottom portion of the message I see this:

```
---3-5---
id: tab-hoary-salamander-1722546969859-566
  ancestors: 
  children:  tab-warty-lynx-1707942167031-351,tab-oneiric-vervet-1707942600292-50,tab-xenial-meerkat-1707941999972-737,tab-edgy-vervet-1707944444367-867,tab-agile-meerkat-1707941883504-231,tab-yakkety-ocelot-1707941879901-839,tab-karmic-pangolin-1707941742262-589,tab-jaunty-werwolf-1707941344573-22,tab-vivid-zapus-1718984137479-113,tab-zesty-alpaca-1707941862804-727,tab-jaunty-narwhal-1707944039246-747,tab-agile-unicorn-1707941887520-917,tab-warty-xerus-1707941906077-402,tab-hoary-ocelot-1712589049569-116,tab-breezy-meerkat-1718983955737-537,tab-raring-jackalope-1708445294884-613,tab-marveric-meerkat-1707941893478-150,tab-agile-pangolin-1707941922959-356,tab-zesty-narwhal-1707941655084-500,tab-oneiric-tahr-1707941870786-242,tab-marveric-lynx-1707941867187-97,tab-cheerful-ringtail-1713546809410-706,tab-marveric-lynx-1709565906869-1,tab-jaunty-pangolin-1710961117486-861,tab-feisty-ibis-1731519677441-622
---3-6---
id: tab-warty-lynx-1707942167031-351
  ancestors: tab-hoary-salamander-1722546969859-566
  children:  
---3-7---
id: tab-oneiric-vervet-1707942600292-50
  ancestors: tab-hoary-salamander-1722546969859-566
  children:  
---3-8---
id: tab-xenial-meerkat-1707941999972-737
  ancestors: tab-hoary-salamander-1722546969859-566
  children:  tab-breezy-alpaca-1722546940226-534
---3-9---
id: tab-edgy-vervet-1707944444367-867
  ancestors: tab-hoary-salamander-1722546969859-566
  children:  
---3-10---
id: tab-agile-meerkat-1707941883504-231
  ancestors: tab-hoary-salamander-1722546969859-566
  children:  
---3-11---
id: tab-yakkety-ocelot-1707941879901-839
  ancestors: tab-hoary-salamander-1722546969859-566
  children:  
---3-12---
id: tab-karmic-pangolin-1707941742262-589
  ancestors: tab-hoary-salamander-1722546969859-566
  children:  
---3-13---
id: tab-jaunty-werwolf-1707941344573-22
  ancestors: tab-hoary-salamander-1722546969859-566
  children:  
---3-14---
id: tab-vivid-zapus-1718984137479-113
  ancestors: tab-hoary-salamander-1722546969859-566
  children:  
---3-15---
id: tab-zesty-alpaca-1707941862804-727
  ancestors: tab-hoary-salamander-1722546969859-566
  children:  
---3-16---
id: tab-jaunty-narwhal-1707944039246-747
  ancestors: tab-hoary-salamander-1722546969859-566
  children:  
---3-17---
id: tab-agile-unicorn-1707941887520-917
  ancestors: tab-hoary-salamander-1722546969859-566
  children:  
---3-18---
id: tab-warty-xerus-1707941906077-402
  ancestors: tab-hoary-salamander-1722546969859-566
  children:  
---3-19---
id: tab-hoary-ocelot-1712589049569-116
  ancestors: tab-hoary-salamander-1722546969859-566
  children:  tab-agile-drake-1722546985397-383,tab-edgy-zapus-1720807316065-598
---3-20---
id: tab-agile-drake-1722546985397-383
  ancestors: tab-hoary-ocelot-1712589049569-116,tab-hoary-salamander-1722546969859-566
  children:  
---3-21---
id: tab-edgy-zapus-1720807316065-598
  ancestors: tab-hoary-ocelot-1712589049569-116,tab-hoary-salamander-1722546969859-566
  children:  
---3-22---
id: tab-breezy-meerkat-1718983955737-537
  ancestors: tab-hoary-salamander-1722546969859-566
  children:  tab-marveric-vervet-1707941745619-878,tab-vivid-lynx-1720466479637-262,tab-precise-drake-1718983946050-47,tab-yakkety-xerus-1707944048352-374
---3-23---
id: tab-marveric-vervet-1707941745619-878
  ancestors: tab-breezy-meerkat-1718983955737-537,tab-hoary-salamander-1722546969859-566
  children:  
---3-24---
id: tab-vivid-lynx-1720466479637-262
  ancestors: tab-breezy-meerkat-1718983955737-537,tab-hoary-salamander-1722546969859-566
  children:  
---3-25---
id: tab-precise-drake-1718983946050-47
  ancestors: tab-breezy-meerkat-1718983955737-537,tab-hoary-salamander-1722546969859-566
  children:  tab-breezy-meerkat-1718983955737-537,tab-intrepid-yak-1720467479770-488
---3-26---
id: tab-yakkety-xerus-1707944048352-374
  ancestors: tab-breezy-meerkat-1718983955737-537,tab-hoary-salamander-1722546969859-566
  children:  
---3-27---
id: tab-raring-jackalope-1708445294884-613
  ancestors: tab-hoary-salamander-1722546969859-566
  children:  
---3-28---
id: tab-marveric-meerkat-1707941893478-150
  ancestors: tab-hoary-salamander-1722546969859-566
  children:  
---3-29---
id: tab-agile-pangolin-1707941922959-356
  ancestors: tab-hoary-salamander-1722546969859-566
  children:  
---3-30---
id: tab-zesty-narwhal-1707941655084-500
  ancestors: tab-hoary-salamander-1722546969859-566
  children:  
---3-31---
id: tab-oneiric-tahr-1707941870786-242
  ancestors: tab-hoary-salamander-1722546969859-566
  children:  
---3-32---
id: tab-marveric-lynx-1707941867187-97
  ancestors: tab-hoary-salamander-1722546969859-566
  children:  
---3-33---
id: tab-cheerful-ringtail-1713546809410-706
  ancestors: tab-hoary-salamander-1722546969859-566
  children:  
---3-34---
id: tab-marveric-lynx-1709565906869-1
  ancestors: tab-hoary-salamander-1722546969859-566
  children:  
---3-35---
id: tab-jaunty-pangolin-1710961117486-861
  ancestors: tab-hoary-salamander-1722546969859-566
  children:  
---3-36---
id: tab-feisty-ibis-1731519677441-622
  ancestors: tab-hoary-salamander-1722546969859-566
  children:  
---3-37---
id: tab-warty-salamander-1710342995643-743
  ancestors: 
  children:  tab-precise-werwolf-1715993225282-444,tab-gutsy-xerus-1715992576455-902
---3-38---
id: tab-precise-werwolf-1715993225282-444
  ancestors: tab-warty-salamander-1710342995643-743
  children:  tab-gutsy-xerus-1715992576455-902
---3-39---
id: tab-gutsy-xerus-1715992576455-902
  ancestors: tab-warty-salamander-1710342995643-743
  children:  
---3-40---
id: tab-raring-eft-1733328067167-903
  ancestors: 
  children:  tab-zesty-eft-1733328076680-191,tab-agile-badger-1733328078852-35,tab-quantal-cat-1733328080950-438,tab-hoary-pangolin-1733761945044-431,tab-natty-narwhal-1733761951168-647,tab-dapper-heron-1733860052122-4,tab-gutsy-quetzal-1733860083528-113,tab-natty-gibbon-1733860427043-495,tab-oneiric-lynx-1733860441886-872,tab-yakkety-cat-1733860121972-775,tab-xenial-unicorn-1733860224143-72
---3-41---
id: tab-zesty-eft-1733328076680-191
  ancestors: tab-raring-eft-1733328067167-903
  children:  
---3-42---
id: tab-agile-badger-1733328078852-35
  ancestors: tab-raring-eft-1733328067167-903
  children:  
---3-43---
id: tab-quantal-cat-1733328080950-438
  ancestors: tab-raring-eft-1733328067167-903
  children:  
---3-44---
id: tab-hoary-pangolin-1733761945044-431
  ancestors: tab-raring-eft-1733328067167-903
  children:  
---3-45---
id: tab-natty-narwhal-1733761951168-647
  ancestors: tab-raring-eft-1733328067167-903
  children:  tab-dapper-heron-1733860052122-4
---3-46---
id: tab-dapper-heron-1733860052122-4
  ancestors: tab-raring-eft-1733328067167-903
  children:  tab-gutsy-quetzal-1733860083528-113,tab-yakkety-cat-1733860121972-775
---3-47---
id: tab-gutsy-quetzal-1733860083528-113
  ancestors: tab-raring-eft-1733328067167-903
  children:  tab-natty-gibbon-1733860427043-495
---3-48---
id: tab-natty-gibbon-1733860427043-495
  ancestors: tab-raring-eft-1733328067167-903
  children:  tab-oneiric-lynx-1733860441886-872
---3-49---
id: tab-oneiric-lynx-1733860441886-872
  ancestors: tab-raring-eft-1733328067167-903
  children:  
---3-50---
id: tab-yakkety-cat-1733860121972-775
  ancestors: tab-raring-eft-1733328067167-903
  children:  tab-xenial-unicorn-1733860224143-72
---3-51---
id: tab-xenial-unicorn-1733860224143-72
  ancestors: tab-raring-eft-1733328067167-903
  children:  
---3-52---
id: tab-intrepid-xerus-1733328581909-118
  ancestors: 
  children:  
---3-53---
id: tab-oneiric-vervet-1734120579656-682
  ancestors: 
  children:  tab-dapper-jackalope-1734121169075-901,tab-utopic-drake-1734121341228-537,tab-warty-eft-1734121419498-124,tab-edgy-yak-1734121869379-523,tab-intrepid-ocelot-1734121888687-304,tab-zesty-tahr-1736184123663-162,tab-lucid-heron-1736184206393-110,tab-jaunty-eft-1736184296168-230,tab-intrepid-heron-1736184340316-683,tab-lucid-xerus-1736184379436-592,tab-dapper-salamander-1736184425132-768,tab-yakkety-fawn-1736184510430-936,tab-intrepid-fawn-1736184513476-374,tab-raring-vervet-1736184530883-567
---3-54---
id: tab-dapper-jackalope-1734121169075-901
  ancestors: tab-oneiric-vervet-1734120579656-682
  children:  
---3-55---
id: tab-utopic-drake-1734121341228-537
  ancestors: tab-oneiric-vervet-1734120579656-682
  children:  
---3-56---
id: tab-warty-eft-1734121419498-124
  ancestors: tab-oneiric-vervet-1734120579656-682
  children:  
---3-57---
id: tab-edgy-yak-1734121869379-523
  ancestors: tab-oneiric-vervet-1734120579656-682
  children:  
---3-58---
id: tab-intrepid-ocelot-1734121888687-304
  ancestors: tab-oneiric-vervet-1734120579656-682
  children:  
---3-59---
id: tab-zesty-tahr-1736184123663-162
  ancestors: tab-oneiric-vervet-1734120579656-682
  children:  
---3-60---
id: tab-lucid-heron-1736184206393-110
  ancestors: tab-oneiric-vervet-1734120579656-682
  children:  
---3-61---
id: tab-jaunty-eft-1736184296168-230
  ancestors: tab-oneiric-vervet-1734120579656-682
  children:  
---3-62---
id: tab-intrepid-heron-1736184340316-683
  ancestors: tab-oneiric-vervet-1734120579656-682
  children:  
---3-63---
id: tab-lucid-xerus-1736184379436-592
  ancestors: tab-oneiric-vervet-1734120579656-682
  children:  
---3-64---
id: tab-dapper-salamander-1736184425132-768
  ancestors: tab-oneiric-vervet-1734120579656-682
  children:  
---3-65---
id: tab-yakkety-fawn-1736184510430-936
  ancestors: tab-oneiric-vervet-1734120579656-682
  children:  
---3-66---
id: tab-intrepid-fawn-1736184513476-374
  ancestors: tab-oneiric-vervet-1734120579656-682
  children:  
---3-67---
id: tab-raring-vervet-1736184530883-567
  ancestors: tab-oneiric-vervet-1734120579656-682
  children:  
---3-68---
id: tab-agile-badger-1735320385885-820
  ancestors: 
  children:  
---3-69---
id: tab-cheerful-ringtail-1735322751084-383
  ancestors: 
  children:  tab-gutsy-zapus-1735322835029-405
---3-70---
id: tab-gutsy-zapus-1735322835029-405
  ancestors: tab-cheerful-ringtail-1735322751084-383
  children:  
---3-71---
id: tab-karmic-tahr-1735765451103-897
  ancestors: 
  children:  
---3-72---
id: tab-zesty-ocelot-1735833003561-766
  ancestors: 
  children:  
---3-73---
id: tab-precise-ringtail-1735936910079-329
  ancestors: 
  children:  tab-jaunty-werwolf-1735937118386-402
---3-74---
id: tab-jaunty-werwolf-1735937118386-402
  ancestors: tab-precise-ringtail-1735936910079-329
  children:  
---3-75---
id: tab-saucy-eft-1735937149967-776
  ancestors: 
  children:  
---3-76---
id: tab-xenial-quetzal-1735937326895-313
  ancestors: 
  children:  
---3-2---
id: tab-jaunty-yak-1736184568215-206
  ancestors: 
  children:  
---3-77---
id: tab-warty-ocelot-1736266108814-13
  ancestors: 
  children:  tab-agile-pangolin-1736266233469-959,tab-edgy-xerus-1736266274564-810
---3-80---
id: tab-natty-meerkat-1736367911295-473
  ancestors: 
  children:  
---3-81---
id: tab-oneiric-jackalope-1736369169299-49
  ancestors: 
  children:  
---3-162---
id: tab-xenial-werwolf-1736437483907-723
  ancestors: 
  children:  tab-marveric-yak-1736437501909-239
---3-163---
id: tab-marveric-yak-1736437501909-239
  ancestors: tab-xenial-werwolf-1736437483907-723
  children:  tab-hoary-lynx-1736437716749-928
---3-164---
id: tab-hoary-lynx-1736437716749-928
  ancestors: tab-marveric-yak-1736437501909-239,tab-xenial-werwolf-1736437483907-723
  children:  tab-raring-tahr-1736437822154-895
---3-165---
id: tab-raring-tahr-1736437822154-895
  ancestors: tab-hoary-lynx-1736437716749-928,tab-marveric-yak-1736437501909-239,tab-xenial-werwolf-1736437483907-723
  children:  tab-agile-gibbon-1736438034920-809,tab-yakkety-eft-1736438064392-16,tab-agile-cat-1736438093404-23
---3-166---
id: tab-agile-gibbon-1736438034920-809
  ancestors: tab-raring-tahr-1736437822154-895,tab-hoary-lynx-1736437716749-928,tab-marveric-yak-1736437501909-239,tab-xenial-werwolf-1736437483907-723
  children:  
---3-167---
id: tab-yakkety-eft-1736438064392-16
  ancestors: tab-raring-tahr-1736437822154-895,tab-hoary-lynx-1736437716749-928,tab-marveric-yak-1736437501909-239,tab-xenial-werwolf-1736437483907-723
  children:  
---3-168---
id: tab-agile-cat-1736438093404-23
  ancestors: tab-raring-tahr-1736437822154-895,tab-hoary-lynx-1736437716749-928,tab-marveric-yak-1736437501909-239,tab-xenial-werwolf-1736437483907-723
  children:  
---3-170---
id: tab-hoary-narwhal-1736438393855-43
  ancestors: 
  children:  
---130-106---
id: tab-natty-jackalope-1720474200710-113
  ancestors: 
  children:  tab-agile-eft-1720536534370-315
---130-107---
id: tab-agile-eft-1720536534370-315
  ancestors: tab-natty-jackalope-1720474200710-113
  children:  
---130-108---
id: tab-xenial-eft-1724787488846-54
  ancestors: 
  children:  
---130-109---
id: tab-edgy-meerkat-1726243204184-176
  ancestors: 
  children:  tab-natty-salamander-1726251583712-557,tab-vivid-vervet-1726675019096-590,tab-utopic-meerkat-1727365608512-306,tab-intrepid-meerkat-1735316154143-535
---130-110---
id: tab-natty-salamander-1726251583712-557
  ancestors: tab-edgy-meerkat-1726243204184-176
  children:  
---130-111---
id: tab-vivid-vervet-1726675019096-590
  ancestors: tab-edgy-meerkat-1726243204184-176
  children:  
---130-112---
id: tab-utopic-meerkat-1727365608512-306
  ancestors: tab-edgy-meerkat-1726243204184-176
  children:  
---130-113---
id: tab-intrepid-meerkat-1735316154143-535
  ancestors: tab-edgy-meerkat-1726243204184-176
  children:  
---130-114---
id: tab-vivid-zapus-1735316160001-191
  ancestors: 
  children:  
---130-115---
id: tab-xenial-alpaca-1727284064841-243
  ancestors: 
  children:  tab-utopic-unicorn-1727284072868-661
---130-116---
id: tab-utopic-unicorn-1727284072868-661
  ancestors: tab-xenial-alpaca-1727284064841-243
  children:  
---130-117---
id: tab-yakkety-vervet-1730133044366-341
  ancestors: 
  children:  tab-dapper-ocelot-1730133123402-447
---130-118---
id: tab-dapper-ocelot-1730133123402-447
  ancestors: tab-yakkety-vervet-1730133044366-341
  children:  
---130-119---
id: tab-precise-ibis-1733154701891-273
  ancestors: 
  children:  tab-quantal-jackalope-1733154713510-865
---130-120---
id: tab-quantal-jackalope-1733154713510-865
  ancestors: tab-precise-ibis-1733154701891-273
  children:  tab-warty-ocelot-1733342586384-460
---130-121---
id: tab-warty-ocelot-1733342586384-460
  ancestors: tab-quantal-jackalope-1733154713510-865,tab-precise-ibis-1733154701891-273
  children:  tab-raring-quetzal-1733342922990-598
---130-122---
id: tab-raring-quetzal-1733342922990-598
  ancestors: tab-warty-ocelot-1733342586384-460,tab-quantal-jackalope-1733154713510-865,tab-precise-ibis-1733154701891-273
  children:  
---130-123---
id: tab-agile-koala-1733239540031-69
  ancestors: 
  children:  tab-feisty-eft-1733239563551-115
---130-124---
id: tab-feisty-eft-1733239563551-115
  ancestors: tab-agile-koala-1733239540031-69
  children:  
---130-125---
id: tab-trusty-lynx-1733247455094-628
  ancestors: 
  children:  
---130-126---
id: tab-lucid-badger-1733247542144-751
  ancestors: 
  children:  tab-raring-heron-1733248282250-856,tab-xenial-drake-1733248283121-698
---130-127---
id: tab-raring-heron-1733248282250-856
  ancestors: tab-lucid-badger-1733247542144-751
  children:  
---130-128---
id: tab-xenial-drake-1733248283121-698
  ancestors: tab-lucid-badger-1733247542144-751
  children:  
---130-129---
id: tab-zesty-vervet-1733250450568-362
  ancestors: 
  children:  tab-karmic-eft-1733344618393-405
---130-130---
id: tab-karmic-eft-1733344618393-405
  ancestors: tab-zesty-vervet-1733250450568-362
  children:  
---130-131---
id: tab-quantal-meerkat-1733346356584-30
  ancestors: 
  children:  
---130-132---
id: tab-lucid-cat-1733358212151-800
  ancestors: 
  children:  
---130-133---
id: tab-edgy-pangolin-1733424605886-207
  ancestors: 
  children:  tab-warty-werwolf-1733425798148-890,tab-agile-lynx-1733425799757-77
---130-134---
id: tab-warty-werwolf-1733425798148-890
  ancestors: tab-edgy-pangolin-1733424605886-207
  children:  
---130-135---
id: tab-agile-lynx-1733425799757-77
  ancestors: tab-edgy-pangolin-1733424605886-207
  children:  
---130-136---
id: tab-quantal-zapus-1733425224488-356
  ancestors: 
  children:  
---130-137---
id: tab-vivid-yak-1734014749563-696
  ancestors: 
  children:  tab-yakkety-yak-1734014781364-987
---130-138---
id: tab-yakkety-yak-1734014781364-987
  ancestors: tab-vivid-yak-1734014749563-696
  children:  
---130-139---
id: tab-gutsy-salamander-1734014900611-481
  ancestors: 
  children:  tab-natty-narwhal-1734014921717-909,tab-zesty-ringtail-1734015102908-154,tab-gutsy-cat-1734016362674-814
---130-140---
id: tab-natty-narwhal-1734014921717-909
  ancestors: tab-gutsy-salamander-1734014900611-481
  children:  tab-natty-tahr-1734014945034-186
---130-141---
id: tab-natty-tahr-1734014945034-186
  ancestors: tab-natty-narwhal-1734014921717-909,tab-gutsy-salamander-1734014900611-481
  children:  
---130-142---
id: tab-zesty-ringtail-1734015102908-154
  ancestors: tab-gutsy-salamander-1734014900611-481
  children:  tab-intrepid-eft-1734015154395-269,tab-xenial-meerkat-1734015155865-7,tab-raring-koala-1734016051960-344
---130-143---
id: tab-intrepid-eft-1734015154395-269
  ancestors: tab-zesty-ringtail-1734015102908-154,tab-gutsy-salamander-1734014900611-481
  children:  tab-vivid-meerkat-1734016096181-445
---130-144---
id: tab-vivid-meerkat-1734016096181-445
  ancestors: tab-intrepid-eft-1734015154395-269,tab-zesty-ringtail-1734015102908-154,tab-gutsy-salamander-1734014900611-481
  children:  
---130-145---
id: tab-xenial-meerkat-1734015155865-7
  ancestors: tab-zesty-ringtail-1734015102908-154,tab-gutsy-salamander-1734014900611-481
  children:  
---130-146---
id: tab-raring-koala-1734016051960-344
  ancestors: tab-zesty-ringtail-1734015102908-154,tab-gutsy-salamander-1734014900611-481
  children:  
---130-147---
id: tab-gutsy-cat-1734016362674-814
  ancestors: tab-gutsy-salamander-1734014900611-481
  children:  
---130-148---
id: tab-xenial-jackalope-1735317726111-125
  ancestors: 
  children:  
---130-149---
id: tab-gutsy-tahr-1735319977863-560
  ancestors: 
  children:  
---130-150---
id: tab-karmic-drake-1735320037608-625
  ancestors: 
  children:  tab-intrepid-salamander-1735320045754-818
---130-151---
id: tab-intrepid-salamander-1735320045754-818
  ancestors: tab-karmic-drake-1735320037608-625
  children:  tab-saucy-fawn-1735320103335-227
---130-152---
id: tab-saucy-fawn-1735320103335-227
  ancestors: tab-intrepid-salamander-1735320045754-818,tab-karmic-drake-1735320037608-625
  children:  
---130-153---
id: tab-natty-ringtail-1735320470884-999
  ancestors: 
  children:  
---130-154---
id: tab-yakkety-koala-1735321322537-574
  ancestors: 
  children:  tab-quantal-eft-1735321373614-738,tab-zesty-jackalope-1735330539042-12
---130-156---
id: tab-quantal-eft-1735321373614-738
  ancestors: tab-yakkety-koala-1735321322537-574
  children:  
---130-157---
id: tab-zesty-jackalope-1735330539042-12
  ancestors: tab-yakkety-koala-1735321322537-574
  children:  
---130-155---
id: tab-quantal-werwolf-1736184655909-50
  ancestors: 
  children:  
---130-158---
id: tab-natty-ocelot-1736187111289-444
  ancestors: 
  children:  
---130-159---
id: tab-hoary-heron-1736187290416-75
  ancestors: 
  children:  
---130-160---
id: tab-dapper-yak-1736190856422-376
  ancestors: 
  children:  
---130-161---
id: tab-trusty-alpaca-1736191074276-439
  ancestors: 
  children:  
---130-3---
id: tab-trusty-drake-1736192043880-444
  ancestors: 
  children:  
---132-82---
id: tab-agile-gibbon-1736196460392-978
  ancestors: 
  children:  
---132-83---
id: tab-saucy-cat-1736267496657-603
  ancestors: 
  children:  
---132-84---
id: tab-jaunty-ibis-1736267598338-519
  ancestors: 
  children:  tab-utopic-badger-1736267621861-696
---132-85---
id: tab-utopic-badger-1736267621861-696
  ancestors: tab-jaunty-ibis-1736267598338-519
  children:  
---132-86---
id: tab-edgy-ibis-1736268940882-88
  ancestors: 
  children:  tab-yakkety-fawn-1736268953666-750,tab-zesty-quetzal-1736268964485-816,tab-raring-koala-1736287303213-894
---132-87---
id: tab-yakkety-fawn-1736268953666-750
  ancestors: tab-edgy-ibis-1736268940882-88
  children:  tab-yakkety-ringtail-1736291188665-575
---132-88---
id: tab-yakkety-ringtail-1736291188665-575
  ancestors: tab-yakkety-fawn-1736268953666-750,tab-edgy-ibis-1736268940882-88
  children:  
---132-89---
id: tab-zesty-quetzal-1736268964485-816
  ancestors: tab-edgy-ibis-1736268940882-88
  children:  tab-intrepid-drake-1736291276409-645
---132-90---
id: tab-intrepid-drake-1736291276409-645
  ancestors: tab-zesty-quetzal-1736268964485-816,tab-edgy-ibis-1736268940882-88
  children:  
---132-91---
id: tab-raring-koala-1736287303213-894
  ancestors: tab-edgy-ibis-1736268940882-88
  children:  
---132-92---
id: tab-oneiric-cat-1736270894586-282
  ancestors: 
  children:  tab-utopic-pangolin-1736292020859-596
---132-93---
id: tab-utopic-pangolin-1736292020859-596
  ancestors: tab-oneiric-cat-1736270894586-282
  children:  tab-edgy-tahr-1736292041487-951
---132-94---
id: tab-edgy-tahr-1736292041487-951
  ancestors: tab-utopic-pangolin-1736292020859-596,tab-oneiric-cat-1736270894586-282
  children:  
---132-95---
id: tab-yakkety-koala-1736271127139-894
  ancestors: 
  children:  
---132-96---
id: tab-oneiric-alpaca-1736271743226-397
  ancestors: 
  children:  
---132-97---
id: tab-vivid-badger-1736272037124-398
  ancestors: 
  children:  
---132-98---
id: tab-vivid-zapus-1736272063550-35
  ancestors: 
  children:  
---132-99---
id: tab-precise-lynx-1736285507156-104
  ancestors: 
  children:  tab-saucy-werwolf-1736285723398-851
---132-100---
id: tab-saucy-werwolf-1736285723398-851
  ancestors: tab-precise-lynx-1736285507156-104
  children:  
---132-101---
id: tab-natty-zapus-1736286373768-585
  ancestors: 
  children:  tab-edgy-pangolin-1736286531977-472
---132-102---
id: tab-edgy-pangolin-1736286531977-472
  ancestors: tab-natty-zapus-1736286373768-585
  children:  
---132-103---
id: tab-vivid-ibis-1736286646923-897
  ancestors: 
  children:  
---132-104---
id: tab-utopic-ocelot-1736287249378-624
  ancestors: 
  children:  
---132-105---
id: tab-trusty-xerus-1736287345561-691
  ancestors: 
  children:  
---132-4---
id: tab-intrepid-salamander-1736290990527-26
  ancestors: 
  children:  
debugger eval code:6:29
```
