### ISSUE TITLE
4.1.1 mute button theming is broken

### ISSUE THREAD

**Issue by awused** [piroor/treestyletab#3696]
## Abstract

![01-10_18-32-37](https://github.com/user-attachments/assets/3afbf5dd-c2be-44d5-b295-2c4d5c94fab3)

## Steps to reproduce

 1. Set theme to Photon
 2. Update to 4.1.1

## Expected result
Audio playing indicator/mute button looks like it did before.

## Actual result

Mute button is giant and unthemed.

**Comment by awused** [comment]
The styling is also broken outright in the high contrast theme, with the foreground and background being the same colour.

![01-10_18-46-28](https://github.com/user-attachments/assets/508ff9bb-1097-4cd7-b01b-c05d268e69dd)

**Comment by enzo-simone** [comment]
Same for me.

**Comment by Zelman88** [comment]
Also have this problem.

**Comment by enzo-simone** [comment]
Update: I do have this issue on a laptop running Linux Mint 22 Cinnamon, while it is not seen on another laptop running Ubuntu 20.04; both uses the latest available version of Firefox.

**Comment by piroor** [comment]
Sorry I missed this. The appearance of the "sound playing" button will be uniformed on all themes, with the commit 04cf13b. Screenshots with the commit:
![image](https://github.com/user-attachments/assets/be22f1d6-c458-4ae1-b43d-43cf822c07ba)
![image](https://github.com/user-attachments/assets/125e9d7a-b7ea-4cd9-b50d-497387b51b82)

**Comment by clockwinder** [comment]
Here's the fix I'm using in the mean time. https://github.com/piroor/treestyletab/discussions/3695

**Comment by tcbbd** [comment]
> Sorry I missed this. The appearance of the "sound playing" button will be uniformed on all themes, with the commit [04cf13b](https://github.com/piroor/treestyletab/commit/04cf13b7452a2e4d7d94cdbe80d7fb7b3af1cb5e). Screenshots with the commit: ![image](https://github.com/user-attachments/assets/be22f1d6-c458-4ae1-b43d-43cf822c07ba) ![image](https://github.com/user-attachments/assets/125e9d7a-b7ea-4cd9-b50d-497387b51b82)

It is white icon on black background on your configuration. But it's black icon on black background on mine, so I can't see the icon. Currently I use this workaround:

```css
tab-sound-button::before {
  background: white;
}

tab-sound-button {
  filter: invert();
}
```

**Comment by nk-tedo-001** [comment]
I'm on 4.1.3 and this is how my media button looks like 
<img width="152" alt="Image" src="https://github.com/user-attachments/assets/90d6ef66-bbe7-432a-8074-6e381fef4418" />

Workaround with custom theme is helped, but it would be nice to have it fixed
<img width="112" alt="Image" src="https://github.com/user-attachments/assets/d3ee11eb-423f-4bd7-8920-36d5158d8886" />

**Comment by piroor** [comment]
@tcbbd @nk-tedo-001 Does your problem still happen with Firefox's system theme and no userChrome.css, no user stylesheet in TST's options? What themes of Firefox and the platform do you use?

**Comment by nk-tedo-001** [comment]
> no userChrome.css

Oh, I have it but it seems like there is nothing to conflict with the media icon

```
#main-window[tabsintitlebar="true"]:not([extradragspace="true"]) #TabsToolbar {
    opacity: 0;
    pointer-events: none;
}

#main-window:not([tabsintitlebar="true"]) #TabsToolbar {
    visibility: collapse !important;
}
#sidebar-box[sidebarcommand="treestyletab_piro_sakura_ne_jp-sidebar-action"] #sidebar-header {
  display: none;
}
```

Also for my user stylesheet - there is only a workaround

<details>
<summary>Screenshot</summary>

<img width="674" alt="Image" src="https://github.com/user-attachments/assets/575e6a21-a61d-4650-b221-02dc9e69c0b9" />

</details>


>What themes of Firefox and the platform do you use?

**Theme** - System Auto
**Version** 	134.0.2
**OS** 	Darwin 24.2.0 Darwin Kernel Version 24.2.0: Fri Dec 6 19:01:59 PST 2024; root:xnu-11215.61.5~2/RELEASE_ARM64_T6000 (MacOS Apple Silicon)

**Comment by tcbbd** [comment]
@piroor  The problem disappears in a fresh profile. But it seem this is not related to userChrome.css or user style. Because when I import those from my daily profile into the new profile, the mute button still works fine. I'm not sure what addon or config option causes the problem.

**Theme** - System Auto
**Version** - 135.0
**OS** - Windows_NT 10.0 19045

---

Okay, I found that on my daily profile, the addon activates this style:

```css
tab-item:not(.collapsed).sound-playing:not(.muted) tab-sound-button::after,
tab-item:not(.collapsed).has-sound-playing-member.subtree-collapsed[data-child-ids]
  tab-sound-button::after {
  background-image: url("./icons/audio-16.svg");
}
```

But on the fresh profile, the addon activates this style:

```css
:root.simulate-svg-context-fill tab-item:not(.collapsed).sound-playing:not(.muted) tab-sound-button::after,
:root.simulate-svg-context-fill tab-item:not(.collapsed).has-sound-playing-member.subtree-collapsed[data-child-ids]
  tab-sound-button::after {
  background-image: none;
  mask-image: url("./icons/audio-16.svg");
}
```

Both are on Tree Style Tab 4.1.3.
