### ISSUE TITLE
[Enhancement] (add vertical lines or dotted line to indicate spacing)

### ISSUE THREAD

**Issue by zaidamazon191** [piroor/treestyletab#3738]
## Abstract
Is it possible to add a vertical line to line up the level of indents for visual ease? similar to [indent blankline](https://github.com/lukas-reineke/indent-blankline.nvim?tab=readme-ov-file#screenshots)

**Comment by piroor** [comment]
Please try [TST Indent Line](https://addons.mozilla.org/firefox/addon/tst-indent-line/).

**Comment by zaidamazon191** [comment]
It doesn't seem to work if I have a custom margins set. This is what it looks like

<img width="100" alt="Image" src="https://github.com/user-attachments/assets/e4211b7b-73e4-4d36-b65c-dc1090129f18" />

I have

```
tab-item[data-level][data-level="0"] tab-item-substance {
  margin-left: 5px !important;
}
tab-item[data-level][data-level="1"] tab-item-substance {
  margin-left: 50px !important;
}
tab-item[data-level][data-level="2"] tab-item-substance {
  margin-left: 90px !important;
}
tab-item[data-level][data-level="3"] tab-item-substance {
  margin-left: 130px !important;
}
tab-item[data-level][data-level="4"] tab-item-substance {
  margin-left: 170px !important;
}
tab-item[data-level][data-level="5"] tab-item-substance {
  margin-left: 210px !important;
}
tab-item[data-level][data-level="6"] tab-item-substance {
  margin-left: 250px !important;
}
tab-item[data-level][data-level="7"] tab-item-substance {
  margin-left: 290px !important;
}
tab-item[data-level][data-level="8"] tab-item-substance {
  margin-left: 330px !important;
}
tab-item[data-level][data-level="9"] tab-item-substance {
  margin-left: 370px !important;
}
tab-item[data-level][data-level="10"] tab-item-substance {
  margin-left: 410px !important;
}
tab-item[data-level][data-level="11"] tab-item-substance {
  margin-left: 450px !important;
}
tab-item[data-level][data-level="12"] tab-item-substance {
  margin-left: 490px !important;
}
tab-item[data-level][data-level="13"] tab-item-substance {
  margin-left: 530px !important;
}
tab-item[data-level][data-level="14"] tab-item-substance {
  margin-left: 570px !important;
}

```

**Comment by piroor** [comment]
Using TST specific CSS variables to customize indent levels will help you, for example:

```css
:root {
  --indent-size: 40px !important;
}
tab-item[data-level][data-level="0"] {
  --tab-indent: 5px !important;
}
tab-item[data-level][data-level="1"] {
  --tab-indent: 50px !important;
}
tab-item[data-level][data-level="2"] {
  --tab-indent: 90px !important;
}
tab-item[data-level][data-level="3"] {
  --tab-indent: 130px !important;
}
tab-item[data-level][data-level="4"] {
  --tab-indent: 170px !important;
}
tab-item[data-level][data-level="5"] {
  --tab-indent: 210px !important;
}
tab-item[data-level][data-level="6"] {
  --tab-indent: 250px !important;
}
tab-item[data-level][data-level="7"] {
  --tab-indent: 290px !important;
}
tab-item[data-level][data-level="8"] {
  --tab-indent: 330px !important;
}
tab-item[data-level][data-level="9"] {
  --tab-indent: 370px !important;
}
tab-item[data-level][data-level="10"] {
  --tab-indent: 410px !important;
}
tab-item[data-level][data-level="11"] {
  --tab-indent: 450px !important;
}
tab-item[data-level][data-level="12"] {
  --tab-indent: 490px !important;
}
tab-item[data-level][data-level="13"] {
  --tab-indent: 530px !important;
}
tab-item[data-level][data-level="14"] {
  --tab-indent: 570px !important;
}
```

**Comment by Baerbeisser** [comment]
I have this in my Materialesque custom CSS:
```CSS
/* left border as indicator */
tab-item:not([data-level="0"]) span.background {
	border-left: 1px solid var(--text-unread);
}
tab-item:not([data-level="0"]):not(.active):hover span.background  {
	border-left-color: var(--border-hover-color);
}
tab-item.active:not([data-level="0"]) span.background {
	border-left-color: var(--border-active-color);
}
```

![Image](https://github.com/user-attachments/assets/efbdf0e9-5b0e-426d-b6aa-711f2d462161)

To research the DOM yourself, you can go to *about:debugging* > tab *This Firefox* > *Tree Style Tab* to open a floating dev console and choose in the top right square icon the respective sidebar (multiple windows, multiple sidebars).

![Image](https://github.com/user-attachments/assets/93f36fa4-4962-4be2-a397-f79509ebab55)

edit: just figured out an error in my CSS. Hover border needs some work.

Btw, this creates a pseudo-3D view to make layers more visible:
```CSS
/* debug view */
body * {
	border: 1px inset lightgray;
	margin: 1px 0 0 2px;
}
```
