### ISSUE TITLE
Weird colors since 4.2.0

### ISSUE THREAD

**Issue by rsalmei** [piroor/treestyletab#3742]
Hi,
Please, what happened with 4.2.0 that brought treestyletabs from this:

<img width="222" alt="Image" src="https://github.com/user-attachments/assets/2f1287c6-f288-4bf6-9ab0-4f1c637378a7" />

to this:

<img width="222" alt="Image" src="https://github.com/user-attachments/assets/a44edc8d-42bf-4c4d-90a1-232fd9f0352d" />

What can I do to restore it to its prior state?
I can barely read tabs anymore. Firefox 139.0.1 macOS.

Thank you!

**Comment by tarvip** [comment]
It is unusable, had to rollback to 4.1.11 and disabled auto updates for now. I also noticed that colors are normal when you make Firefox window inactive.

**Comment by piroor** [comment]
Sorry for my mistake. This should be fixed with the commit 7219b49.

This happens on the dark color scheme mode. Switching to the light color scheme may be a temporary solution, otherwise please apply a user stylesheet containing the change at the commit 7219b49, as a workaround.

**Comment by Napoleon-BlownApart** [comment]
[Firefox 139.0.1, TST 4.2.0, MacOS Sonoma 14.2.1 (Dark Mode)]

I have the same problem as @rsalmei  with all my tabs having a dark background with black text (using the default 'Sidebar' theme) when Firefox is in focus. 
How can I get TST to update using Firefox?  Firefox does not see an update to the TST addon and I don't see any way to manually ask it to check for an update.

Thanks in advance, and thanks for a great addon!

**Comment by piroor** [comment]
@Napoleon-BlownApart The commit to fix this will be included in TST 4.2.2 and later and it is not released yet. Please try the workaround I commented for now.

**Comment by Napoleon-BlownApart** [comment]
@piroor thanks for your reply. Where can I find instructions on how to setup a user stylesheet for this?

**Comment by piroor** [comment]
@Napoleon-BlownApart TST options => Advanced => User Style Sheet, paste this CSS to the text area:

```css
@media (prefers-color-scheme: dark), not (prefers-color-scheme: dark) {
  :root.sidebar,
  :root:not(.sidebar) {
    --bg-color: #d4dde5;
    --bg-color-inactive: #e8e8e8;
    --shadow-color: #404040;
    --shadow-color-inactive: #868686;
    --tab-like-surface: #d4dde5;
    --tab-surface-regular: transparent;
    --tab-surface-active-color: #94A1C0;
    --tab-surface-active-color-pale: #B4C1E0;
    --tab-surface-active-gradient: linear-gradient(to bottom, #A0B0CF, #7386AB) repeat-x;
    --tab-surface-active-gradient-pale: linear-gradient(to bottom, #C0D0EF, #93A6CB) repeat-x;
    --tab-surface-active-gradient-inactive: linear-gradient(to bottom, #B4B4B4, #8A8A8A) repeat-x;
    --tab-surface-active: var(--tab-surface-active-gradient);
    --tab-surface-active-hover: var(--tab-surface-active);
    --tab-text-regular: black;
    --tab-text-inverted: white;
    --tab-text-active: white;
    --badge-bg-color: #91a0c0;
    --badge-color-inactive: #b5b5b5;
    --badge-bg-color-inactive: #929292;
    --dropmarker-border-color: #577bf3;
    --dropmarker-bg-color: #d0def5;
    --throbber-color: white;
    --throbber-color-active: white;
    --throbber-shadow-color: var(--dropmarker-border-color);
    --tab-text-shadow: 0 1px var(--shadow-color);

    --tab-highlighted-highlight: white;
    --tab-highlighted-glow: var(--dropmarker-border-color);
    --tab-highlighted-base: var(--bg-color);

    --multiselected-color: var(--tab-surface-active-gradient);
    --multiselected-color-opacity: 0.35;

    --tab-vertical-padding: 0.075em; /* We should define this as a variable to reuse calculation of extra tab contents size. */
  }

  tab-item:not(.active) {
    --throbber-color: var(--dropmarker-border-color);
    --throbber-shadow-color: white;
  }

  /* Background colour for the tree sidebar (light blue when window is
     active, grey otherwise) */
  :root,
  body,
  #background {
    background: var(--bg-color);
  }

  :root:not(.active),
  :root:not(.active) #background {
    background: var(--bg-color-inactive);
  }

  /* Use the splitter to display the border of tab-items */
  :root.left:not(.rtl),
  :root.right.rtl {
    border-inline-end: 1px solid var(--shadow-color);
  }
  :root:not(.active).left:not(.rtl),
  :root:not(.active).right.rtl {
    border-inline-end-color: var(--shadow-color-inactive);
  }

  :root.right:not(.rtl),
  :root.left.rtl {
    border-inline-start: 1px solid var(--shadow-color);
  }
  :root:not(.active).right:not(.rtl),
  :root:not(.active).left.rtl {
    border-inline-start-color: var(--shadow-color-inactive);
  }
}
```

**Comment by Napoleon-BlownApart** [comment]
Thanks, that works perfectly!

**Comment by jamessonbarreto** [comment]
This one fixed for me too. Just a small change. This will make the active (selected) tab’s background color #BBD8EA and keep the active tab’s text black.

```css
@media (prefers-color-scheme: dark), not (prefers-color-scheme: dark) {
  :root.sidebar,
  :root:not(.sidebar) {
    --bg-color: #d4dde5;
    --bg-color-inactive: #e8e8e8;
    --shadow-color: #404040;
    --shadow-color-inactive: #868686;
    --tab-like-surface: #d4dde5;
    --tab-surface-regular: transparent;
    --tab-surface-active: #BBD8EA !important; /* Active tab background: #BBD8EA */
    --tab-surface-active-hover: ##486d84 !important;
    --tab-surface-active-gradient: ##486d84 !important;
    --tab-surface-active-gradient-pale: ##486d84 !important;
    --tab-surface-active-gradient-inactive: ##486d84 !important;
    --tab-text-regular: black;
    --tab-text-inverted: white;
    --tab-text-active: black !important; /* Active tab text: black */
    --badge-bg-color: #91a0c0;
    --badge-color-inactive: #b5b5b5;
    --badge-bg-color-inactive: #929292;
    --dropmarker-border-color: #577bf3;
    --dropmarker-bg-color: #d0def5;
    --throbber-color: white;
    --throbber-color-active: white;
    --throbber-shadow-color: var(--dropmarker-border-color);
    --tab-text-shadow: 0 1px var(--shadow-color);

    --tab-highlighted-highlight: white;
    --tab-highlighted-glow: var(--dropmarker-border-color);
    --tab-highlighted-base: var(--bg-color);

    --multiselected-color: ##486d84 !important;
    --multiselected-color-opacity: 0.35;

    --tab-vertical-padding: 0.075em;
  }

  tab-item:not(.active) {
    --throbber-color: var(--dropmarker-border-color);
    --throbber-shadow-color: white;
  }

  :root,
  body,
  #background {
    background: var(--bg-color);
  }

  :root:not(.active),
  :root:not(.active) #background {
    background: var(--bg-color-inactive);
  }

  :root.left:not(.rtl),
  :root.right.rtl {
    border-inline-end: 1px solid var(--shadow-color);
  }
  :root:not(.active).left:not(.rtl),
  :root:not(.active).right.rtl {
    border-inline-end-color: var(--shadow-color-inactive);
  }

  :root.right:not(.rtl),
  :root.left.rtl {
    border-inline-start: 1px solid var(--shadow-color);
  }
  :root:not(.active).right:not(.rtl),
  :root:not(.active).left.rtl {
    border-inline-start-color: var(--shadow-color-inactive);
  }

  /* Ensure active tab text is black and background is #BBD8EA */
  tab-item.active {
    background: #486d84 !important;
    color: #000 !important;
  }
}
```
