### ISSUE TITLE
An indent before and after vertical tab list, win7, Fx36.0.4

### ISSUE THREAD

**Issue by arni2033** [piroor/treestyletab#863]
I'm using default theme for Firefox, and mixed theme in TST, but the bug appears on every TST theme. As you can see on attached pics, there's ~1px indent before tabs, when the scroll is moved from it's higher position, AND the scrollbar itself is moved by ~1px when the scroll moved to it's lower position.
This bug may be fixed by simple CSS rule:
```css
/* spacers before and after <xul:scrollbox> that contains tabs */
spacer.arrowscrollbox-overflow-start-indicator,
spacer.arrowscrollbox-overflow-end-indicator
{
	display:none!important;
}
```
Images: [tst 1](https://cloud.githubusercontent.com/assets/9205283/6881715/e65d90e0-d584-11e4-8a95-9301c85c1720.png), [tst 2](https://cloud.githubusercontent.com/assets/9205283/6881716/e9c0349a-d584-11e4-85d1-45e088ba976a.png), [tst 3](https://cloud.githubusercontent.com/assets/9205283/6881717/ebe4dc26-d584-11e4-8c50-b539e343d403.png)
